import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
await build({stdin:{contents:"export {bubbleWork} from './lib/bubble-work';export {IslandScene} from './components/grade/island-scene';export {SubjectWorld} from './components/grade/subject-world';",resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',outfile:'.sites-runtime/bubble-work-test.mjs'});
const {bubbleWork,IslandScene,SubjectWorld}=await import('../.sites-runtime/bubble-work-test.mjs');
const courses=[{id:'c',subject_id:'subject',classroom:'1/1'},{id:'c2',subject_id:'subject',classroom:'1/2'}];
const task=(id,course='c',due='2026-10-15T00:00:00Z')=>({id,course_id:course,title:id,due_at:due,max_score:10});
const state={user:{id:'me',role:'student'},subjects:[{id:'subject',code:'TEST01',name:'วิชาทดสอบ'}],courses,enrollments:[{id:'e',course_id:'c',student_id:'me',active:1},{id:'e2',course_id:'c',student_id:'other',active:1},{id:'e3',course_id:'c2',student_id:'other',active:1},{id:'inactive',course_id:'c',student_id:'inactive',active:0}],assignments:[task('graded'),task('pending'),task('returned'),task('missing'),task('other-room','c2'),{...task('deleted'),deleted:1}],submissions:[{id:'1',assignment_id:'graded',student_id:'me',status:'graded'},{id:'2',assignment_id:'pending',student_id:'me',status:'pending'},{id:'3',assignment_id:'returned',student_id:'me',status:'returned'},{id:'4',assignment_id:'missing',student_id:'other',status:'graded'}],files:[{id:'student-photo',assignment_id:'returned',student_id:'other',mime:'image/png'},{id:'completed-photo',assignment_id:'graded',student_id:null,mime:'image/png'},{id:'deleted-photo',assignment_id:'returned',student_id:null,mime:'image/png',deleted:1},{id:'sample',assignment_id:'returned',student_id:null,mime:'image/png'}],extensions:[],periods:[],students:[],staff:[],people:[],profiles:[],history:[]};
let work=bubbleWork(state,courses);assert.deepEqual(work.map(t=>t.assignment.id),['returned','missing']);assert.equal(work[0].preview,'/api/file/sample');assert.equal(work[1].preview,undefined);assert.equal(work[1].missing,1);
const extended={...state,assignments:[task('early','c','2026-10-12T00:00:00Z'),task('later','c','2026-10-16T00:00:00Z')],submissions:[],extensions:[{id:'x',assignment_id:'early',student_id:'me',due_at:'2026-10-20T00:00:00Z'}]};assert.deepEqual(bubbleWork(extended,courses).map(t=>t.assignment.id),['later','early']);
console.log('PASS own active roster, missing and returned work only; teacher samples only; individual deadline extensions determine priority');
const teacher={...state,user:{id:'teacher',role:'teacher'}};work=bubbleWork(teacher,courses);assert.equal(work.find(t=>t.assignment.id==='missing').missing,1);assert.equal(work.find(t=>t.assignment.id==='returned').missing,1);assert.equal(work.find(t=>t.assignment.id==='returned').returned,1);assert(work.some(t=>t.assignment.id==='other-room'));assert(!work.some(t=>t.assignment.id==='deleted'));assert.equal(bubbleWork({...state,submissions:[...state.submissions.filter(s=>s.assignment_id!=='returned'),{id:'5',assignment_id:'missing',student_id:'me',status:'pending'},{id:'6',assignment_id:'returned',student_id:'me',status:'graded'}]},courses).length,0);
console.log('PASS teacher counts active students across rooms; submitted and corrected tasks disappear from the bubble after refresh');
const html=renderToStaticMarkup(createElement(SubjectWorld,{state,courses,activeId:'subject',onRoom:()=>{},onSubject:()=>{},onTask:()=>{}}));assert(html.includes('src="/api/file/sample"'));assert(html.includes('ตัวอย่างงาน returned'));assert(html.includes('งานค้าง 2 งาน'));assert(!html.includes('/api/file/student-photo'));assert(!html.includes('/api/file/completed-photo'));
const empty=renderToStaticMarkup(createElement(IslandScene,{subjects:[{id:'s',code:'T',name:'วิชา',roomCount:1,hasAssignments:true,outstandingCount:0}],focusedId:'s',onPick:()=>{}}));assert(empty.includes('ไม่มีงานค้าง'));assert(!empty.includes('<img'));
console.log('PASS bubble renders the actual outstanding task thumbnail, title and count; completed subjects show a clear empty state');

