import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const base=process.env.GRADE_TEST_URL;if(!/^http:\/\/127\.0\.0\.1:/.test(base||''))throw Error('Use isolated worker only');
const creds=JSON.parse(await readFile('../Grade-direct-verification/test-login.json','utf8'));
function client(){let cookie='';return async(path,body,method='POST',expected=200)=>{const r=await fetch(`${base}/api/${path}`,{method:body===undefined?'GET':method,headers:{Connection:'close',...(cookie?{Cookie:cookie}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const b=await r.json();assert.equal(r.status,expected,path+': '+JSON.stringify(b));return b;};}
const admin=client();await admin('login',creds);
if(process.env.EXAM_TIME_PHASE){const fixture=JSON.parse(await readFile('../Grade-direct-verification/exam-time.json','utf8'));const student=client();await student('login',{username:fixture.code,password:fixture.code});const stale=await student(`exam-attempts/${fixture.disconnect}`);assert.equal(stale.attempt.status,'locked');assert.match(stale.attempt.lock_reason,/30/);const expiry=await student(`exam-attempts/${fixture.deadline}`);assert.equal(expiry.attempt.status,'submitted');assert.equal(expiry.attempt.score,null);const teacher=await admin(`exam-attempts/${fixture.deadline}`);assert.equal(teacher.attempt.score,20);assert.equal((await admin('state')).enrollments.find(e=>e.id===teacher.attempt.enrollment_id).final,null);console.log('PASS Expired attempts auto-submit saved answers; missing heartbeat locks on the server without client cooperation');process.exit(0);}
const suffix=randomUUID().slice(0,6),student=client(),other=client(),outside=client(),viewer=client(),code='EXAM'+suffix;
const period=await admin('periods',{year:2581,term:1},'POST',201);const course=(await admin('courses',{periodId:period.id,code:'EX'+suffix,name:'รายวิชาทดสอบการสอบ',classrooms:['6/1','6/2'],workWeight:60,beforeWorkWeight:30,midWeight:20,finalWeight:20},'POST',201)).id;
await admin('students',{courseId:course,code,name:'นักเรียนสอบจำลอง',number:1},'POST',201);await admin('students',{courseId:course,code:code+'B',name:'นักเรียนอื่น',number:2},'POST',201);await student('login',{username:code,password:code});await other('login',{username:code+'B',password:code+'B'});
const qs=[{type:'choice',prompt:'หนึ่งบวกหนึ่งเท่ากับ?',points:10,options:['1','2','3','4'],correct:1},{type:'choice',prompt:'เมืองหลวงของไทย?',points:10,options:['กรุงเทพฯ','เชียงใหม่'],correct:0}];const config={courseId:course,title:'EXAM regression '+suffix,kind:'mid',duration:60,maxScore:20,questions:qs,unlockCode:'Teacher-'+suffix};
const exam=await admin('exams',config,'POST',201);await student('exams',config,'POST',403);assert.equal((await student(`exams/course/${course}`)).exams.length,0);await student(`exams/${exam.id}/start`,{},'POST',409);await admin('exams',{...config,questions:[qs[0]]},'POST',400);await admin(`exams/${exam.id}`,{...config,title:'แก้ก่อนสอบ'},'PATCH');await admin(`exams/${exam.id}`,{status:'open'},'PATCH');
const listed=(await student(`exams/course/${course}`)).exams[0];assert(!('questions' in listed));assert(!('unlock_hash' in listed));let page=await student(`exams/${exam.id}/start`,{},'POST',201),a=page.attempt;assert(page.questions.every(q=>!('correct' in q)));await admin(`exams/${exam.id}`,{...config},'PATCH',409);await other(`exam-attempts/${a.id}`,undefined,'POST',403);await student(`exams/${exam.id}`,undefined,'POST',403);await admin(`exams/${exam.id}/start`,{},'POST',403);
console.log('PASS Teacher exam authoring, publication, enrollment ownership and answer-key privacy');
const auth=()=>({token:a.page_token,generation:a.generation});const saved={q0:1,q1:0};await student(`exam-attempts/${a.id}/save`,{...auth(),answers:saved});await student(`exam-attempts/${a.id}/heartbeat`,auth());assert.deepEqual(JSON.parse((await student(`exam-attempts/${a.id}`)).attempt.answers),saved);await student(`exam-attempts/${a.id}/lock`,{...auth(),reason:'สลับแท็บ',answers:saved});await student(`exam-attempts/${a.id}/save`,{...auth(),answers:{}},'POST',423);await student(`exam-attempts/${a.id}/submit`,{...auth(),answers:saved},'POST',423);await student(`exam-attempts/${a.id}/unlock`,{code:'incorrect'},'POST',403);const old=auth();page=await student(`exam-attempts/${a.id}/unlock`,{code:config.unlockCode});a=page.attempt;assert.deepEqual(JSON.parse(a.answers),saved);assert.equal(a.deadline,page.attempt.deadline);assert.notEqual(a.page_token,old.token);await student(`exam-attempts/${a.id}/save`,{...old,answers:{}},'POST',409);await student(`exam-attempts/${a.id}/lock`,{...old,reason:'stale page'},'POST',409);await student(`exam-attempts/${a.id}/save`,{...auth(),answers:saved});page=await student(`exams/${exam.id}/start`,{});assert.equal(page.attempt.status,'locked');assert.equal(page.questions.length,0);page=await student(`exams/${exam.id}/start`,{});assert.equal(page.attempt.status,'locked');page=await student(`exam-attempts/${a.id}/unlock`,{code:config.unlockCode});a=page.attempt;
console.log('PASS Immediate persistent lock, blocked saves/submissions, PIN unlock, stale page rejection and reload lock');
await student(`exam-attempts/${a.id}/submit`,{...auth(),answers:saved});const result=await admin(`exam-attempts/${a.id}`);assert.equal(result.attempt.score,20);assert.equal((await student(`exam-attempts/${a.id}`)).attempt.score,null);assert.equal((await student(`exams/course/${course}`)).exams[0].attempts[0].score,null);let state=await admin('state'),en=state.enrollments.find(e=>e.course_id===course&&e.student_code===code);assert.equal(en.mid,null);await admin(`exam-attempts/${a.id}/sync`,{});state=await admin('state');assert.equal(state.enrollments.find(e=>e.id===en.id).mid,20);assert.equal(state.courses.find(c=>c.id===course).published,0);await student(`exam-attempts/${a.id}/sync`,{},'POST',403);await admin(`exam-attempts/${a.id}/grade`,{score:21},'POST',400);await admin(`exam-attempts/${a.id}/grade`,{score:18});assert.equal((await admin(`exam-attempts/${a.id}`)).attempt.synced,0);await admin(`exam-attempts/${a.id}/sync`,{});assert.equal((await admin('state')).enrollments.find(e=>e.id===en.id).mid,18);
console.log('PASS Automatic choice scoring, hidden provisional scores, teacher adjustment and explicit transfer into midterm results');
const final=await admin('exams',{...config,kind:'final',questions:[{type:'written',prompt:'อธิบายสิ่งที่เรียน',points:20}]},'POST',201);await admin(`exams/${final.id}`,{status:'open'},'PATCH');let written=await student(`exams/${final.id}/start`,{},'POST',201);await student(`exam-attempts/${written.attempt.id}/submit`,{token:written.attempt.page_token,generation:0,answers:{q0:'คำตอบข้อเขียน'}});assert.equal((await admin(`exam-attempts/${written.attempt.id}`)).attempt.score,null);await admin(`exam-attempts/${written.attempt.id}/sync`,{},'POST',409);await admin(`exam-attempts/${written.attempt.id}/grade`,{score:17});await admin(`exam-attempts/${written.attempt.id}/sync`,{});assert.equal((await admin('state')).enrollments.find(e=>e.id===en.id).final,17);
console.log('PASS Written questions require teacher grading and transfer into final-exam results');
const preview=await admin('trash/preview',{kind:'exam',id:exam.id});assert.equal(preview.counts.examAttempt,1);const job=await admin('trash',{kind:'exam',id:exam.id,signature:preview.signature});await student(`exam-attempts/${a.id}`,undefined,'POST',404);const replacement=await admin('exams',config,'POST',201);await admin('trash/restore',{jobId:job.jobId},'POST',409);const replacementPreview=await admin('trash/preview',{kind:'exam',id:replacement.id});await admin('trash',{kind:'exam',id:replacement.id,signature:replacementPreview.signature});await admin('trash/restore',{jobId:job.jobId});assert.equal((await admin(`exam-attempts/${a.id}`)).attempt.score,18);const ep=await admin('trash/preview',{kind:'enrollment',id:en.id});assert.equal(ep.counts.examAttempt,2);const ej=await admin('trash',{kind:'enrollment',id:en.id,signature:ep.signature});await admin(`exam-attempts/${a.id}`,undefined,'POST',404);await admin('trash/restore',{jobId:ej.jobId});
console.log('PASS Exam and enrollment trash preserves answers and scores; conflicting restore rolls back safely');
const backup=await admin('backup');assert(backup.exams.some(e=>e.id===exam.id));assert(backup.examAttempts.some(x=>x.id===a.id));assert(backup.exams.every(e=>!('unlock_hash' in e)));assert(backup.examAttempts.every(a=>!('page_token' in a)));const manifest={...backup,assets:[]};manifest.files=[];manifest.profiles=[];const restored=await admin('restore/start',{manifest},'POST',201);await admin('restore/commit',{jobId:restored.id},'POST',201);const restoredCourse=(await admin('state')).courses.find(c=>c.name==='รายวิชาทดสอบการสอบ'&&c.code.includes('~R'));const restoredExams=(await admin(`exams/course/${restoredCourse.id}`)).exams;assert.equal(restoredExams.length,2);assert(restoredExams.every(e=>e.status==='draft'));assert(restoredExams.some(e=>e.attempts.some(a=>a.score===18)));assert(restoredExams.some(e=>e.attempts.some(a=>a.score===17)));
console.log('PASS Backups retain exams, answers and event history; restore creates draft exams with new credentials');
// Attempts left active for harness-controlled deadline and connection tests.
const nextCourse=(await admin('courses',{periodId:period.id,code:'TIME'+suffix,name:'ห้องจำลองเวลา',classrooms:['6/1'],workWeight:60,midWeight:20,finalWeight:20},'POST',201)).id;await admin('students',{courseId:nextCourse,code,name:'นักเรียนเวลา',number:1},'POST',201);const x1=await admin('exams',{...config,courseId:nextCourse},'POST',201),x2=await admin('exams',{...config,courseId:nextCourse,kind:'final'},'POST',201);for(const x of [x1,x2])await admin(`exams/${x.id}`,{status:'open'},'PATCH');const d=await student(`exams/${x1.id}/start`,{},'POST',201),f=await student(`exams/${x2.id}/start`,{},'POST',201);await student(`exam-attempts/${f.attempt.id}/save`,{token:f.attempt.page_token,generation:0,answers:saved});await writeFile('../Grade-direct-verification/exam-time.json',JSON.stringify({code,disconnect:d.attempt.id,deadline:f.attempt.id}));
await admin(`exams/${x1.id}`,{status:'closed'},'PATCH');await student(`exam-attempts/${d.attempt.id}/unlock`,{code:config.unlockCode},'POST',409);await admin(`exams/${x1.id}`,{status:'open'},'PATCH');for(let i=0;i<5;i++)await student(`exam-attempts/${d.attempt.id}/unlock`,{code:'incorrect'},'POST',403);await student(`exam-attempts/${d.attempt.id}/unlock`,{code:config.unlockCode},'POST',429);
console.log('PASS Closed exams reject continuation and incorrect unlock codes are rate limited');
