import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {writeFile,mkdir} from 'node:fs/promises';
import * as XLSX from 'xlsx';
import JSZip from 'jszip';
await build({entryPoints:['lib/exam-import.ts'],outfile:'node_modules/.cache/grade-exam-import.mjs',bundle:true,platform:'node',format:'esm',packages:'external'});
const {parseExamTable,parseExamText,questionIssues,answerIndex,readExamFile}=await import('../node_modules/.cache/grade-exam-import.mjs');
const rows=[['ประเภท','คำถาม','คะแนน','ตัวเลือก A','ตัวเลือก B','เฉลย'],['เลือกตอบ','2 + 2 = ?',10,'3','4','B'],['ข้อเขียน','Explain your method.',10,'','','']];
const table=parseExamTable(rows);assert.equal(table.questions.length,2);assert.equal(table.questions[0].correct,1);assert.equal(table.questions[1].type,'written');assert.equal(table.warnings.length,0);
assert.equal(parseExamTable([['Question','Points','Choice A','Choice B','Answer'],['Which?','2','One','Two','2']]).questions[0].correct,1);
assert.equal(parseExamTable([['คำถาม','คะแนน','ก','ข','เฉลย'],['ถูกข้อใด','2','ใช่','ไม่','ข']]).questions[0].correct,1);
const text='Exam\n1. 2 + 2 = ?\nA. 3\nB. 4\nAnswer: B\nPoints: 10\n2. Explain your method.\nType: written\nPoints: 10';
assert.deepEqual(parseExamText(text).questions,table.questions);
const keys=parseExamText('1. Test\nก. One\nข. Two\nคะแนน: 2\nเฉลย\n1. ข');assert.equal(keys.questions[0].correct,1);
const offset=parseExamText('10. Test\nA. One\nB. Two\nPoints: 2\nAnswer key\n10. B');assert.equal(offset.questions[0].correct,1);assert.ok(offset.warnings.some(w=>w.includes('ลำดับข้อ')));
const missing=parseExamText('1. Test\nA. One\nB. Two').questions[0];assert.equal(missing.correct,null);assert.equal(missing.points,0);assert.equal(questionIssues(missing).length,2);
const gaps=parseExamTable([['Question','Points','A','B','C','Answer'],['Test','2','One','','Three','C']]);assert.ok(questionIssues(gaps.questions[0]).some(x=>x.includes('ตัวเลือกว่าง')));
assert.equal(answerIndex('ตัวเลือก B',['One','Two']),1);assert.equal(answerIndex('Two',['One','Two']),1);assert.equal(answerIndex('E',['One','Two']),null);
assert.throws(()=>parseExamText('No numbered questions'));assert.throws(()=>parseExamTable([['Name'],['Nobody']]));assert.throws(()=>parseExamText(Array.from({length:101},(_,i)=>`${i+1}. Test\nPoints: 1`).join('\n')),/100/);
await assert.rejects(()=>readExamFile(new File(['x'],'legacy.doc')),/docx/);await assert.rejects(()=>readExamFile(new File([new Uint8Array(15*1024*1024+1)],'large.pdf')),/15 MB/);
const out='../Grade-direct-verification/import-fixtures';await mkdir(out,{recursive:true});
const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Notes'],['Use next sheet']]),'Notes');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Questions');
const xlsx=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});await writeFile(out+'/exam.xlsx',xlsx);
const excelSources=await readExamFile(new File([xlsx],'exam.xlsx'));assert.equal(excelSources.length,2);assert.equal(parseExamTable(excelSources[1].rows).questions[0].correct,1);
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');const paragraphs=text.split('\n').map(l=>`<w:p><w:r><w:t xml:space="preserve">${escape(l)}</w:t></w:r></w:p>`).join('');
const zip=new JSZip();zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.file('word/document.xml',`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}</w:body></w:document>`);await writeFile(out+'/exam.docx',await zip.generateAsync({type:'nodebuffer'}));
const content='BT /F1 12 Tf 50 790 Td '+text.split('\n').map((l,i)=>(i?'0 -24 Td ':'')+'('+l.replace(/[\\()]/g,'\\$&')+') Tj').join('\n')+' ET';
const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;await writeFile(out+'/exam.pdf',pdf);
await writeFile(out+'/blank.pdf',pdf.replace(content,' '.repeat(Buffer.byteLength(content))));
const automatic=text.split('\n').map(l=>{const match=l.match(/^([12])\. (.+)$/);return `<w:p>${match?'<w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr>':''}<w:r><w:t>${escape(match?match[2]:l)}</w:t></w:r></w:p>`;}).join('');
zip.file('word/document.xml',`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${automatic}</w:body></w:document>`);
zip.file('word/numbering.xml','<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>');
zip.file('word/_rels/document.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdNumbering" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/></Relationships>');
await writeFile(out+'/automatic-numbering.docx',await zip.generateAsync({type:'nodebuffer'}));
console.log('PASS exam import: Thai/English tables, real Excel sheets, text questions, answer keys, missing data, gaps, limits, legacy files; DOCX/PDF fixtures ready for browser QA');
