import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
const base=process.env.GRADE_TEST_URL||'http://127.0.0.1:5173';
const results=[];const outputDir=process.env.GRADE_TEST_OUTPUT||'.sites-runtime';
function client(){let cookie='';return async(path,body,method='POST',expected=200,extra={})=>{const r=await fetch(`${base}/api/${path}`,{method:body===undefined?'GET':method,headers:{...(body instanceof FormData?{}:body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{}),...extra},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const next=r.headers.get('set-cookie');if(next)cookie=next.split(';')[0];const raw=await r.text();let data;try{data=JSON.parse(raw);}catch{data=raw.slice(0,2000);}assert.equal(r.status,expected,`${path}: ${JSON.stringify(data)}`);return data;};}
const t=client(),a=client(),b=client();const initial=await t('auth');assert.equal(initial.setup,true,'Tests require an empty, disposable local database. Do not run against real school records.');
const teacherPassword=`Test-${randomUUID()}`,studentPassword=`Student-${randomUUID()}`;
const check=(name)=>{results.push(name);console.log(`PASS ${name}`);};
await t('setup',{name:'ครูทดสอบ ระบบ',username:'teacher-e2e',password:teacherPassword},'POST',201);await mkdir(outputDir,{recursive:true});await writeFile(outputDir+'/test-login-'+new URL(base).port+'.json',JSON.stringify({username:'teacher-e2e',password:teacherPassword}));await t('setup',{name:'ครูซ้ำ',username:'duplicate',password:teacherPassword},'POST',409);check('One-time atomic teacher setup');
const p1=await t('periods',{year:2569,term:1},'POST',201),p2=await t('periods',{year:2569,term:2},'POST',201),p3=await t('periods',{year:2570,term:1},'POST',201);await t('periods',{year:2569,term:1},'POST',409);
const courseData={code:'ว21101',name:'วิทยาศาสตร์',classroom:'ม.1/1',workWeight:60,midWeight:20,finalWeight:20};const c1=await t('courses',{...courseData,periodId:p1.id},'POST',201),c2=await t('courses',{...courseData,periodId:p2.id},'POST',201),c3=await t('courses',{...courseData,periodId:p3.id},'POST',201);check('Independent years, terms and courses');
await t('courses',{...courseData,periodId:p1.id,workWeight:70},'POST',400);
const imported=await t('import',{courseId:c1.id,rows:[{code:'00001',name:'นักเรียน ทดสอบหนึ่ง',number:1},{code:'00002',name:'นักเรียน ทดสอบสอง',number:2}]},'POST',201);assert.equal(imported.credentials.length,2);await t('import',{courseId:c2.id,rows:[{code:'00001',name:'นักเรียน ชื่อในเทอมสอง',number:5}]},'POST',201);const before=(await t('state')).enrollments.length;await t('import',{courseId:c2.id,rows:[{code:'00003',name:'ห้ามบันทึกบางส่วน',number:6},{code:'00001',name:'ข้อมูลซ้ำ',number:5}]},'POST',409);assert.equal((await t('state')).enrollments.length,before);check('Import preview contract, shared accounts, no partial duplicate import');
await a('login',{username:'00001',password:imported.credentials[0].password});await a('state',undefined,'GET',403);await a('password',{oldPassword:imported.credentials[0].password,password:studentPassword});await b('login',{username:'00002',password:imported.credentials[1].password});await b('password',{oldPassword:imported.credentials[1].password,password:studentPassword});check('Temporary password enforcement and session rotation');
const task=await t('assignments',{courseId:c1.id,title:'การทดลองแรงและการเคลื่อนที่',description:'ถ่ายรูปผลการทดลองและอธิบายสิ่งที่พบ',maxScore:10,dueAt:'2026-12-01T09:00:00+07:00'},'POST',201);await a('assignments',{courseId:c1.id,title:'ห้ามสร้าง',maxScore:10,dueAt:'2026-12-01'},'POST',403);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
function form(id,bytes=png,name='งานทดลอง.png'){const f=new FormData();f.set('assignmentId',id);f.set('note','ทดสอบส่งงาน');f.append('files',new Blob([bytes],{type:'image/png'}),name);return f;}
await t('samples',form(task.id),'POST',201);await a('submit',form(task.id,Buffer.from('<html>bad</html>'),'fake.png'),'POST',400);await a('submit',form(task.id),'POST',201);await a('submit',form(task.id),'POST',409);check('Image storage, example attachment and content validation');
let s=await t('state');const studentA=s.students.find(x=>x.username==='00001'),studentB=s.students.find(x=>x.username==='00002');let sub=s.submissions.find(x=>x.student_id===studentA.id);const firstFile=s.files.find(x=>x.student_id===studentA.id);const anonymous=client();await anonymous(`file/${firstFile.id}`,undefined,'GET',401);await b(`file/${firstFile.id}`,undefined,'GET',403);const studentState=await b('state');assert.equal(studentState.submissions.length,0);assert.equal(studentState.files.filter(x=>x.student_id===studentA.id).length,0);assert.equal((await a('state')).courses.some(x=>x.id===c3.id),false);check('Student privacy, file authorization and course isolation');
await t(`review/${sub.id}`,{score:11,feedback:'',revision:1},'PATCH',400);await t(`review/${sub.id}`,{score:null,feedback:'',revision:1},'PATCH',400);await a(`review/${sub.id}`,{score:10,revision:1},'PATCH',403);await t(`review/${sub.id}`,{score:8,revision:1},'PATCH',403,{Origin:'https://wrong.example'});await t(`review/${sub.id}`,{returned:true,feedback:'เพิ่มคำอธิบาย',revision:1},'PATCH');await a('submit',form(task.id),'POST',201);await t(`review/${sub.id}`,{score:9,revision:1},'PATCH',409);s=await t('state');sub=s.submissions.find(x=>x.id===sub.id);assert.equal(sub.revision,2);assert.equal(s.files.filter(f=>f.student_id===studentA.id).length,2);await t(`review/${sub.id}`,{score:8,feedback:'ทำได้ดี',revision:2},'PATCH');check('Returned work, retained revisions, stale grading rejection and score bounds');
await t(`courses/${c1.id}`,{published:true},'PATCH',409);s=await t('state');const e1=s.enrollments.find(e=>e.student_id===studentA.id&&e.course_id===c1.id),e2=s.enrollments.find(e=>e.student_id===studentB.id&&e.course_id===c1.id);await t(`enrollments/${e1.id}`,{mid:17,final:18,special:''},'PATCH');await t(`enrollments/${e2.id}`,{mid:10,final:10,special:''},'PATCH');assert.equal((await a('state')).enrollments.find(e=>e.id===e1.id).mid,null);await t(`courses/${c1.id}`,{published:true},'PATCH');assert.equal((await a('state')).enrollments.find(e=>e.id===e1.id).mid,17);await a('submit',form(task.id),'POST',409);await t(`enrollments/${e1.id}`,{mid:18,final:18,special:''},'PATCH');assert.equal((await t('state')).courses.find(c=>c.id===c1.id).published,0);check('Publish gating, hidden provisional exams, retraction after score edits');
const oldName=(await t('state')).enrollments.find(e=>e.id===e1.id).name;const eNew=(await t('state')).enrollments.find(e=>e.course_id===c2.id);await t(`enrollments/${eNew.id}`,{name:'ชื่อใหม่ เฉพาะเทอมสอง',number:7,active:true},'PATCH');assert.equal((await t('state')).enrollments.find(e=>e.id===e1.id).name,oldName);await t(`courses/${c1.id}`,{archived:true},'PATCH');await t(`review/${sub.id}`,{score:9,revision:2},'PATCH',409);await t(`courses/${c1.id}`,{archived:false},'PATCH');check('Historical roster snapshots and reversible course archive');
const backup=await t('backup');assert.equal(backup.user.password,undefined);assert(backup.audit.length>0);assert(!JSON.stringify(backup).includes('password":"'));check('Backup without password hashes, audit history');
await mkdir(outputDir,{recursive:true});await writeFile(outputDir+'/test-login.json',JSON.stringify({username:'teacher-e2e',password:teacherPassword,studentUsername:'00001',studentPassword}));await writeFile(outputDir+'/test-report.json',JSON.stringify({passed:results.length,checks:results},null,2));console.log(`${results.length} integration groups passed.`);




