// Disposable database and bucket only. Production data is never touched.
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
const modules=(await readdir('dist/server',{recursive:true})).filter(p=>(p.endsWith('.js')||p.endsWith('.mjs'))&&p!=='index.js');
const mf=new Miniflare({name:'reliability-qa',modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...modules.map(p=>({type:'ESModule',path:resolve('dist/server',p)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'reliability-qa'},r2Buckets:{BUCKET:'reliability-qa'},assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:false,has_user_worker:true}},port:8788,host:'127.0.0.1'});
function client(){let cookie='';return {async call(path,body,method='POST',status=200){const r=await fetch('http://127.0.0.1:8788/api/'+path,{method:body===undefined?'GET':method,headers:{Connection:'close',...(cookie?{Cookie:cookie}:{}),...(body===undefined||body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert([status].flat().includes(r.status),path+': '+r.status+' '+JSON.stringify(data));return {...data,httpStatus:r.status};}};}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9WQAAAAASUVORK5CYII=','base64');
function form(assignmentId,requestId,note='งานจำลอง'){const f=new FormData();f.set('assignmentId',assignmentId);f.set('requestId',requestId);f.set('note',note);f.append('files',new Blob([png],{type:'image/png'}),'งานทดสอบ.png');return f;}
try{
 await mf.ready;const db=await mf.getD1Database('DB'),bucket=await mf.getR2Bucket('BUCKET');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 const teacher=client(),student=client(),other=client();await teacher.call('setup',{name:'ครูห้องตรวจความพร้อม',username:'ready_teacher',password:'Ready-Teacher-1234'},'POST',201);
 const p=await teacher.call('periods',{year:2569,term:2},'POST',201),c=await teacher.call('courses',{periodId:p.id,code:'พร้อม101',name:'ห้องตรวจความพร้อม',classrooms:['6/1'],workWeight:60,beforeWorkWeight:30,midWeight:20,finalWeight:20},'POST',201);
 for(const [i,s] of [student,other].entries()){const code='READY00'+(i+1);await teacher.call('students',{courseId:c.id,code,name:'นักเรียนจำลอง '+(i+1),number:i+1},'POST',201);await s.call('login',{username:code,password:code});}
 const assignment=async(title,isGroup=false)=>teacher.call('assignments',{courseId:c.id,title,description:'ข้อมูลจำลองสำหรับทดสอบเท่านั้น',maxScore:1,workPhase:'before',dueAt:'2027-12-01T00:00:00Z',rubric:[],isGroup,groupMax:3,individualWeight:0},'POST',201);
 const a=await assignment('ส่งซ้ำหลังผลตอบกลับหาย'),key=randomUUID();await student.call('submit',form(a.id,key),'POST',201);
 const replay=await student.call('submit',form(a.id,key,'ข้อความใหม่ไม่ควรทับงานเดิม'),'POST',201);assert.equal(replay.recovered,true);assert.equal(replay.revision,1);
 assert.equal((await student.call(`submission-status?assignmentId=${a.id}&requestId=${key}`)).receipt.revision,1);assert.equal((await other.call(`submission-status?assignmentId=${a.id}&requestId=${key}`)).receipt,null);
 let state=await teacher.call('state');assert.equal(state.submissions.length,1);assert.equal(state.files.length,1);assert.equal(state.submissions[0].note,'งานจำลอง');assert.equal((await bucket.list()).objects.length,1);
 await student.call('submit',form(a.id,randomUUID()),'POST',409);
 const b=await assignment('แข่งส่งครั้งแรก'),raceKey=randomUUID(),race=await Promise.all([student.call('submit',form(b.id,raceKey),'POST',201),student.call('submit',form(b.id,raceKey),'POST',[201,409])]);
 // A duplicate can observe the pending submission before the winning receipt commits.
 assert(race.some(x=>x.httpStatus===201));assert.equal((await student.call('submit',form(b.id,raceKey),'POST',201)).recovered,true);
 state=await teacher.call('state');assert.equal(state.submissions.filter(s=>s.assignment_id===b.id).length,1);assert.equal(state.files.filter(f=>f.assignment_id===b.id).length,1);assert.equal((await bucket.list()).objects.length,2);
 console.log('PASS lost responses and concurrent first uploads produce one submission, one receipt and one R2 object; receipt privacy and duplicate checks hold');
 const sub=state.submissions.find(s=>s.assignment_id===b.id);await teacher.call('review/'+sub.id,{score:null,revision:sub.revision,returned:true,feedback:'แก้ไข',expectedReviewedAt:null,expectedRubric:'[]'},'PATCH');state=await teacher.call('state');const before=state.courses.find(x=>x.id===c.id).revision;
 const correction=await Promise.all([student.call('submit',form(b.id,randomUUID()),'POST',[201,409]),student.call('submit',form(b.id,randomUUID()),'POST',[201,409])]);assert.deepEqual(correction.map(x=>x.httpStatus).sort(),[201,409]);state=await teacher.call('state');assert.equal(state.submissions.find(s=>s.id===sub.id).revision,2);assert.equal(state.files.filter(f=>f.assignment_id===b.id&&f.revision===2).length,1);assert.equal(state.courses.find(x=>x.id===c.id).revision,before+1);assert.equal((await bucket.list()).objects.length,state.files.length);
 await student.call('submit',form(b.id,key),'POST',409);
 console.log('PASS concurrent corrections advance one revision and invalidate course once, with no orphan file metadata or R2 objects');
 const g=await assignment('งานกลุ่มส่งครั้งเดียว',true),group=await student.call('groups/'+g.id+'/create',{name:'ทีมความพร้อม'},'POST',201);await other.call('groups/'+g.id+'/join',{groupId:group.id});const groupKey=randomUUID();await student.call('submit',form(g.id,groupKey),'POST',201);assert.equal((await student.call('submit',form(g.id,groupKey),'POST',201)).recovered,true);state=await teacher.call('state');assert.equal(state.submissions.filter(s=>s.assignment_id===g.id).length,2);assert.equal(state.files.filter(f=>f.assignment_id===g.id).length,2);
 console.log('PASS replaying a group upload preserves one group revision and one set of files per member');
 const tasks=[];for(let i=0;i<30;i++)tasks.push(await assignment('ทดสอบพร้อมกัน '+(i+1)));const load=await Promise.all(tasks.map((a,i)=>(i%2?other:student).call('submit',form(a.id,randomUUID()),'POST',201)));assert.equal(load.length,30);state=await teacher.call('state');assert.equal(state.submissions.filter(s=>tasks.some(a=>a.id===s.assignment_id)).length,30);assert.equal((await bucket.list()).objects.length,state.files.length);
 console.log('PASS 30 concurrent submissions preserve all student records and file bytes on the isolated Worker (not a production capacity guarantee)');
 const exam=await teacher.call('exams',{courseId:c.id,title:'สอบทดสอบการเชื่อมต่อ',kind:'mid',duration:60,maxScore:20,questions:[{type:'written',prompt:'อธิบายสิ่งที่เรียน',points:20}],unlockCode:'Ready-Unlock-1234'},'POST',201);await teacher.call('exams/'+exam.id,{status:'open'},'PATCH');const page=await student.call('exams/'+exam.id+'/start',{},'POST',201);await db.prepare('UPDATE exam_attempts SET heartbeat=? WHERE id=?').bind(Date.now()-31000,page.attempt.id).run();const locked=await student.call('exam-attempts/'+page.attempt.id);assert.equal(locked.attempt.status,'locked');await student.call('exam-attempts/'+page.attempt.id+'/save',{token:page.attempt.page_token,generation:0,answers:{q0:'ค้างส่ง'}},'POST',423);await student.call('exam-attempts/'+page.attempt.id+'/unlock',{code:'wrong'},'POST',403);const unlocked=await student.call('exam-attempts/'+page.attempt.id+'/unlock',{code:'Ready-Unlock-1234'});await student.call('exam-attempts/'+page.attempt.id+'/save',{token:unlocked.attempt.page_token,generation:unlocked.attempt.generation,answers:{q0:'คำตอบจากฉบับร่าง'}});assert.equal(JSON.parse((await student.call('exam-attempts/'+page.attempt.id)).attempt.answers).q0,'คำตอบจากฉบับร่าง');
 console.log('PASS disconnection locks the attempt, rejects saves, requires the correct teacher PIN, and accepts the preserved draft only after unlock');
 await assignment('งานสำหรับทดลองฉบับร่าง');
 if(process.env.GRADE_READY_PREVIEW==='1'){console.log('Preview http://127.0.0.1:8788/ student READY001 / READY001');await new Promise(()=>{});}
}finally{await mf.dispose();}
