import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
await build({stdin:{contents:"export {CourseView} from './components/grade/course-views';export {Results} from './components/grade/results';export {calculateGrade} from './lib/grades';",resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},outfile:'.sites-runtime/score-display-test.mjs'});
const {CourseView,Results,calculateGrade}=await import('../.sites-runtime/score-display-test.mjs');
const course={id:'c',code:'SCI01',name:'วิทยาศาสตร์ทดสอบ',classroom:'ม.1/1',work_weight:60,mid_weight:20,final_weight:20,published:0,can_edit:true};
const e={id:'e',course_id:'c',student_id:'s',student_code:'00123',name:'นักเรียนทดสอบ',number:1,active:1,mid:null,final:null,special:''};
const task={id:'a',course_id:'c',title:'งานทดสอบ',max_score:10,due_at:'2026-12-01T00:00:00Z',rubric:'[]'};
const submission={id:'sub',assignment_id:'a',student_id:'s',status:'graded',score:8,revision:1,submitted_at:'2026-10-08T00:00:00Z'};
const state={user:{id:'s',role:'student'},assignments:[task],submissions:[submission],enrollments:[e],files:[],extensions:[]};
let g=calculateGrade(course,state.assignments,state.submissions,e);assert.equal(g.raw,8);assert.equal(g.work,8);assert.equal(g.total,8);assert.equal(g.complete,false);assert.equal(g.grade,null);
const html=renderToStaticMarkup(createElement(CourseView,{state,course,edit:()=>{},initialFilter:'missing'}));assert(html.includes('คะแนนรวมปัจจุบัน'));assert(html.includes('ก่อนกลางภาค'));assert(html.includes('คะแนนเก็บสะสม'));assert(html.includes('<strong>8<small> / 100'));assert(html.includes('<strong>8<small> / 10'));assert(html.includes('ไม่มีงานในสถานะนี้'));
console.log('PASS Student assignment totals show current points and raw/accumulated scores independently of task filters');
const studentResults=renderToStaticMarkup(createElement(Results,{state,course:{...course,can_edit:false},refresh:async()=>{}}));assert(studentResults.includes('<strong>8<small> / 100'));assert(studentResults.includes('รอเผยแพร่'));assert(!studentResults.includes('ครูยังไม่เผยแพร่ผลการเรียน'));
const teacherResults=renderToStaticMarkup(createElement(Results,{state:{...state,user:{id:'teacher',role:'admin'}},course,refresh:async()=>{}}));assert(teacherResults.includes('รวมปัจจุบัน / 100'));assert(teacherResults.includes('<strong>8</strong>'));assert(teacherResults.includes('คะแนนที่มีแล้ว'));assert(teacherResults.includes('รอข้อมูล'));
console.log('PASS Student and teacher results show available totals before exams are complete while official grades wait');
const publishedState={...state,enrollments:[{...e,mid:17,final:18}]};const published=renderToStaticMarkup(createElement(Results,{state:publishedState,course:{...course,published:1,can_edit:false},refresh:async()=>{}}));assert(published.includes('<strong>43<small> / 100'));assert(published.includes('grade-value">0<'));assert(!published.includes('รอเผยแพร่'));
g=calculateGrade(course,[task,{...task,id:'other-task',course_id:'other',max_score:999}], [{...submission,status:'returned',score:8},{...submission,id:'someone-else',student_id:'another',score:10}],e);assert.equal(g.raw,0);assert.equal(g.total,0);assert.equal(g.max,10);assert.equal(g.grade,null);
g=calculateGrade(course,[],[],e);assert.equal(g.total,0);assert.equal(g.raw,0);assert.equal(Number.isFinite(g.work),true);
console.log('PASS Published totals and grade thresholds stay intact; pending/returned work, other users/courses and empty courses are handled');
const ten={...submission,score:10};const tenGrade=calculateGrade(course,[task],[ten],e);assert.equal(tenGrade.total,10);assert.equal(tenGrade.work,10);assert.equal(tenGrade.phases.before.earned,10);
const expanded=calculateGrade(course,[task,{...task,id:'after',work_phase:'after',max_score:20}],[ten,{...ten,assignment_id:'after',score:15}],e);assert.equal(expanded.total,25);assert.equal(expanded.phases.after.earned,15);assert.equal(expanded.phases.before.earned,10);assert.equal(expanded.budgetValid,true);
assert.equal(calculateGrade(course,[task,{...task,id:'new',max_score:10}],[ten],e).work,10);
const legacy=calculateGrade({...course,archived:1,grading_mode:'weighted'},[task],[ten],{...e,mid:20,final:20});assert.equal(legacy.work,60);assert.equal(legacy.total,100);
const archivedPoints=calculateGrade({...course,archived:1,grading_mode:'points'},[task],[ten],{...e,mid:20,final:20});assert.equal(archivedPoints.work,10);assert.equal(archivedPoints.total,50);
const overflow=calculateGrade(course,[{...task,max_score:31}],[ten],{...e,mid:20,final:20});assert.equal(overflow.grade,null);assert.equal(overflow.budgetValid,false);
console.log('PASS Earned points accumulate without inflation or dilution; phases and overflow gating work; old archived grades stay unchanged');
