import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const base=process.env.GRADE_TEST_URL;if(!/^http:\/\/127\.0\.0\.1:/.test(base||''))throw Error('Use the isolated built-worker harness');
const cred=JSON.parse(await readFile('../Grade-direct-verification/test-login.json','utf8'));
function client(){let cookie='';return async(path,body,method='POST',status=200)=>{const r=await fetch(`${base}/api/${path}`,{method:body===undefined?'GET':method,headers:{Connection:'close',...(cookie?{Cookie:cookie}:{}),...(body!==undefined&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const json=r.headers.get('content-type')?.includes('application/json'),data=json?await r.json():new Uint8Array(await r.arrayBuffer());assert.equal(r.status,status,path+': '+(json?JSON.stringify(data):'file'));return data;};}
const admin=client(),student=client(),limited=client();await admin('login',{username:cred.username,password:cred.password});await student('login',{username:cred.studentUsername,password:cred.studentPassword});
const period=await admin('periods',{year:2572,term:1},'POST',201),data={periodId:period.id,code:'MULTI01',name:'วิทยาศาสตร์หลายห้อง',classrooms:['ม.1/1','ม.1/2'],workWeight:60,midWeight:20,finalWeight:20},created=await admin('courses',data,'POST',201);let state=await admin('state');const sections=created.ids.map(id=>state.courses.find(c=>c.id===id));assert.equal(new Set(sections.map(c=>c.subject_id)).size,1);assert.equal(state.subjects.filter(s=>s.id===created.subjectId).length,1);
const count=state.courses.length;await admin('subject-rooms',{subjectId:created.subjectId,classrooms:['ม.1/2','ม.1/3']},'POST',409);assert.equal((await admin('state')).courses.length,count);const added=await admin('subject-rooms',{subjectId:created.subjectId,classrooms:['ม.1/3']},'POST',201);assert.equal(added.subjectId,created.subjectId);await admin(`subjects/${created.subjectId}`,{code:'MULTI01',name:'วิทยาศาสตร์ร่วมกัน'},'PATCH');state=await admin('state');assert.equal(state.courses.filter(c=>c.subject_id===created.subjectId&&c.name==='วิทยาศาสตร์ร่วมกัน').length,3);console.log('PASS One subject has multiple rooms; room creation is atomic and shared names stay consistent');
await admin('students',{courseId:sections[0].id,code:cred.studentUsername,name:'นักเรียนห้องหนึ่ง',number:1},'POST',201);const two=await admin('students',{courseId:sections[1].id,code:'room-two-'+randomUUID().slice(0,8),name:'นักเรียนห้องสอง',number:1},'POST',201);const rubric=[{id:'accuracy',label:'ความถูกต้อง',max:10}],taskBody={courseIds:created.ids,title:'งานร่วมสองห้อง',description:'โจทย์เดียวกัน',maxScore:10,dueAt:'2027-01-01T10:00:00+07:00',rubric},assigned=await admin('assignments',taskBody,'POST',201);assert.equal(assigned.assignmentIds.length,2);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64'),f=new FormData();f.set('assignmentIds',JSON.stringify(assigned.assignmentIds));f.append('files',new Blob([png],{type:'image/png'}),'โจทย์.png');await admin('samples',f,'POST',201);state=await admin('state');assert.equal(state.files.filter(x=>assigned.assignmentIds.includes(x.assignment_id)).length,2);const me=(await student('state')).user.id;await admin('paper-grade',{assignmentId:assigned.assignmentIds[0],studentId:me,score:7,rubricScores:[7]},'POST',201);state=await admin('state');assert.equal(state.submissions.filter(s=>s.assignment_id===assigned.assignmentIds[1]).length,0);const ss=await student('state');assert(ss.assignments.some(a=>a.id===assigned.assignmentIds[0]));assert(!ss.assignments.some(a=>a.id===assigned.assignmentIds[1]));assert.equal(ss.subjects.filter(s=>s.id===created.subjectId).length,1);await student(`file/${state.files.find(x=>x.assignment_id===assigned.assignmentIds[1]).id}`,undefined,'GET',403);console.log('PASS Multi-room assignment/sample distribution keeps scores and student files private per room');
const person=await admin('staff',{username:'room-staff-'+randomUUID().slice(0,8),name:'ครูหนึ่งห้อง',role:'teacher'},'POST',201);await limited('login',{username:person.credentials[0].code,password:person.credentials[0].password});await limited('password',{oldPassword:person.credentials[0].password,password:'Secure-'+randomUUID()});await admin('course-access',{courseId:sections[0].id,userId:person.id,permission:'edit'});const before=state.assignments.length;await limited('assignments',taskBody,'POST',403);assert.equal((await admin('state')).assignments.length,before);await limited('subject-rooms',{subjectId:created.subjectId,classrooms:['ม.1/4']},'POST',403);assert.equal((await limited('state')).courses.length,1);assert.equal((await limited('state')).subjects.length,1);console.log('PASS Teacher room permissions prevent partial multi-room writes and sibling-room data leakage');
const other=state.courses.find(c=>c.subject_id!==created.subjectId);await admin('assignments',{...taskBody,courseIds:[sections[0].id,other.id]},'POST',400);const p2=await admin('periods',{year:2572,term:2},'POST',201),next=await admin('courses',{...data,periodId:p2.id},'POST',201);assert.notEqual(next.subjectId,created.subjectId);
const backup=await admin('backup');backup.courses=backup.courses.filter(c=>c.subject_id===created.subjectId);backup.subjects=backup.subjects.filter(s=>s.id===created.subjectId);backup.assignments=[];backup.enrollments=[];backup.submissions=[];backup.files=[];backup.students=[];backup.extensions=[];backup.profiles=[];backup.assets=[];backup.audit=[];const job=await admin('restore/start',{manifest:backup},'POST',201),restored=await admin('restore/commit',{jobId:job.id},'POST',201);assert.equal(restored.courses,3);state=await admin('state');const restoredRooms=state.courses.filter(c=>c.name==='วิทยาศาสตร์ร่วมกัน'&&c.code.includes('~R'));assert.equal(restoredRooms.length,3);assert.equal(new Set(restoredRooms.map(c=>c.subject_id)).size,1);assert.equal(new Set(restoredRooms.map(c=>c.code)).size,1);assert(restoredRooms.every(c=>!c.published));console.log('PASS Subject grouping survives restore and remains independent across academic terms');
