// End-to-end Worker, D1 and R2 tests on a disposable in-memory classroom only.
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
const modules=(await readdir('dist/server',{recursive:true})).filter(p=>(p.endsWith('.js')||p.endsWith('.mjs'))&&p!=='index.js');
const mf=new Miniflare({name:'teacher-upgrade-qa',modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...modules.map(p=>({type:'ESModule',path:resolve('dist/server',p)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'teacher-upgrade-qa'},r2Buckets:{BUCKET:'teacher-upgrade-qa'},assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:false,has_user_worker:true}},port:8786,host:'127.0.0.1',bindings:{BACKUP_OWNER_EMAIL:'qa-owner@example.test'}});
await mf.ready;const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
function client(){let cookie='';return {async call(path,body,method='POST',status=200){const r=await fetch('http://127.0.0.1:8786/api/'+path,{method:body===undefined?'GET':method,headers:{Connection:'close',...(cookie?{Cookie:cookie}:{}),...(body===undefined||body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const result=r.headers.get('content-type')?.includes('application/json')?await r.json():new Uint8Array(await r.arrayBuffer());if(Array.isArray(status)){assert(status.includes(r.status),path+': '+JSON.stringify(result));result._httpStatus=r.status;}else assert.equal(r.status,status,path+': '+JSON.stringify(result));return result;}};}
const admin=client(),s1=client(),s2=client(),s3=client(),s4=client();let passed=0;const pass=label=>{passed++;console.log('PASS '+label);};

try {
 await admin.call('setup',{name:'ครูทดสอบ',username:'upgrade_teacher',password:'Upgrade-Teacher-1234'},'POST',201);
 const p=await admin.call('periods',{year:2569,term:2},'POST',201);
 const c=await admin.call('courses',{periodId:p.id,code:'ง30101',name:'การออกแบบ',classrooms:['6/1'],workWeight:60,beforeWorkWeight:30,midWeight:20,finalWeight:20},'POST',201);
 for(const [i,s] of [s1,s2,s3].entries()){const code='00'+(i+1);await admin.call('students',{courseId:c.id,code,name:['ต้นกล้า','ใบแก้ว','ร่มไทร'][i],number:i+1},'POST',201);await s.call('login',{username:code,password:code});}
 let state=await admin.call('state'),roster=state.enrollments.filter(e=>e.course_id===c.id);const revision=()=>state.courses.find(x=>x.id===c.id).revision;
 await admin.call('bulk-scores',{courseId:c.id,revision:revision(),reason:'ตรวจนำเข้า',rows:[{enrollmentId:roster[0].id,mid:15},{enrollmentId:roster[1].id,mid:21}]},'POST',400);
 assert((await admin.call('state')).enrollments.every(e=>e.mid===null));
 const b={courseId:c.id,revision:revision(),reason:'นำเข้าสอบ',rows:roster.map(e=>({enrollmentId:e.id,mid:15,final:18}))};
 const race=await Promise.all([admin.call('bulk-scores',b,'POST',[200,409]),admin.call('bulk-scores',b,'POST',[200,409])]);assert.deepEqual(race.map(x=>x._httpStatus).sort(),[200,409]);
 assert((await admin.call('state')).enrollments.every(e=>e.mid===15&&e.final===18));
 let snaps=(await admin.call('snapshots')).snapshots;assert(snaps.some(x=>x.kind==='before_scores'&&x.status==='complete'));const pre=await admin.call('snapshots/'+snaps.find(x=>x.status==='complete').id);assert(pre.enrollments.every(e=>e.mid===null));await s1.call('snapshots',undefined,'GET',403);
 pass('Bulk marks validate the entire class, concurrent saves have one winner, checkpoints preserve old marks, students cannot read backups');
 await admin.call('attendance',{courseId:c.id,date:'2026-99-99',title:'ผิด',hours:1},'POST',400);
 const session=await admin.call('attendance',{courseId:c.id,date:'2026-10-10',title:'คาบออกแบบ',hours:2},'POST',201);
 const marks=roster.map((e,i)=>({studentId:e.student_id,status:i===1?'absent':i===2?'late':'present',hours:i===1?0:i===2?1:2,note:'ครูบันทึก'}));
 await admin.call('attendance/'+session.id,{revision:0,rows:marks},'PATCH');await admin.call('attendance/'+session.id,{revision:0,rows:marks},'PATCH',409);
 const note=await admin.call('followup-notes',{courseId:c.id,studentId:roster[0].student_id,text:'PRIVATE_CASE_NOTE',nextDate:'2026-10-11'},'POST',201);
 await admin.call('followup-notes/'+note.id,{revision:0,status:'done'},'PATCH');await admin.call('followup-notes/'+note.id,{revision:0,text:'stale'},'PATCH',409);
 await s1.call('followup-notes/'+note.id,{revision:1,text:'forbidden'},'PATCH',403);
 const own=await s1.call('state');assert.equal(own.attendanceRecords.length,1);assert.equal(own.attendanceRecords[0].hours,2);assert.equal(own.enrollments[0].attendance.hours,2);assert.deepEqual(own.followupNotes,[]);assert(!JSON.stringify(own).includes('PRIVATE_CASE_NOTE'));
 await s1.call('notification-read',{keys:['mine']});assert.equal((await s2.call('state')).notificationReads.length,0);await s1.call('notification-read',{keys:[]});
 pass('Attendance revisions and hours validated; students see only their own attendance and no private case notes; notification read state is personal');
 const task={courseId:c.id,title:'ออกแบบร่วมกัน',description:'ทดสอบ',isGroup:true,groupMax:3,individualWeight:20,maxScore:30,workPhase:'before',dueAt:'2027-12-01T00:00:00Z',rubric:[]};
 const a=await admin.call('assignments',task,'POST',201);state=await admin.call('state');assert.equal(state.assignments.find(x=>x.id===a.id).individual_weight,20);
 const g=await s1.call('groups/'+a.id+'/create',{name:'ทีมต้นกล้า'},'POST',201);await s2.call('groups/'+a.id+'/join',{groupId:g.id});
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lWQAAAAASUVORK5CYII=','base64');
 const form=()=>{const f=new FormData();f.set('assignmentId',a.id);f.set('note','งานร่วม');f.append('files',new Blob([png],{type:'image/png'}),'งาน.png');return f;};await s1.call('submit',form(),'POST',201);
 state=await admin.call('state');let sub=state.submissions.find(s=>s.student_id===roster[0].student_id);await admin.call('review/'+sub.id,{score:25,revision:sub.revision,expectedReviewedAt:sub.reviewed_at,expectedRubric:'[]',feedback:'คะแนนกลุ่ม'},'PATCH');
 state=await admin.call('state');sub=state.submissions.find(s=>s.id===sub.id);const personal={submissionId:sub.id,score:5,reason:'ส่วนร่วม',revision:sub.revision,expectedScore:null};await admin.call('individual-score',personal);await admin.call('individual-score',personal,'POST',409);
 await admin.call('individual-score',{...personal,score:7,expectedScore:5},'POST',400);
 const plan=await admin.call('publication-check/'+c.id);assert.equal(plan.pending,1);assert(plan.incomplete.some(x=>x.enrollment.student_id===roster[1].student_id));
 const shared=(await admin.call('groups/'+a.id)).groups[0];state=await admin.call('state');const changed={courseRevision:revision(),reason:'เพิ่มสมาชิกเพื่อทำใหม่',resetAffected:false,groups:[{id:g.id,revision:shared.revision,name:'ทีมต้นกล้า',leaderId:roster[0].student_id,memberIds:roster.map(e=>e.student_id)}]};
 await admin.call('manage-groups/'+a.id,changed,'POST',409);await admin.call('manage-groups/'+a.id,{...changed,resetAffected:true});state=await admin.call('state');assert.equal(state.submissions.length,3);assert(state.submissions.every(s=>s.status==='returned'&&s.score===null&&s.individual_score===null));await s3.call('submit',form(),'POST',201);assert((await admin.call('state')).submissions.every(s=>s.status==='pending'));
 pass('Group assignment stores contribution weight; personal marks have stale-value protection; missing contributions block publication; group exceptions checkpoint and return every member for resubmission');
 const questions=[{type:'choice',prompt:'ข้อสี',points:10,options:['แดง','เขียว','ฟ้า'],correct:1},{type:'choice',prompt:'ข้อจำนวน',points:10,options:['หนึ่ง','สอง','สาม'],correct:2}];
 const bank=await admin.call('question-banks',{name:'คลังสี',tags:'สี',questions},'POST',201);await s1.call('question-banks',undefined,'GET',403);await admin.call('question-banks/'+bank.id,{name:'คลังสีแก้ไข',questions,tags:'ทดสอบ',revision:0,deleted:true},'PATCH');await admin.call('question-banks/'+bank.id,{name:'คลังสีคืน',tags:'ทดสอบ',revision:1,deleted:false},'PATCH');
 const exam=await admin.call('exams',{courseId:c.id,title:'กลางภาคสุ่ม',kind:'mid',duration:60,maxScore:20,questions,unlockCode:'Teacher-Only-1234',shuffleQuestions:true,shuffleOptions:true},'POST',201);await admin.call('exams/'+exam.id,{status:'open'},'PATCH');
 let page=await s1.call('exams/'+exam.id+'/start',{},'POST',201);assert(!('question_form' in page.attempt));assert(page.questions.every(q=>!('correct' in q)));const attemptId=page.attempt.id,token=page.attempt.page_token;
 const teacherPage=await admin.call('exam-attempts/'+attemptId),answers=Object.fromEntries(teacherPage.questions.map(q=>[q.id,q.correct]));
 await s1.call('exam-attempts/'+attemptId+'/save',{token,generation:0,answers});await s1.call('exam-attempts/'+attemptId+'/lock',{token,generation:0,reason:'เปลี่ยนแท็บ',answers});
 const locked=await admin.call('exam-attempts/'+attemptId);await s1.call('exam-attempts/'+attemptId+'/teacher-unlock',{generation:locked.attempt.generation,reason:'ปลอม'},'POST',403);
 await admin.call('exam-attempts/'+attemptId+'/teacher-unlock',{generation:locked.attempt.generation,reason:'ครูตรวจอุปกรณ์แล้ว'});page=await s1.call('exam-attempts/'+attemptId);assert.deepEqual(page.questions,teacherPage.questions.map(({correct,...q})=>q));assert.deepEqual(JSON.parse(page.attempt.answers),answers);assert.notEqual(page.attempt.page_token,token);
 await s1.call('exam-attempts/'+attemptId+'/save',{token,generation:0,answers},'POST',409);
 const extra={generation:page.attempt.generation,deadline:page.attempt.deadline,minutes:10,reason:'อุปกรณ์ขัดข้อง'};const extraRace=await Promise.all([admin.call('exam-attempts/'+attemptId+'/extra-time',extra,'POST',[200,409]),admin.call('exam-attempts/'+attemptId+'/extra-time',extra,'POST',[200,409])]);assert.deepEqual(extraRace.map(x=>x._httpStatus).sort(),[200,409]);page=await s1.call('exam-attempts/'+attemptId);assert.equal(page.attempt.deadline,extra.deadline+600000);
 await s1.call('exam-attempts/'+attemptId+'/submit',{token:page.attempt.page_token,generation:page.attempt.generation,answers});const analysis=await admin.call('exam-analysis/'+exam.id);assert(analysis.items.every(x=>x.correct===1&&x.correctPercent===100));await s1.call('exam-analysis/'+exam.id,undefined,'GET',403);await admin.call('exam-attempts/'+attemptId+'/extra-time',{...extra,generation:page.attempt.generation},'POST',409);
 pass('Question bank private CRUD; shuffled questions/options persist with saved answers; remote unlock rotates stale tokens; extra-time races add time once; item analysis follows each randomized form');
 const snap=await admin.call('snapshots',{courseId:c.id},'POST',201),manifest=await admin.call('snapshots/'+snap.id);assert.equal(manifest.attendanceSessions.length,1);assert.equal(manifest.followupNotes.length,1);assert.equal(manifest.questionBanks.length,1);assert(manifest.examAttempts[0].question_form);assert(manifest.assets.length>0);
 const restored=await admin.call('snapshots/'+snap.id+'/restore',{},'POST',201);state=await admin.call('state');const recovered=state.courses.find(c=>c.code.includes('~R'));assert(recovered);assert(state.attendanceSessions.some(s=>s.course_id===recovered.id));assert(state.followupNotes.some(n=>n.course_id===recovered.id&&n.text==='PRIVATE_CASE_NOTE'));assert.equal(state.assignments.find(a=>a.course_id===recovered.id).individual_weight,20);const restoredExam=(await admin.call('exams/course/'+recovered.id)).exams[0];const restoredAnalysis=await admin.call('exam-analysis/'+restoredExam.id);assert(restoredAnalysis.items.every(x=>x.correct===1));assert.equal(state.files.filter(f=>f.course_id===recovered.id).length,manifest.files.length);
 await admin.call('snapshots/daily',{});const before=(await admin.call('snapshots')).snapshots.filter(s=>s.kind==='daily').length;await admin.call('snapshots/daily',{});assert.equal((await admin.call('snapshots')).snapshots.filter(s=>s.kind==='daily').length,before);
 const rpc=async(name,headers={})=>{const r=await fetch('http://127.0.0.1:8786/mcp',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:{}}})});return r.json();};assert.equal((await rpc('daily_classroom_backup')).result.isError,true);assert.equal((await rpc('daily_classroom_backup',{'oai-authenticated-user-id':'scoped','oai-authenticated-user-email':'other@example.test'})).result.isError,true);assert.equal((await rpc('daily_classroom_backup',{'oai-authenticated-user-id':'scoped','oai-authenticated-user-email':'qa-owner@example.test'})).result.isError,false);
 pass('Snapshots include bytes, attendance, notes, private question banks and randomized forms; restore remaps IDs; daily backups are idempotent and unattended writer requires verified Site-owner identity');
 // Deliberately remove a live file: protected edits must stop rather than create an incomplete recovery point.
 const file=(await admin.call('state')).files.find(f=>f.course_id===c.id);await (await mf.getR2Bucket('BUCKET')).delete(file.id);state=await admin.call('state');await admin.call('bulk-scores',{courseId:c.id,revision:revision(),reason:'ไฟล์หาย',rows:[{enrollmentId:roster[0].id,mid:1}]},'POST',409);assert.equal((await admin.call('state')).enrollments.find(e=>e.id===roster[0].id).mid,15);
 pass('Missing source file blocks protected mutations; old marks remain intact');
 await (await mf.getR2Bucket('BUCKET')).put(file.id,png,{httpMetadata:{contentType:'image/png'}});
 const activity=await admin.call('courses',{periodId:p.id,code:'ก30101',name:'แนะแนว',classrooms:['6/1'],courseType:'activity',workWeight:100,beforeWorkWeight:50,midWeight:0,finalWeight:0,passThreshold:60},'POST',201);
 for(const e of roster)await admin.call('students',{courseId:activity.id,code:e.student_code,name:e.name,number:e.number},'POST',201);
 const actTask=await admin.call('assignments',{...task,courseId:activity.id,title:'กิจกรรมช่วงหนึ่ง',maxScore:50,isGroup:false,individualWeight:0},'POST',201);for(const e of roster)await admin.call('paper-grade',{assignmentId:actTask.id,studentId:e.student_id,score:40},'POST',201);
 const actTask2=await admin.call('assignments',{...task,courseId:activity.id,title:'กิจกรรมช่วงสอง',maxScore:50,isGroup:false,individualWeight:0,workPhase:'after'},'POST',201);for(const e of roster)await admin.call('paper-grade',{assignmentId:actTask2.id,studentId:e.student_id,score:40},'POST',201);
 await admin.call('activity-policy',{courseId:activity.id,attendanceMin:75,requiredHours:1.5});let check=await admin.call('publication-check/'+activity.id);assert.equal(check.incomplete.length,3);
 const actSession=await admin.call('attendance',{courseId:activity.id,date:'2026-10-10',title:'แนะแนว',hours:2},'POST',201);await admin.call('attendance/'+actSession.id,{revision:0,rows:marks},'PATCH');check=await admin.call('publication-check/'+activity.id);assert.equal(check.incomplete.length,0);assert.equal(check.students,3);await admin.call('courses/'+activity.id,{published:true},'PATCH');
 state=await admin.call('state');await admin.call('attendance/'+actSession.id,{revision:1,date:'2026-10-11',title:'คาบแก้ไข',hours:1},'PATCH',409);await admin.call('attendance/'+actSession.id,{revision:1,date:'2026-10-11',title:'คาบแก้ไข',hours:2},'PATCH');assert.equal((await admin.call('state')).courses.find(c=>c.id===activity.id).published,0);
 pass('Activity attendance requirements block incomplete records, permit final pass/fail evaluation when complete; session editing protects credited hours and retracts published results');
 console.log(passed+' teacher-upgrade integration groups passed.');
 if(process.env.GRADE_UPGRADE_PREVIEW==='1'){console.log('Preview http://127.0.0.1:8786/ teacher upgrade_teacher / Upgrade-Teacher-1234; student 001 / 001');await new Promise(()=>{});}
} finally {await mf.dispose();}
