// Disposable local classroom for browser QA, never a school database.
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
const modules=(await readdir('dist/server',{recursive:true})).filter(p=>(p.endsWith('.js')||p.endsWith('.mjs'))&&p!=='index.js');const mf=new Miniflare({name:'exam-browser-qa',modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...modules.map(p=>({type:'ESModule',path:resolve('dist/server',p)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'exam-browser-qa'},r2Buckets:{BUCKET:'exam-browser-qa'},assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:false,has_user_worker:true}},port:8784,host:'127.0.0.1'});
await mf.ready;const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
let cookie='';async function call(path,body,method='POST'){const r=await fetch('http://127.0.0.1:8784/api/'+path,{method:body===undefined?'GET':method,headers:{Connection:'close',...(cookie?{Cookie:cookie}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const result=await r.json();if(!r.ok)throw Error(path+': '+result.error);return result;}
await call('setup',{name:'ครูทดสอบระบบสอบ',username:'exam_teacher',password:'Exam-Preview-Teacher-1234'});const p=await call('periods',{year:2569,term:2});const c=await call('courses',{periodId:p.id,code:'ว30101',name:'วิทยาศาสตร์และเทคโนโลยี',classrooms:['6/1'],workWeight:60,beforeWorkWeight:30,midWeight:20,finalWeight:20});await call('students',{courseId:c.id,code:'EXAM001',name:'นักเรียนทดสอบระบบสอบ',number:1});const e=await call('exams',{courseId:c.id,title:'สอบกลางภาค วิทยาศาสตร์',kind:'mid',duration:60,maxScore:20,instructions:'อ่านโจทย์ให้ครบ เลือกคำตอบที่ถูกต้องที่สุด แล้วส่งข้อสอบเมื่อพร้อม',unlockCode:'Teacher-2468',questions:[{type:'choice',prompt:'พลังงานจากแสงอาทิตย์จัดเป็นพลังงานประเภทใด?',points:10,options:['พลังงานหมุนเวียน','พลังงานฟอสซิล','พลังงานนิวเคลียร์','พลังงานจากถ่านหิน'],correct:0},{type:'choice',prompt:'การประหยัดพลังงานในห้องเรียนทำได้ด้วยวิธีใด?',points:10,options:['เปิดไฟทุกดวงตลอดเวลา','ปิดอุปกรณ์ไฟฟ้าเมื่อเลิกใช้งาน','เปิดหน้าต่างพร้อมเครื่องปรับอากาศ','เปิดคอมพิวเตอร์ทิ้งไว้ทั้งคืน'],correct:1}]});await call(`exams/${e.id}`,{status:'open'},'PATCH');const studentId=(await call('state')).enrollments[0].student_id;
for(const phase of ['before','after']){const task=await call('assignments',{courseId:c.id,title:phase==='before'?'งานก่อนกลางภาค':'งานหลังกลางภาค',description:'ข้อมูลจำลองสำหรับตรวจต้นไทร',maxScore:20,workPhase:phase,dueAt:'2027-12-01T09:00:00+07:00',rubric:[]});await call('paper-grade',{assignmentId:task.id,studentId,score:20});}
await db.prepare('UPDATE enrollments SET mid=20,final=20 WHERE course_id=?').bind(c.id).run();await call('courses/'+c.id,{published:true},'PATCH');
for(const [code,name,score] of [['ค30101','คณิตศาสตร์',10],['ศ30101','ศิลปะและการสร้างสรรค์',0],['อ30101','ภาษาอังกฤษ',30],['ท30101','ภาษาไทย',50],['ง30202','คอมพิวเตอร์',100]]){const room=await call('courses',{periodId:p.id,code,name,classrooms:['6/1'],workWeight:60,beforeWorkWeight:30,midWeight:20,finalWeight:20});await call('students',{courseId:room.id,code:'EXAM001',name:'นักเรียนทดสอบระบบสอบ',number:1});let remaining=Math.min(60,score);for(const workPhase of ['before','after']){const points=Math.min(30,remaining);remaining-=points;if(points){const task=await call('assignments',{courseId:room.id,title:'งานจำลอง '+name+' '+workPhase,description:'ทดสอบต้นอ่อนเติบโต',maxScore:30,workPhase,dueAt:'2027-12-01T09:00:00+07:00',rubric:[]});await call('paper-grade',{assignmentId:task.id,studentId,score:points});}}if(score>60){await db.prepare('UPDATE enrollments SET mid=20,final=20 WHERE course_id=?').bind(room.id).run();await call('courses/'+room.id,{published:true},'PATCH');}}
await fetch('http://127.0.0.1:8784/');console.log('Disposable exam preview ready: http://127.0.0.1:8784/');console.log('Test teacher exam_teacher / Exam-Preview-Teacher-1234; student EXAM001 / EXAM001; teacher unlock Teacher-2468');process.on('SIGINT',async()=>{await mf.dispose();process.exit(0);});await new Promise(()=>{});
