'use client';
import { useEffect, useRef, useState } from 'react';
import { GraduationCap,LayoutDashboard,ClipboardCheck,Users,BarChart3,FileSpreadsheet,BookOpen,CalendarDays,ShieldCheck,Plus,RefreshCw,LogOut,KeyRound,Download,Archive,Undo2 } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarGroup,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarInset,SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { api,type AppState,type Row } from '@/lib/client';
import { exportWorkbook } from '@/lib/files-client';
import { AuthScreen } from '@/components/grade/auth-screen';
import { Dashboard } from '@/components/grade/dashboard';
import { CourseView,ReviewView,StudentsView } from '@/components/grade/course-views';
import { Results } from '@/components/grade/results';
import { ImportExport } from '@/components/grade/import-export';
import { Editor,type Edit } from '@/components/grade/editor';
import { Choice,DataTable,Empty,Loading } from '@/components/grade/shared';
export default function GradeApp(){
 const [state,setState]=useState<AppState|null>(null),[user,setUser]=useState<Row|null>(null),[setup,setSetup]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('dashboard'),[periodId,setPeriodId]=useState(''),[courseId,setCourseId]=useState('all'),[edit,setEdit]=useState<Edit|null>(null),[credentials,setCredentials]=useState<any[]>([]),[refreshing,setRefreshing]=useState(false);
 const stateRef=useRef(state);stateRef.current=state;
 async function refresh(){const a=await api('auth');setUser(a.user);setSetup(a.setup);if(a.user&&!a.user.must_change){const s:AppState=await api('state');setState(s);setPeriodId(p=>s.periods.some(x=>x.id===p)?p:s.periods[0]?.id||'');setError('');}else setState(null);}
 useEffect(()=>{let active=true;(async()=>{try{await refresh();}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}})();const focus=()=>{void refresh().catch(()=>{});};window.addEventListener('focus',focus);return ()=>{active=false;window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:any)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'open_grade_view',title:'เปิดหน้าห้องเรียน',description:'Open the requested classroom view. This only changes navigation, and does not modify grades or student records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['dashboard','courses','review','students','results','files']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},async execute(input:any){const allowed=stateRef.current?.user.role==='teacher'?['dashboard','courses','review','students','results','files']:['dashboard','courses','results'];if(!stateRef.current||typeof input?.view!=='string'||!allowed.includes(input.view))throw new Error('ไม่มีสิทธิ์เปิดหน้านี้');setTab(input.view);await new Promise(requestAnimationFrame);return {view:input.view};}});
 return ()=>lifecycle.abort();},[]);
 const teacher=user?.role==='teacher';const courses=state?.courses.filter(c=>c.period_id===periodId)||[];const selected=courseId==='all'?null:courses.find(c=>c.id===courseId);const course=selected||courses[0];const shown=selected?[selected]:courses;
 const items=teacher?[{id:'dashboard',icon:LayoutDashboard,label:'ภาพรวม'},{id:'courses',icon:BookOpen,label:'รายวิชาและงาน'},{id:'review',icon:ClipboardCheck,label:'ตรวจงาน'},{id:'students',icon:Users,label:'นักเรียน'},{id:'results',icon:BarChart3,label:'ผลการเรียน'},{id:'files',icon:FileSpreadsheet,label:'นำเข้า / ส่งออก'}]:[{id:'dashboard',icon:LayoutDashboard,label:'ภาพรวม'},{id:'courses',icon:BookOpen,label:'งานของฉัน'},{id:'results',icon:BarChart3,label:'ผลการเรียน'}];
 const current=items.find(i=>i.id===tab)||items[0];const headings:Record<string,string>={dashboard:teacher?'ภาพรวมการส่งงาน':'ห้องเรียนของฉัน',courses:teacher?'รายวิชาและงานที่มอบหมาย':'งานและคะแนนของฉัน',review:'ตรวจงานนักเรียน',students:'รายชื่อนักเรียน',results:'ผลการเรียน',files:'นำเข้าและส่งออกข้อมูล'};
 async function manualRefresh(){setRefreshing(true);try{await refresh();}catch(e){setError((e as Error).message);}finally{setRefreshing(false);}}
 async function onDone(r:any){if(r?.initialPassword)setCredentials([{code:r.code,password:r.initialPassword}]);if(edit?.kind==='period'&&r?.id){setPeriodId(r.id);setCourseId('all');}if(edit?.kind==='course'&&!edit.item&&r?.id)setCourseId(r.id);await refresh();}
 const activate=(id:string)=>{setTab(id);if(id!=='dashboard'&&courseId==='all'&&course)setCourseId(course.id);};
 return <SidebarProvider><Sidebar><SidebarHeader><div className="brand"><span className="brand-icon"><GraduationCap/></span><div><strong>Grade<span className="brand-dot">.</span></strong><small>ห้องเรียนของคุณ</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><p className="nav-label">{teacher?'จัดการห้องเรียน':'พื้นที่เรียนรู้'}</p><SidebarMenu>{items.map(({id,icon:Icon,label})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={tab===id} disabled={!state} onClick={()=>activate(id)}><Icon/><span>{label}</span>{id==='review'&&state&&<span className="nav-count">{state.submissions.filter(s=>s.status==='pending'&&courses.some(c=>state.assignments.some(a=>a.course_id===c.id&&a.id===s.assignment_id))).length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>{state&&teacher&&<SidebarGroup><p className="nav-label">ภาคเรียน</p><SidebarMenu>{state.periods.slice(0,5).map(p=><SidebarMenuItem key={p.id}><SidebarMenuButton isActive={periodId===p.id} onClick={()=>{setPeriodId(p.id);setCourseId('all');}}><CalendarDays/><span>{p.year} · ภาคเรียน {p.term}</span></SidebarMenuButton></SidebarMenuItem>)}<SidebarMenuItem><SidebarMenuButton onClick={()=>setEdit({kind:'period'})}><Plus/><span>เพิ่มภาคเรียน</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>}</SidebarContent><SidebarFooter><div className="sidebar-note"><ShieldCheck size={19}/><span>ข้อมูลแต่ละเทอม<br/>จัดเก็บแยกกันอย่างเป็นระบบ</span></div>{user&&<div className="user-card"><span className="avatar-mini">{user.name.slice(0,1)}</span><div><strong>{user.name}</strong><small>{teacher?'ครูผู้สอน':`นักเรียน · ${user.username}`}</small></div></div>}</SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div className="row"><SidebarTrigger/><span>{user?(teacher?'พื้นที่ทำงานครู':'พื้นที่นักเรียน'):'Grade · ห้องเรียนออนไลน์'}</span></div>{user&&<div className="row header-actions"><Button variant="ghost" size="icon" aria-label="เปลี่ยนรหัสผ่าน" onClick={()=>setEdit({kind:'password'})}><KeyRound size={17}/></Button><Button variant="ghost" size="sm" onClick={async()=>{try{await api('logout',{});setCredentials([]);setEdit(null);setCourseId('all');setTab('dashboard');await refresh();}catch(e){setError((e as Error).message);}}}><LogOut size={16}/> ออกจากระบบ</Button></div>}</header><main className="workspace">
 {error&&<div className="error" role="alert">{error}<Button size="sm" variant="outline" onClick={manualRefresh}>ลองอีกครั้ง</Button></div>}
 {loading?<Loading/>:!user?<AuthScreen setup={setup} onDone={refresh}/>:user.must_change?<section className="panel"><Empty title="ตั้งรหัสผ่านส่วนตัวก่อนเริ่มใช้งาน" description="เพื่อรักษาคะแนนและงานของคุณ กรุณาเปลี่ยนรหัสผ่านชั่วคราวที่ครูให้" action={<Button onClick={()=>setEdit({kind:'password'})}>เปลี่ยนรหัสผ่าน</Button>}/></section>:state?<><div className="page-heading"><div><p className="eyebrow">{teacher?'TEACHER WORKSPACE':'STUDENT WORKSPACE'}</p><h1>{headings[tab]||headings.dashboard}</h1><p className="muted">{tab==='dashboard'?'ติดตามทุกงานที่ส่ง และทุกความก้าวหน้าในภาคเรียนนี้':state.periods.find(p=>p.id===periodId)?`ปีการศึกษา ${state.periods.find(p=>p.id===periodId)?.year} · ภาคเรียน ${state.periods.find(p=>p.id===periodId)?.term}`:'เริ่มจากเพิ่มภาคเรียนและรายวิชา'}</p></div><div className="row heading-actions"><Button variant="outline" size="icon" aria-label="อัปเดตข้อมูล" onClick={manualRefresh} disabled={refreshing}><RefreshCw size={17} className={refreshing?'animate-spin':''}/></Button>{teacher&&<Button onClick={()=>state.periods.length?setEdit({kind:'course'}):setEdit({kind:'period'})}><Plus size={16}/>{state.periods.length?'เพิ่มรายวิชา':'เพิ่มภาคเรียน'}</Button>}</div></div>
 {state.periods.length>0&&<div className="filterbar"><div className="row"><CalendarDays size={17}/><Choice label="ภาคเรียน" value={periodId} onChange={v=>{setPeriodId(v);setCourseId('all');}} options={state.periods.map(p=>({value:p.id,label:`ปี ${p.year} · เทอม ${p.term}`}))}/><Choice label="รายวิชาและห้องเรียน" value={tab==='dashboard'?courseId:(course?.id||'')} onChange={setCourseId} options={[...(tab==='dashboard'?[{value:'all',label:'ทุกวิชา / ทุกห้อง'}]:[]),...courses.map(c=>({value:c.id,label:`${c.name} · ${c.classroom}${c.archived?' (ประวัติ)':''}`}))]}/></div><span className="muted">{courses.length} รายวิชาในเทอมนี้</span></div>}
 {credentials.length>0&&<section className="panel credentials"><div className="panel-head"><div><h2>รหัสผ่านชั่วคราวนักเรียน</h2><p className="muted">บันทึกหรือดาวน์โหลดไว้ก่อนปิด แสดงเฉพาะรหัสที่สร้างใหม่ นักเรียนต้องเปลี่ยนเมื่อเข้าสู่ระบบ</p></div><Button variant="outline" onClick={()=>setCredentials([])}>ปิดข้อมูล</Button></div><DataTable headers={['รหัสนักเรียน','ชื่อ','รหัสผ่านชั่วคราว']} rows={credentials.map(c=>[c.code,c.name||'—',<code>{c.password}</code>])}/><Button onClick={async()=>{try{await exportWorkbook(credentials.map(c=>({'รหัสนักเรียน':c.code,'ชื่อ':c.name||'','รหัสผ่านชั่วคราว':c.password})),'บัญชีนักเรียน.xlsx');}catch(e){setError((e as Error).message);}}}><Download size={16}/> ดาวน์โหลดบัญชีนักเรียน</Button></section>}
 {!courses.length?<section className="panel"><Empty title={teacher?'เริ่มสร้างรายวิชาแรก':'ยังไม่มีรายวิชาที่ลงทะเบียน'} description={teacher?'เพิ่มรายวิชาและห้องเรียน แล้วนำเข้ารายชื่อนักเรียนเพื่อเริ่มมอบหมายงาน':'ติดต่อครูเพื่อลงทะเบียนในรายวิชา'} action={teacher?<Button onClick={()=>state.periods.length?setEdit({kind:'course'}):setEdit({kind:'period'})}><Plus size={16}/>{state.periods.length?'สร้างรายวิชา':'เพิ่มภาคเรียน'}</Button>:undefined}/></section>:<>{tab==='dashboard'&&<Dashboard state={state} courses={shown} openView={activate}/>} {tab==='courses'&&<CourseView state={state} course={course!} edit={setEdit}/>} {tab==='review'&&teacher&&<ReviewView state={state} course={course!} edit={setEdit}/>} {tab==='students'&&teacher&&<StudentsView state={state} course={course!} edit={setEdit} openImport={()=>activate('files')}/>} {tab==='results'&&<Results key={course!.id} state={state} course={course!} refresh={refresh}/>} {tab==='files'&&teacher&&<ImportExport key={course!.id} state={state} course={course!} refresh={refresh} onCredentials={setCredentials}/>} {teacher&&tab!=='dashboard'&&course&&<div className="archive-control"><span className="muted">{course.archived?'รายวิชานี้เก็บเป็นประวัติแล้ว งานและคะแนนยังดูได้':'เมื่อจบเทอม เก็บรายวิชาเป็นประวัติเพื่อปิดรับงานและป้องกันการแก้ไข'}</span><Button variant="ghost" size="sm" onClick={async()=>{try{await api(`courses/${course.id}`,{archived:!course.archived},'PATCH');await refresh();}catch(e){setError((e as Error).message);}}}>{course.archived?<Undo2 size={15}/>:<Archive size={15}/>} {course.archived?'เปิดใช้งานอีกครั้ง':'เก็บเป็นประวัติ'}</Button></div>}</>}
 </>:<Loading/>}
 </main>{edit&&<Editor key={`${edit.kind}-${edit.item?.id||edit.assignment?.id||'new'}`} edit={edit} state={state} periodId={periodId} onClose={()=>setEdit(null)} onDone={onDone}/>}</SidebarInset></SidebarProvider>;
}
