import {stmt,fail,uid,now,string,number,integer} from './server';
import {attendanceLabels} from './teacher-logic';
import {attemptQuestions,cleanAnswers} from './exam-logic';
const collection=(m:any,k:string)=>{const a=m[k]??[];if(!Array.isArray(a)||a.length>5000)fail(400,'ข้อมูล '+k+' ไม่ถูกต้อง');const ids=new Set();for(const row of a){if(!row||typeof row.id!=='string'||ids.has(row.id))fail(400,'รหัส '+k+' ซ้ำหรือไม่ถูกต้อง');ids.add(row.id);}return a;};
const date=(v:any,optional=false)=>{if(optional&&v==='')return;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(new Date(v).getTime())||new Date(v).toISOString().slice(0,10)!==v)fail(400,'วันที่ในชุดสำรองไม่ถูกต้อง');};
export function validateTeachingBackup(m:any){
 const attendanceSessions=collection(m,'attendanceSessions'),attendanceRecords=collection(m,'attendanceRecords'),followupNotes=collection(m,'followupNotes'),questionBanks=collection(m,'questionBanks');const enroll=new Set(m.enrollments.map((e:any)=>e.course_id+':'+e.student_id)),seen=new Set();
 for(const c of m.courses){number(c.attendance_min??0,'เกณฑ์เวลา');number(c.required_hours??0,'ชั่วโมงขั้นต่ำ',0,1000);}
 for(const a of m.assignments){number(a.individual_weight??0,'สัดส่วนรายบุคคล');if(!a.is_group&&Number(a.individual_weight||0))fail(400,'งานรายบุคคลไม่มีสัดส่วนกลุ่ม');}
 for(const s of m.submissions){const a=m.assignments.find((a:any)=>a.id===s.assignment_id);if(s.individual_score!=null){if(s.status!=='graded')fail(400,'งานรอตรวจไม่มีคะแนนส่วนบุคคล');number(s.individual_score,'คะแนนส่วนบุคคล',0,a.max_score*Number(a.individual_weight||0)/100);}}
 for(const s of attendanceSessions){if(!m.courses.some((c:any)=>c.id===s.course_id))fail(400,'คาบเช็กชื่อไม่ตรงวิชา');date(s.date);string(s.title,'ชื่อคาบ',150);number(s.hours,'ชั่วโมงคาบ',.01,24);}
 for(const r of attendanceRecords){const s=attendanceSessions.find((s:any)=>s.id===r.session_id),key=r.session_id+':'+r.student_id;if(!s||!enroll.has(s.course_id+':'+r.student_id)||!Object.hasOwn(attendanceLabels,r.status)||seen.has(key))fail(400,'เช็กชื่อไม่ตรงทะเบียนหรือซ้ำ');seen.add(key);number(r.hours,'ชั่วโมงเข้าร่วม',0,s.hours);if(['absent','leave'].includes(r.status)&&r.hours!==0)fail(400,'ขาด/ลาต้องไม่มีชั่วโมง');}
 for(const n of followupNotes){if(!enroll.has(n.course_id+':'+n.student_id)||!['open','done'].includes(n.status))fail(400,'บันทึกติดตามไม่ตรงทะเบียน');string(n.text,'บันทึก',3000);date(n.next_date||'',true);}
 for(const b of questionBanks){string(b.name,'ชื่อคลัง',150);let qs;try{qs=JSON.parse(b.questions);}catch{fail(400,'คลังคำถามไม่ถูกต้อง');}validateQuestionForm(qs,qs);}
 for(const a of m.examAttempts||[]){const e=m.exams.find((e:any)=>e.id===a.exam_id);let form;try{form=attemptQuestions(e,a);}catch{fail(400,'ชุดข้อสอบสุ่มไม่ถูกต้อง');}validateQuestionForm(JSON.parse(e.questions),form);try{cleanAnswers(form,JSON.parse(a.answers));}catch{fail(400,'คำตอบไม่ตรงชุดข้อสอบ');}}
 return {attendanceSessions,attendanceRecords,followupNotes,questionBanks};
}
function validateQuestionForm(original:any[],form:any[]){if(!Array.isArray(original)||!original.length||original.length>100||!Array.isArray(form)||form.length!==original.length)fail(400,'ชุดคำถามไม่ครบ');const seen=new Set();for(const q of form){const source=original.find(x=>x.id===q.id);if(!source||seen.has(q.id)||q.prompt!==source.prompt||q.points!==source.points||q.type!==source.type||!['choice','written'].includes(q.type))fail(400,'ชุดคำถามไม่ตรงต้นฉบับ');seen.add(q.id);string(q.prompt,'คำถาม',5000);number(q.points,'คะแนนข้อ',.01,1000);if(q.type==='choice'){if(!Array.isArray(q.options)||q.options.length<2||q.options.length>6||q.options.length!==source.options.length||JSON.stringify([...q.options].sort())!==JSON.stringify([...source.options].sort()))fail(400,'ตัวเลือกไม่ตรงต้นฉบับ');q.options.forEach((o:any)=>string(o,'ตัวเลือก',2000));integer(q.correct,'เฉลย',0,q.options.length-1);if(q.options[q.correct]!==source.options[source.correct])fail(400,'เฉลยสุ่มไม่ตรงต้นฉบับ');}}}
export function restoreTeachingOps(m:any,u:any,courseIds:Map<any,any>,studentIds:Map<any,any>,assignmentIds:Map<any,any>){
 const ops:D1PreparedStatement[]=[],sessionIds=new Map();for(const c of m.courses)ops.push(stmt('UPDATE courses SET attendance_min=?,required_hours=? WHERE id=?',c.attendance_min??0,c.required_hours??0,courseIds.get(c.id)));for(const a of m.assignments)ops.push(stmt('UPDATE assignments SET individual_weight=? WHERE id=?',a.individual_weight??0,assignmentIds.get(a.id)));for(const s of m.submissions)if(s.individual_score!=null)ops.push(stmt('UPDATE submissions SET individual_score=? WHERE assignment_id=? AND student_id=?',s.individual_score,assignmentIds.get(s.assignment_id),studentIds.get(s.student_id)));
 for(const s of m.attendanceSessions){const id=uid();sessionIds.set(s.id,id);ops.push(stmt('INSERT INTO attendance_sessions(id,course_id,date,title,hours,deleted,created_at) VALUES(?,?,?,?,?,?,?)',id,courseIds.get(s.course_id),s.date,s.title,s.hours,Number(!!s.deleted),s.created_at||now()));}
 for(const r of m.attendanceRecords)ops.push(stmt('INSERT INTO attendance_records(id,session_id,student_id,status,hours,note,updated_at) VALUES(?,?,?,?,?,?,?)',uid(),sessionIds.get(r.session_id),studentIds.get(r.student_id),r.status,r.hours,String(r.note||'').slice(0,1000),now()));
 for(const n of m.followupNotes)ops.push(stmt('INSERT INTO followup_notes(id,course_id,student_id,actor_id,text,next_date,status,deleted,created_at) VALUES(?,?,?,?,?,?,?,?,?)',uid(),courseIds.get(n.course_id),studentIds.get(n.student_id),u.id,n.text,n.next_date||'',n.status,Number(!!n.deleted),n.created_at||now()));
 for(const b of m.questionBanks)ops.push(stmt('INSERT INTO question_banks(id,owner_id,name,tags,questions,deleted,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,b.name+' (กู้คืน)',String(b.tags||'').slice(0,300),b.questions,Number(!!b.deleted),b.created_at||now()));return ops;
}
