import {all,one,stmt,database,fail,uid,now,jsonBody,reply,string,integer,number,requireLive,log} from './server';
import {ownCourse,teacher,hashPassword,matches,type User} from './auth';
import {publicQuestions,examScore,cleanAnswers,type ExamQuestion} from './exam-logic';

function meta(e:any){const {unlock_hash,questions,...rest}=e;return rest;}
function safeAttempt(a:any){if(!a)return null;const {page_token,...rest}=a;return rest;}
const event=(a:any,actor:string,action:string,reason:string)=>stmt('INSERT INTO exam_events(id,attempt_id,actor_id,action,reason,created_at) VALUES(?,?,?,?,?,?)',uid(),a.id,actor,action,reason,now());
async function access(u:User,id:string,write=false){await requireLive('exam',id);const e=await one('SELECT * FROM exams WHERE id=? AND deleted=0',id);if(!e)fail(404,'ไม่พบข้อสอบ');const c=await ownCourse(u,e!.course_id,write);if(write&&c.archived)fail(409,'รายวิชาเก็บเข้าประวัติแล้ว');return {e:e!,c};}
async function attemptAccess(u:User,id:string,write=false){const a=await one('SELECT * FROM exam_attempts WHERE id=?',id);if(!a)fail(404,'ไม่พบการสอบ');await requireLive('examAttempt',id);const {e,c}=await access(u,a!.exam_id,write);await requireLive('enrollment',a!.enrollment_id);await requireLive('student',a!.student_id);if(u.role==='student'&&a!.student_id!==u.id)fail(403,'ไม่มีสิทธิ์ดูการสอบนี้');const en=await one('SELECT * FROM enrollments WHERE id=? AND active=1 AND deleted=0',a!.enrollment_id);if(!en)fail(403,'การลงทะเบียนไม่ได้ใช้งาน');return {a:a!,e,c};}
async function finish(a:any,e:any,actor:string,reason:string):Promise<any>{const score=examScore(JSON.parse(e.questions),JSON.parse(a.answers));const changed=await stmt("UPDATE exam_attempts SET status='submitted',score=?,submitted_at=? WHERE id=? AND status IN('active','locked') AND generation=? AND answers=?",score,now(),a.id,a.generation,a.answers).run();if(changed.meta.changes)await event(a,actor,'submitted',reason).run();const latest=(await one('SELECT * FROM exam_attempts WHERE id=?',a.id))!;if(!changed.meta.changes&&['active','locked'].includes(latest.status)&&Date.now()>=latest.deadline)return finish(latest,e,actor,reason);return latest;}
async function settle(a:any,e:any,actor:string){if(!['active','locked'].includes(a.status))return a;if(Date.now()>=a.deadline)return finish(a,e,actor,'หมดเวลาสอบ');if(a.status==='active'&&(Date.now()-a.heartbeat>30000||e.status!=='open')){const reason=e.status!=='open'?'ครูปิดการสอบ':'ขาดการเชื่อมต่อเกิน 30 วินาที';await database().batch([stmt("UPDATE exam_attempts SET status='locked',lock_reason=?,lock_count=lock_count+1,generation=generation+1 WHERE id=? AND status='active' AND generation=?",reason,a.id,a.generation),event(a,actor,'locked',reason)]);return (await one('SELECT * FROM exam_attempts WHERE id=?',a.id))!;}return a;}
function validateQuestions(value:any,max:number):ExamQuestion[]{if(!Array.isArray(value)||!value.length||value.length>100)fail(400,'ข้อสอบต้องมี 1–100 ข้อ');const qs=value.map((q:any,i:number)=>{const type=q.type;if(!['choice','written'].includes(type))fail(400,'ชนิดคำถามไม่ถูกต้อง');const prompt=string(q.prompt,'คำถาม',5000),points=number(q.points,'คะแนนรายข้อ',0.01,max);const options=type==='choice'?q.options:[];if(type==='choice'&&(!Array.isArray(options)||options.length<2||options.length>6))fail(400,'แต่ละข้อเลือกตอบต้องมี 2–6 ตัวเลือก');return {id:'q'+i,type,prompt,points,options:options.map((o:unknown)=>string(o,'ตัวเลือก',2000)),correct:type==='choice'?integer(q.correct,'เฉลย',0,options.length-1):null};});if(Math.abs(qs.reduce((n,q)=>n+q.points,0)-max)>0.001)fail(400,'คะแนนรายข้อต้องรวมเท่าคะแนนเต็ม');return qs;}
function pin(value:unknown){if(typeof value!=='string'||value.length<6||value.length>64)fail(400,'รหัสปลดล็อกครูต้องยาว 6–64 ตัวอักษร');return value;}
function answers(e:any,value:unknown){try{return cleanAnswers(JSON.parse(e.questions),value);}catch(err){fail(400,(err as Error).message);}}
function studentPage(a:any,e:any){return {attempt:{...a,score:null},exam:meta(e),questions:a.status==='active'?publicQuestions(JSON.parse(e.questions)):[],serverNow:Date.now()};}
export async function examRoute(r:Request,u:User,path:string,method:string){
 if(path==='exams'&&method==='POST'){teacher(u);const b=await jsonBody(r),c=await ownCourse(u,string(b.courseId,'ห้องเรียน'),true);if(c.archived)fail(409,'รายวิชาเก็บเข้าประวัติแล้ว');if(!['mid','final'].includes(b.kind))fail(400,'เลือกกลางภาคหรือปลายภาค');const max=number(b.maxScore,'คะแนนเต็ม',0.01,b.kind==='mid'?c.mid_weight:c.final_weight),qs=validateQuestions(b.questions,max),id=uid();try{await stmt('INSERT INTO exams(id,course_id,title,kind,instructions,duration,max_score,questions,unlock_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,c.id,string(b.title,'ชื่อข้อสอบ',200),b.kind,typeof b.instructions==='string'?b.instructions.slice(0,5000):'',integer(b.duration,'เวลาสอบ (นาที)',1,300),max,JSON.stringify(qs),await hashPassword(pin(b.unlockCode)),'draft',now()).run();}catch(err){if((err as Error).message.includes('UNIQUE'))fail(409,'ห้องนี้มีข้อสอบประเภทนี้แล้ว กรุณาแก้ไขชุดเดิม');throw err;}await log(u.id,c.id,'exam_created',{examId:id,kind:b.kind});return reply({id},201);}
 const list=path.match(/^exams\/course\/([^/]+)$/);if(list&&method==='GET'){const c=await ownCourse(u,list[1]);const exams=await all('SELECT * FROM exams WHERE course_id=? ORDER BY created_at',c.id);const result=[];for(const e of exams){if(await one("SELECT 1 FROM trash_entries WHERE kind='exam' AND record_id=?",e.id))continue;if(u.role==='student'&&e.status==='draft')continue;const attempts=await all('SELECT a.*,en.name student_name,en.number student_number,en.student_code FROM exam_attempts a JOIN enrollments en ON en.id=a.enrollment_id WHERE a.exam_id=? AND en.deleted=0 AND en.active=1 AND NOT EXISTS(SELECT 1 FROM trash_entries t WHERE (t.kind=\'examAttempt\' AND t.record_id=a.id) OR (t.kind=\'student\' AND t.record_id=a.student_id))'+(u.role==='student'?' AND a.student_id=?':''),e.id,...(u.role==='student'?[u.id]:[]));const settled=[];for(const a of attempts){const result=safeAttempt(await settle(a,e,u.id));if(u.role==='student')result.score=null;settled.push(result);};result.push({...meta(e),attempts:settled});}return reply({exams:result});}
 const exam=path.match(/^exams\/([^/]+)(?:\/(start))?$/);if(exam){const {e,c}=await access(u,exam[1],method==='PATCH');if(!exam[2]&&method==='GET'){teacher(u);return reply({...meta(e),questions:JSON.parse(e.questions)});}
  if(!exam[2]&&method==='PATCH'){teacher(u);const b=await jsonBody(r);if('status' in b){if(!['draft','open','closed'].includes(b.status))fail(400,'สถานะไม่ถูกต้อง');await stmt('UPDATE exams SET status=? WHERE id=?',b.status,e.id).run();if(b.status!=='open')await stmt("UPDATE exam_attempts SET status='locked',lock_reason='ครูปิดการสอบ',lock_count=lock_count+1,generation=generation+1 WHERE exam_id=? AND status='active'",e.id).run();}else if('unlockCode' in b&&!('questions' in b)){await stmt('UPDATE exams SET unlock_hash=? WHERE id=?',await hashPassword(pin(b.unlockCode)),e.id).run();}else{if(await one('SELECT id FROM exam_attempts WHERE exam_id=?',e.id))fail(409,'มีนักเรียนเริ่มสอบแล้ว แก้คำถามหรือเวลาไม่ได้');const max=number(b.maxScore,'คะแนนเต็ม',0.01,e.kind==='mid'?c.mid_weight:c.final_weight),qs=validateQuestions(b.questions,max);await stmt('UPDATE exams SET title=?,instructions=?,duration=?,max_score=?,questions=? WHERE id=?',string(b.title,'ชื่อข้อสอบ',200),String(b.instructions||'').slice(0,5000),integer(b.duration,'เวลาสอบ',1,300),max,JSON.stringify(qs),e.id).run();}await log(u.id,c.id,'exam_updated',{examId:e.id,status:b.status||null,codeChanged:'unlockCode' in b&&!('questions' in b)});return reply({ok:true});}
  if(exam[2]&&method==='POST'){if(u.role!=='student')fail(403,'เฉพาะนักเรียนเริ่มสอบได้');if(c.archived||e.status!=='open')fail(409,'ข้อสอบยังไม่เปิดหรือครูปิดรับแล้ว');const en=await one('SELECT * FROM enrollments WHERE course_id=? AND student_id=? AND active=1 AND deleted=0',c.id,u.id);if(!en)fail(403,'ไม่ได้ลงทะเบียน');let a:any=await one('SELECT * FROM exam_attempts WHERE exam_id=? AND student_id=?',e.id,u.id);if(a){await requireLive('examAttempt',a.id);if(a.enrollment_id!==en.id)fail(409,'ทะเบียนสอบเดิมไม่ตรง กรุณาติดต่อครู');a=await settle(a,e,u.id);if(a.status==='active'){await database().batch([stmt("UPDATE exam_attempts SET status='locked',lock_reason='เปิดหน้าสอบใหม่หรือรีโหลด',lock_count=lock_count+1,generation=generation+1 WHERE id=? AND status='active' AND generation=?",a.id,a.generation),event(a,u.id,'locked','เปิดหน้าสอบใหม่หรือรีโหลด')]);a=await one('SELECT * FROM exam_attempts WHERE id=?',a.id);}return reply(studentPage(a,e));}
   const t=Date.now(),id=uid();try{await database().batch([stmt("INSERT INTO exam_attempts(id,exam_id,enrollment_id,student_id,status,answers,started_at,deadline,heartbeat,page_token) VALUES(?,?,?,?,'active','{}',?,?,?,?)",id,e.id,en.id,u.id,t,t+e.duration*60000,t,uid()),event({id},u.id,'started','เริ่มสอบ')]);}catch{fail(409,'เปิดการสอบอีกหน้าแล้ว กรุณาเปิดใหม่');}return reply(studentPage(await one('SELECT * FROM exam_attempts WHERE id=?',id),e),201);}
 }
 const route=path.match(/^exam-attempts\/([^/]+)(?:\/(save|heartbeat|lock|unlock|submit|grade|sync))?$/);if(!route)return null;
 const op=route[2],{e,c,a:initial}=await attemptAccess(u,route[1],['grade','sync'].includes(op));let a=await settle(initial,e,u.id);
 if(method==='GET'&&!op){if(u.role!=='student')teacher(u);return reply(u.role==='student'?studentPage(a,e):{attempt:safeAttempt(a),exam:meta(e),questions:JSON.parse(e.questions),events:await all('SELECT * FROM exam_events WHERE attempt_id=? ORDER BY created_at',a.id)});}
 if(method!=='POST'||!op)return null;const b=await jsonBody(r);
 if(['grade','sync'].includes(op)){teacher(u);if(a.status!=='submitted')fail(409,'ยังไม่ส่งข้อสอบ');if(op==='grade'){const score=number(b.score,'คะแนนสอบ',0,e.max_score);await database().batch([stmt('UPDATE exam_attempts SET score=?,synced=0 WHERE id=?',score,a.id),stmt('UPDATE courses SET published=0,revision=revision+1 WHERE id=?',c.id),event(a,u.id,'graded','ครูตรวจให้คะแนน')]);return reply({ok:true});}if(a.score===null)fail(409,'ต้องตรวจให้คะแนนก่อน');if(a.score>(e.kind==='mid'?c.mid_weight:c.final_weight))fail(409,'คะแนนเกินสัดส่วนของวิชา');await database().batch([stmt(`UPDATE enrollments SET ${e.kind==='mid'?'mid':'final'}=? WHERE id=?`,a.score,a.enrollment_id),stmt('UPDATE exam_attempts SET synced=1 WHERE id=?',a.id),stmt('UPDATE courses SET published=0,revision=revision+1,grading_mode=\'points\' WHERE id=?',c.id),event(a,u.id,'synced','บันทึกคะแนนลงผลการเรียน')]);await log(u.id,c.id,'exam_scores',{examId:e.id,attemptId:a.id,kind:e.kind,score:a.score});return reply({ok:true});}
 if(u.role!=='student'||a.student_id!==u.id)fail(403,'เฉพาะนักเรียนเจ้าของการสอบ');
 if(op==='unlock'){if(a.status!=='locked')fail(409,'การสอบไม่ได้ล็อก');if(e.status!=='open'||c.archived)fail(409,'ครูต้องเปิดการสอบก่อน');const key='exam-unlock:'+a.id,t=Date.now();await stmt('INSERT INTO login_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END',key,t+900000,t,t).run();if((await one('SELECT count FROM login_limits WHERE key=?',key))!.count>5)fail(429,'รหัสผิดหลายครั้ง กรุณารอ 15 นาที');if(typeof b.code!=='string'||b.code.length>64||!await matches(b.code,e.unlock_hash))fail(403,'รหัสปลดล็อกครูไม่ถูกต้อง');const changed=await stmt("UPDATE exam_attempts SET status='active',page_token=?,generation=generation+1,heartbeat=?,lock_reason='' WHERE id=? AND status='locked' AND generation=? AND deadline>?",uid(),t,a.id,a.generation,t).run();if(!changed.meta.changes)fail(409,'สถานะสอบเปลี่ยนหรือหมดเวลาแล้ว');await event(a,u.id,'unlocked','ใช้รหัสปลดล็อกครู').run();await stmt('DELETE FROM login_limits WHERE key=?',key).run();a=await one('SELECT * FROM exam_attempts WHERE id=?',a.id) as any;return reply(studentPage(a,e));}
 if(a.status==='submitted')return op==='submit'?reply(studentPage(a,e)):reply({error:'ส่งข้อสอบแล้ว',status:a.status},409);
 if(a.status!=='active')return reply({error:'การสอบถูกล็อก ต้องให้ครูใส่รหัสปลดล็อก',status:'locked'},423);
 if(b.token!==a.page_token||b.generation!==a.generation)fail(409,'หน้านี้ไม่ได้เป็นหน้าสอบปัจจุบัน');
 if(e.status!=='open'||c.archived)fail(409,'การสอบปิดแล้ว');const t=Date.now();
 const guard="id=? AND status='active' AND page_token=? AND generation=? AND deadline>? AND EXISTS(SELECT 1 FROM exams e WHERE e.id=exam_attempts.exam_id AND e.status='open' AND e.deleted=0)";const params=[a.id,a.page_token,a.generation,t];
 if(op==='lock'){const reason=string(b.reason,'เหตุผลล็อก',200);const draft=b.answers===undefined?a.answers:JSON.stringify(answers(e,b.answers));const change=await stmt(`UPDATE exam_attempts SET status='locked',answers=?,lock_reason=?,lock_count=lock_count+1,generation=generation+1 WHERE ${guard}`,draft,reason,...params).run();if(change.meta.changes)await event(a,u.id,'locked',reason).run();return reply({ok:true,status:'locked'});}
 if(op==='save'||op==='heartbeat'){const change=op==='save'?await stmt(`UPDATE exam_attempts SET answers=?,heartbeat=? WHERE ${guard}`,JSON.stringify(answers(e,b.answers)),t,...params).run():await stmt(`UPDATE exam_attempts SET heartbeat=? WHERE ${guard}`,t,...params).run();if(!change.meta.changes)fail(423,'การสอบถูกล็อกหรือหมดเวลา');return reply({ok:true,serverNow:t});}
 if(op==='submit'){const draft=JSON.stringify(answers(e,b.answers));const score=examScore(JSON.parse(e.questions),JSON.parse(draft));const change=await stmt(`UPDATE exam_attempts SET answers=?,status='submitted',score=?,submitted_at=? WHERE ${guard}`,draft,score,now(),...params).run();if(!change.meta.changes)fail(423,'การสอบถูกล็อกหรือหมดเวลา');await event(a,u.id,'submitted','นักเรียนส่งข้อสอบ').run();return reply(studentPage(await one('SELECT * FROM exam_attempts WHERE id=?',a.id),e));}
 return null;
}
