import {all,one,stmt,database,bucket,fail,uid,now,string,number,integer,jsonBody,reply,log,requireLive} from './server';
import {teacher,ownCourse,hashPassword,passwordValid,digest,type User} from './auth';
import {subjectPlan} from './subjects-server';
import {getState} from './state';
import {parseRubric,rubricScore} from './rubrics';
import {validateRestore,commitRestore} from './restore-server';
function admin(u:User){if(u.role!=='admin')fail(403,'เฉพาะผู้ดูแลระบบ');}
async function task(u:User,id:string,write=true){await requireLive('assignment',id);const a=await one('SELECT * FROM assignments WHERE id=?',id);if(!a)fail(404,'ไม่พบงาน');const c=await ownCourse(u,a!.course_id,write);if(write&&c.archived)fail(409,'วิชาเก็บเป็นประวัติแล้ว');return {a:a!,c};}
function invalidate(id:string){return stmt('UPDATE courses SET published=0,grading_mode=\'points\',revision=revision+1 WHERE id=?',id);}
async function job(u:User,id:string){const j=await one('SELECT * FROM restore_jobs WHERE id=? AND owner_id=?',id,u.id);if(!j||j.status!=='staging')fail(409,'ชุดกู้คืนนี้ปิดแล้วหรือไม่มีสิทธิ์');return j!;}
export async function extendedRoute(r:Request,u:User,path:string,method:string):Promise<Response|null>{
 if(path==='staff'&&method==='POST'){
  admin(u);const b=await jsonBody(r);const username=string(b.username,'ชื่อผู้ใช้',40);if(!/^[a-zA-Z0-9_.-]{3,40}$/.test(username)||!['teacher','homeroom'].includes(b.role))fail(400,'ชื่อผู้ใช้หรือบทบาทไม่ถูกต้อง');const id=uid(),password=`Gr-${uid().slice(0,16)}`;
  try{await stmt('INSERT INTO users (id,username,name,role,password,active,must_change,created_at) VALUES (?,?,?,?,?,1,1,?)',id,username,string(b.name,'ชื่อ',100),b.role,await hashPassword(password),now()).run();}catch{fail(409,'ชื่อผู้ใช้นี้มีแล้ว');}await log(u.id,null,'create_staff',{id,role:b.role});return reply({id,credentials:[{code:username,name:b.name,password}]},201);
 }
 if(path.startsWith('staff/')&&method==='PATCH'){
  admin(u);const id=path.slice(6),b=await jsonBody(r),s=await one("SELECT * FROM users WHERE id=? AND role!='student'",id);if(!s)fail(404,'ไม่พบบัญชีครู');if(id===u.id)fail(409,'ไม่สามารถปิดหรือเปลี่ยนสิทธิ์บัญชีผู้ดูแลที่ใช้อยู่');
  if(b.resetPassword){const password=passwordValid(b.password);await database().batch([stmt('UPDATE users SET password=?,must_change=1 WHERE id=?',await hashPassword(password),id),stmt('DELETE FROM sessions WHERE user_id=?',id)]);return reply({ok:true});}
  if(!['admin','teacher','homeroom'].includes(b.role))fail(400,'บทบาทไม่ถูกต้อง');if(b.role==='homeroom'&&await one('SELECT id FROM courses WHERE owner_id=?',id))fail(409,'บัญชีนี้เป็นเจ้าของรายวิชาอยู่ ไม่สามารถเปลี่ยนเป็นสิทธิ์ดูอย่างเดียว');const active=b.active===false?0:1;const changed=await stmt("UPDATE users SET role=?,active=? WHERE id=? AND (role!='admin' OR (?='admin' AND ?=1) OR (SELECT COUNT(*) FROM users WHERE role='admin' AND active=1)>1)",b.role,active,id,b.role,active).run();if(!changed.meta.changes)fail(409,'ต้องเหลือผู้ดูแลที่ใช้งานได้อย่างน้อยหนึ่งคน');await stmt('DELETE FROM sessions WHERE user_id=?',id).run();await log(u.id,null,'staff_access',{id,role:b.role,active:b.active!==false});return reply({ok:true});
 }
 if(path==='course-access'&&method==='POST'){
  admin(u);const b=await jsonBody(r);await ownCourse(u,b.courseId,true);const s=await one("SELECT id,role FROM users WHERE id=? AND role!='student' AND active=1",b.userId);if(!s)fail(404,'ไม่พบครู');if(!['edit','view','remove'].includes(b.permission)||s!.role==='homeroom'&&b.permission==='edit')fail(400,'ครูประจำชั้นได้รับสิทธิ์ดูเท่านั้น');if(b.permission==='remove')await stmt('DELETE FROM course_staff WHERE course_id=? AND user_id=?',b.courseId,b.userId).run();else await stmt('INSERT INTO course_staff (id,course_id,user_id,permission) VALUES (?,?,?,?) ON CONFLICT(course_id,user_id) DO UPDATE SET permission=excluded.permission',uid(),b.courseId,b.userId,b.permission).run();await log(u.id,b.courseId,'course_access',{userId:b.userId,permission:b.permission});return reply({ok:true});
 }
 if(path==='extensions'&&method==='POST'){
  teacher(u);const b=await jsonBody(r);const {a}=await task(u,b.assignmentId);if(!(await getState(u)).enrollments.some(e=>e.course_id===a.course_id&&e.student_id===b.studentId&&e.active))fail(404,'นักเรียนไม่ได้ลงทะเบียน');const due=new Date(b.dueAt);if(!Number.isFinite(due.getTime()))fail(400,'วันส่งไม่ถูกต้อง');await database().batch([stmt('INSERT INTO extensions (id,assignment_id,student_id,due_at,note) VALUES (?,?,?,?,?) ON CONFLICT(assignment_id,student_id) WHERE deleted=0 DO UPDATE SET due_at=excluded.due_at,note=excluded.note',uid(),a.id,b.studentId,due.toISOString(),String(b.note||'').slice(0,1000)),invalidate(a.course_id)]);await log(u.id,a.course_id,'extension',{studentId:b.studentId,assignmentId:a.id,dueAt:due.toISOString()});return reply({ok:true});
 }
 if(path==='paper-grade'&&method==='POST'){
  teacher(u);const b=await jsonBody(r);const {a,c}=await task(u,b.assignmentId);if(!(await getState(u)).enrollments.some(e=>e.course_id===c.id&&e.student_id===b.studentId&&e.active))fail(404,'นักเรียนไม่ได้ลงทะเบียน');if(await one('SELECT id FROM submissions WHERE assignment_id=? AND student_id=? AND deleted=0',a.id,b.studentId))fail(409,'มีงานส่งแล้ว กรุณาตรวจหรือแก้จากงานเดิม');let score=number(b.score,'คะแนน',0,a.max_score);const rubric=parseRubric(a.rubric);if(rubric.length)try{score=rubricScore(rubric,b.rubricScores);}catch(e){fail(400,(e as Error).message);}const id=uid(),feedback=String(b.feedback||'').slice(0,5000);
  try{await database().batch([stmt("INSERT INTO submissions (id,assignment_id,student_id,note,submitted_at,score,feedback,status,revision,reviewed_at,rubric_scores,source) VALUES (?,?,?,'ส่งงานในห้องเรียน',?,?,?,'graded',1,?,?,'paper')",id,a.id,b.studentId,now(),score,feedback,now(),JSON.stringify(b.rubricScores||[])),invalidate(c.id)]);}catch{fail(409,'งานนี้มีข้อมูลแล้ว กรุณาอัปเดตตาราง');}await log(u.id,c.id,'paper_grade',{submissionId:id,score,studentId:b.studentId});return reply({id},201);
 }
 if(path==='feedback-image'&&method==='POST'){
  teacher(u);const form=await r.formData();const s=await one('SELECT * FROM submissions WHERE id=?',String(form.get('submissionId')));if(!s)fail(404,'ไม่พบงานส่ง');await requireLive('submission',s!.id);const {a}=await task(u,s!.assignment_id);if(Number(form.get('revision'))!==s!.revision)fail(409,'งานเปลี่ยนรุ่นแล้ว');const f=form.get('file');if(!(f instanceof File)||f.size<1||f.size>10*1024*1024)fail(400,'รูปคำแนะนำต้องไม่เกิน 10 MB');const data=await f.arrayBuffer();if(new Uint8Array(data).slice(0,8).join(',')!=='137,80,78,71,13,10,26,10')fail(400,'รูปคำแนะนำต้องเป็น PNG');const id=uid();await bucket().put(id,data,{httpMetadata:{contentType:'image/png'}});try{await database().batch([stmt('INSERT INTO files (id,course_id,assignment_id,student_id,revision,kind,name,mime,size,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,a.course_id,a.id,s!.student_id,s!.revision,'feedback',`คำแนะนำ-${f.name.slice(0,100)}`,'image/png',f.size,now()),stmt('UPDATE courses SET revision=revision+1 WHERE id=?',a.course_id)]);}catch(e){await bucket().delete(id);throw e;}return reply({id},201);
 }
 if(path==='copy-course'&&method==='POST'){
  teacher(u);const b=await jsonBody(r),c=await ownCourse(u,b.courseId);if(!await one('SELECT id FROM periods WHERE id=?',b.periodId))fail(404,'ไม่พบภาคเรียนปลายทาง');const days=integer(b.shiftDays,'จำนวนวันเลื่อนกำหนดส่ง',-3650,3650),id=uid();const state=await getState(u);const assignments=state.assignments.filter(a=>a.course_id===c.id),samples=state.files.filter(f=>f.course_id===c.id&&!f.student_id),ids=new Map(assignments.map(a=>[a.id,uid()]));const copied:any[]=[];
  const parent=await subjectPlan(u,b);const ops=[...parent.ops,stmt('INSERT INTO courses (id,subject_id,period_id,owner_id,code,name,classroom,work_weight,mid_weight,final_weight,before_work_weight,grading_mode,published,archived,revision) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'points\',0,0,0)',id,parent.id,b.periodId,u.id,string(b.code,'รหัสวิชา',30),string(b.name,'ชื่อวิชา',100),string(b.classroom,'ห้อง',40),c.work_weight,c.mid_weight,c.final_weight,c.before_work_weight??c.work_weight/2)];
  for(const a of assignments)ops.push(stmt('INSERT INTO assignments (id,course_id,title,description,max_score,due_at,rubric,work_phase,created_at) VALUES (?,?,?,?,?,?,?,?,?)',ids.get(a.id),id,a.title,a.description,a.max_score,new Date(new Date(a.due_at).getTime()+days*86400000).toISOString(),a.rubric,a.work_phase,now()));
  try{for(const f of samples){const object=await bucket().get(f.id);if(!object)fail(409,`ไฟล์ตัวอย่าง ${f.name} หายไป ไม่คัดลอกชุดที่ไม่ครบ`);const key=uid();await bucket().put(key,object.body,{httpMetadata:{contentType:f.mime}});copied.push(key);ops.push(stmt('INSERT INTO files (id,course_id,assignment_id,student_id,revision,kind,name,mime,size,created_at) VALUES (?,?,?,NULL,0,?,?,?,?,?)',key,id,ids.get(f.assignment_id),'work',f.name,f.mime,f.size,now()));}if(b.copyRoster){for(const e of state.enrollments.filter(e=>e.course_id===c.id&&e.active))ops.push(stmt("INSERT INTO enrollments (id,course_id,student_id,student_code,name,number,active,special) VALUES (?,?,?,?,?,?,1,'')",uid(),id,e.student_id,e.student_code,e.name,e.number));}await database().batch(ops);}catch(e){await Promise.all(copied.map(key=>bucket().delete(key)));if((e as any).status)throw e;fail(409,'รายวิชา/ห้องนี้มีแล้ว หรือคัดลอกไม่ได้ ไม่มีคะแนนเดิมถูกแก้ไข');}await log(u.id,id,'copy_course',{from:c.id,shiftDays:days,copyRoster:!!b.copyRoster});return reply({id},201);
 }
 if(path==='sgs-profiles'&&method==='POST'){
  teacher(u);const form=await r.formData(),name=string(form.get('name'),'ชื่อรูปแบบ',100),f=form.get('file');let config;try{config=JSON.parse(String(form.get('config')));}catch{fail(400,'รูปแบบไม่ถูกต้อง');}if(!config||typeof config.sheet!=='string'||!config.sheet||!Number.isInteger(config.startRow)||config.startRow<1||config.startRow>10000||!['none','nearest','floor','ceil'].includes(config.rounding)||![0,1,2].includes(config.precision))fail(400,'ตั้งค่าแผ่นงานหรือปัดคะแนนไม่ถูกต้อง');const keys=['idColumn','workColumn','midColumn','finalColumn','totalColumn','gradeColumn'];const cols=keys.map(k=>config[k]);if(!cols[0]||cols.some((c,i)=>typeof c!=='string'||(c!==''&&!/^[A-Z]{1,3}$/.test(c)))||new Set(cols.filter(Boolean)).size!==cols.filter(Boolean).length)fail(400,'คอลัมน์ไม่ถูกต้องหรือซ้ำ');if(!(f instanceof File)||!f.name.toLowerCase().endsWith('.xlsx')||f.size<1||f.size>15*1024*1024)fail(400,'ต้นแบบต้องเป็น .xlsx ไม่เกิน 15 MB');const data=await f.arrayBuffer(),bytes=new Uint8Array(data);if(bytes[0]!==80||bytes[1]!==75)fail(400,'ต้นแบบไม่ใช่ Excel');const id=uid(),key=uid();await bucket().put(key,data,{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});try{await stmt('INSERT INTO sgs_profiles (id,owner_id,name,config,template_key,template_name,size,created_at) VALUES (?,?,?,?,?,?,?,?)',id,u.id,name,JSON.stringify({...config,allowOverwrite:false}),key,f.name.slice(0,200),f.size,now()).run();}catch(e){await bucket().delete(key);throw e;}return reply({id},201);
 }
 if(path.startsWith('sgs-template/')&&method==='GET'){
  teacher(u);await requireLive('profile',path.slice(13));const p=await one('SELECT * FROM sgs_profiles WHERE id=? AND owner_id=?',path.slice(13),u.id);if(!p)fail(404,'ไม่พบต้นแบบ');const object=await bucket().get(p!.template_key);if(!object)fail(404,'ไม่พบไฟล์');return new Response(object.body,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Cache-Control':'private, no-store','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(p!.template_name)}`}});
 }
 if(path==='backup'&&method==='GET'){
  teacher(u);const state=await getState(u);const audits=await all('SELECT * FROM audit WHERE course_id IN (SELECT c.id FROM courses c WHERE '+(u.role==='admin'?'1=1':'c.owner_id=? OR EXISTS (SELECT 1 FROM course_staff cs WHERE cs.course_id=c.id AND cs.user_id=?)')+') ORDER BY created_at',...(u.role==='admin'?[]:[u.id,u.id]));return reply({format:'grade-backup',version:2,exportedAt:now(),...state,audit:audits});
 }
 if(path==='restore/start'&&method==='POST'){
  teacher(u);const b=await jsonBody(r),manifest=validateRestore(b.manifest);const id=uid();await stmt('INSERT INTO restore_jobs (id,owner_id,manifest,status,created_at) VALUES (?,?,?,?,?)',id,u.id,JSON.stringify(manifest),'staging',now()).run();return reply({id,assets:manifest.assets.length,courses:manifest.courses.length},201);
 }
 if(path==='restore/asset'&&method==='POST'){
  teacher(u);const form=await r.formData(),j=await job(u,String(form.get('jobId'))),manifest=JSON.parse(j.manifest),asset=manifest.assets.find((a:any)=>a.id===form.get('assetId')),f=form.get('file');if(!asset||!(f instanceof File)||f.size!==asset.size||f.size>15*1024*1024)fail(400,'ไฟล์กู้คืนไม่ตรงกับรายการ');const data=await f.arrayBuffer(),hash=await digestBytes(data);if(hash!==asset.sha256)fail(400,'ไฟล์สำรองเสียหาย ตรวจลายนิ้วมือไม่ผ่าน');const bytes=new Uint8Array(data),text=new TextDecoder();const valid=asset.mime==='image/png'?bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':asset.mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:asset.mime==='image/webp'?text.decode(bytes.slice(0,4))==='RIFF'&&text.decode(bytes.slice(8,12))==='WEBP':asset.mime==='application/pdf'?text.decode(bytes.slice(0,5))==='%PDF-':bytes[0]===80&&bytes[1]===75&&bytes[2]===3&&bytes[3]===4;if(!valid)fail(400,'ชนิดไฟล์กู้คืนไม่ตรงกับข้อมูล');const old=await one('SELECT * FROM restore_assets WHERE job_id=? AND asset_id=?',j.id,asset.id);if(old)return reply({ok:true});const key=uid();await bucket().put(key,data,{httpMetadata:{contentType:asset.mime}});try{await stmt('INSERT INTO restore_assets (id,job_id,asset_id,object_key,sha256,size) VALUES (?,?,?,?,?,?)',uid(),j.id,asset.id,key,hash,f.size).run();}catch(e){await bucket().delete(key);throw e;}return reply({ok:true},201);
 }
 if(path==='restore/commit'&&method==='POST'){
  teacher(u);const b=await jsonBody(r),j=await job(u,b.jobId);const result=await commitRestore(u,j);return reply(result,201);
 }
 if(path==='restore/cancel'&&method==='POST'){
  teacher(u);const b=await jsonBody(r),j=await job(u,b.jobId);const assets=await all('SELECT object_key FROM restore_assets WHERE job_id=?',j.id);await stmt('UPDATE restore_jobs SET status=? WHERE id=?','cancelled',j.id).run();await Promise.all(assets.map(a=>bucket().delete(a.object_key)));return reply({ok:true});
 }
 return null;
}
async function digestBytes(data:ArrayBuffer){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),x=>x.toString(16).padStart(2,'0')).join('');}
