import {all,one,stmt,database,fail,uid,now,string,number,integer,log} from './server';
import {hashPassword,type User} from './auth';
import {validateRubric,parseRubric,rubricScore} from './rubrics';
const mimeTypes=new Set(['image/jpeg','image/png','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
function rows(m:any,key:string,max=5000){if(!Array.isArray(m[key])||m[key].length>max)fail(400,`รายการ ${key} ไม่ถูกต้องหรือมากเกินไป`);const ids=new Set();for(const row of m[key]){if(!row||typeof row.id!=='string'||!row.id||row.id.length>200||ids.has(row.id))fail(400,`รหัส ${key} ซ้ำหรือไม่ถูกต้อง`);ids.add(row.id);}return m[key] as any[];}
function date(v:any){if(typeof v!=='string'||!Number.isFinite(new Date(v).getTime()))fail(400,'วันที่ในข้อมูลสำรองไม่ถูกต้อง');return new Date(v).toISOString();}
export function validateRestore(m:any){
 if(!m||m.format!=='grade-backup'||m.version!==2)fail(400,'รองรับชุดสำรอง Grade ZIP รุ่น 2 เท่านั้น');const periods=rows(m,'periods',100),courses=rows(m,'courses',100),assignments=rows(m,'assignments'),enrollments=rows(m,'enrollments'),submissions=rows(m,'submissions'),files=rows(m,'files'),students=rows(m,'students'),extensions=rows(m,'extensions'),profiles=rows(m,'profiles',100),assets=rows(m,'assets');
 if(courses.length+assignments.length+enrollments.length+submissions.length+files.length+extensions.length>5000)fail(413,'ชุดกู้คืนใหญ่เกินไป กรุณาสำรองแยกรายวิชา');const by=(a:any[])=>new Map(a.map(x=>[x.id,x])),ps=by(periods),cs=by(courses),as=by(assignments),us=by(students),es=new Set(enrollments.map(e=>`${e.course_id}:${e.student_id}`));const userCodes=new Set(),courseKeys=new Set(),subKeys=new Set();
 for(const p of periods){integer(p.year,'ปี',2500,2700);integer(p.term,'เทอม',1,3);}
 for(const u of students){const code=string(u.username,'รหัสนักเรียน',40);if(!/^[a-zA-Z0-9_.-]{1,40}$/.test(code)||userCodes.has(code))fail(400,'รหัสนักเรียนซ้ำหรือไม่ถูกต้อง');userCodes.add(code);string(u.name,'ชื่อ',100);}
 for(const c of courses){if(!ps.has(c.period_id))fail(400,'วิชาไม่มีภาคเรียน');string(c.code,'รหัสวิชา',30);string(c.name,'ชื่อวิชา',100);string(c.classroom,'ห้อง',40);number(c.work_weight,'คะแนนเก็บ');number(c.mid_weight,'กลางภาค');number(c.final_weight,'ปลายภาค');if(Math.abs(c.work_weight+c.mid_weight+c.final_weight-100)>.0001)fail(400,'สัดส่วนคะแนนไม่ครบ 100');const key=`${c.period_id}:${c.code}:${c.classroom}`;if(courseKeys.has(key))fail(400,'รายวิชาซ้ำ');courseKeys.add(key);}
 for(const a of assignments){if(!cs.has(a.course_id))fail(400,'งานไม่มีรายวิชา');string(a.title,'ชื่องาน',150);number(a.max_score,'คะแนนเต็ม',.1,1000);date(a.due_at);try{validateRubric(a.rubric,a.max_score);}catch(e){fail(400,(e as Error).message);}}
 const enrollmentKeys=new Set();for(const e of enrollments){const c=cs.get(e.course_id);if(!c||!us.has(e.student_id)||us.get(e.student_id).username!==e.student_code)fail(400,'รายชื่อไม่ตรงบัญชี');const key=`${e.course_id}:${e.student_id}`;if(enrollmentKeys.has(key))fail(400,'การลงทะเบียนซ้ำ');enrollmentKeys.add(key);string(e.name,'ชื่อ',100);integer(e.number,'เลขที่',1,999);if(e.mid!==null)number(e.mid,'กลางภาค',0,c.mid_weight);if(e.final!==null)number(e.final,'ปลายภาค',0,c.final_weight);if(!['','ร','มส'].includes(e.special))fail(400,'สถานะคะแนนไม่ถูกต้อง');}
 for(const s of submissions){const a=as.get(s.assignment_id);if(!a||!es.has(`${a.course_id}:${s.student_id}`)||!['pending','graded','returned'].includes(s.status)||!['paper','upload'].includes(s.source))fail(400,'งานส่งไม่ตรงรายชื่อ');const key=`${s.assignment_id}:${s.student_id}`;if(subKeys.has(key))fail(400,'งานส่งซ้ำ');subKeys.add(key);integer(s.revision,'รุ่นงาน',1,10000);date(s.submitted_at);if(s.status==='graded'){number(s.score,'คะแนน',0,a.max_score);const rubric=parseRubric(a.rubric);if(rubric.length){let total;try{total=rubricScore(rubric,JSON.parse(s.rubric_scores));}catch(e){fail(400,'คะแนนเกณฑ์ในชุดสำรองไม่ถูกต้อง');}if(total!==s.score)fail(400,'คะแนนรวมเกณฑ์ไม่ตรง');}}else if(s.score!==null)fail(400,'งานรอตรวจหรือคืนแก้ต้องไม่มีคะแนน');}
 for(const f of files){const a=as.get(f.assignment_id);if(!a||a.course_id!==f.course_id||(f.student_id&&!es.has(`${f.course_id}:${f.student_id}`))||!mimeTypes.has(f.mime))fail(400,'ไฟล์ไม่ตรงรายวิชา');integer(f.size,'ขนาดไฟล์',1,10*1024*1024);integer(f.revision,'รุ่นไฟล์',0,10000);string(f.name,'ชื่อไฟล์',200);if(!['work','feedback'].includes(f.kind))fail(400,'ชนิดไฟล์ไม่ถูกต้อง');}
 for(const x of extensions){const a=as.get(x.assignment_id);if(!a||!es.has(`${a.course_id}:${x.student_id}`))fail(400,'รายการขยายเวลาไม่ตรงรายชื่อ');date(x.due_at);}
 for(const p of profiles){string(p.name,'ชื่อรูปแบบ',100);string(p.template_name,'ชื่อต้นแบบ',200);integer(p.size,'ขนาดต้นแบบ',1,15*1024*1024);try{const config=JSON.parse(p.config);if(!config||typeof config.sheet!=='string')throw Error();}catch{fail(400,'รูปแบบ SGS ไม่ถูกต้อง');}}
 const fileMap=by(files),profileMap=by(profiles),assetKeys=new Set();let totalBytes=0;for(const a of assets){const item=a.kind==='file'?fileMap.get(a.referenceId):a.kind==='template'?profileMap.get(a.referenceId):null;const key=`${a.kind}:${a.referenceId}`;if(!item||assetKeys.has(key)||typeof a.sha256!=='string'||!/^[a-f0-9]{64}$/.test(a.sha256)||a.size!==item.size||!mimeTypes.has(a.mime)||a.kind==='file'&&a.mime!==item.mime||a.kind==='template'&&a.mime!=='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')fail(400,'รายการไฟล์สำรองไม่ครบหรือไม่ตรง');assetKeys.add(key);totalBytes+=a.size;}if(assets.length!==files.length+profiles.length||totalBytes>250*1024*1024)fail(413,'ต้องมีไฟล์ครบชุด และขนาดรวมไม่เกิน 250 MB');
 return {format:'grade-backup',version:2,periods,courses,assignments,enrollments,submissions,files,students,extensions,profiles,assets,audit:Array.isArray(m.audit)?m.audit.slice(0,1000):[]};
}
export async function commitRestore(u:User,j:any){
 const m=validateRestore(JSON.parse(j.manifest)),uploaded=await all('SELECT * FROM restore_assets WHERE job_id=?',j.id);if(uploaded.length!==m.assets.length)fail(409,'ยังอัปโหลดไฟล์ไม่ครบ ไม่มีข้อมูลถูกกู้คืน');const assetMap=new Map();for(const a of m.assets){const item=uploaded.find(x=>x.asset_id===a.id);if(!item||item.sha256!==a.sha256||item.size!==a.size)fail(409,'ไฟล์ไม่ครบหรือไม่ตรง');assetMap.set(`${a.kind}:${a.referenceId}`,item.object_key);}
 const periodCache=new Map();const ops=[],periodIds=new Map(),studentIds=new Map(),courseIds=new Map(),assignmentIds=new Map(),credentials=[];
 for(const p of m.periods){const old=await one('SELECT id FROM periods WHERE year=? AND term=? ORDER BY rowid LIMIT 1',p.year,p.term);const key=`${p.year}:${p.term}`,id=old?.id||periodCache.get(key)||uid();periodIds.set(p.id,id);if(!old&&!periodCache.has(key))ops.push(stmt('INSERT INTO periods (id,owner_id,year,term) VALUES (?,?,?,?)',id,u.id,p.year,p.term));periodCache.set(key,id);}
 for(const s of m.students){const old=await one('SELECT id,role FROM users WHERE username=?',s.username);if(old&&old.role!=='student')fail(409,`รหัส ${s.username} เป็นบัญชีบุคลากร ไม่สามารถกู้คืน`);const id=old?.id||uid();studentIds.set(s.id,id);if(!old){const password=`Gr-${uid().slice(0,16)}`;ops.push(stmt("INSERT INTO users (id,username,name,role,password,active,must_change,created_at) VALUES (?,?,?,'student',?,1,1,?)",id,s.username,s.name,await hashPassword(password),now()));credentials.push({code:s.username,name:s.name,password});}}
 const suffix=j.id.slice(0,6);for(const c of m.courses){const id=uid();courseIds.set(c.id,id);ops.push(stmt('INSERT INTO courses (id,period_id,owner_id,code,name,classroom,work_weight,mid_weight,final_weight,published,archived,revision) VALUES (?,?,?,?,?,?,?,?,?,0,?,0)',id,periodIds.get(c.period_id),u.id,c.code.slice(0,15)+`~R${suffix}-${courseIds.size}`,c.name,c.classroom,c.work_weight,c.mid_weight,c.final_weight,c.archived?1:0));}
 for(const a of m.assignments){const id=uid();assignmentIds.set(a.id,id);ops.push(stmt('INSERT INTO assignments (id,course_id,title,description,max_score,due_at,rubric,created_at) VALUES (?,?,?,?,?,?,?,?)',id,courseIds.get(a.course_id),a.title,String(a.description||'').slice(0,10000),a.max_score,a.due_at,JSON.stringify(parseRubric(a.rubric)),a.created_at||now()));}
 for(const e of m.enrollments)ops.push(stmt('INSERT INTO enrollments (id,course_id,student_id,student_code,name,number,active,mid,final,special) VALUES (?,?,?,?,?,?,?,?,?,?)',uid(),courseIds.get(e.course_id),studentIds.get(e.student_id),e.student_code,e.name,e.number,e.active?1:0,e.mid,e.final,e.special));
 for(const s of m.submissions)ops.push(stmt('INSERT INTO submissions (id,assignment_id,student_id,note,submitted_at,score,feedback,status,revision,reviewed_at,rubric_scores,source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',uid(),assignmentIds.get(s.assignment_id),studentIds.get(s.student_id),String(s.note||'').slice(0,3000),s.submitted_at,s.score,String(s.feedback||'').slice(0,5000),s.status,s.revision,s.reviewed_at||null,s.rubric_scores,s.source));
 for(const f of m.files)ops.push(stmt('INSERT INTO files (id,course_id,assignment_id,student_id,revision,kind,name,mime,size,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',assetMap.get(`file:${f.id}`),courseIds.get(f.course_id),assignmentIds.get(f.assignment_id),f.student_id?studentIds.get(f.student_id):null,f.revision,f.kind,f.name,f.mime,f.size,f.created_at||now()));
 for(const x of m.extensions)ops.push(stmt('INSERT INTO extensions (id,assignment_id,student_id,due_at,note) VALUES (?,?,?,?,?)',uid(),assignmentIds.get(x.assignment_id),studentIds.get(x.student_id),x.due_at,String(x.note||'').slice(0,1000)));
 for(const p of m.profiles)ops.push(stmt('INSERT INTO sgs_profiles (id,owner_id,name,config,template_key,template_name,size,created_at) VALUES (?,?,?,?,?,?,?,?)',uid(),u.id,p.name+' (กู้คืน)',p.config,assetMap.get(`template:${p.id}`),p.template_name,p.size,now()));
 for(const a of m.audit)if(courseIds.has(a.course_id))ops.push(stmt('INSERT INTO audit (id,actor_id,course_id,action,detail,created_at) VALUES (?,?,?,?,?,?)',uid(),u.id,courseIds.get(a.course_id),'restored_history',JSON.stringify({originalActorId:a.actor_id,action:a.action,detail:a.detail,originalCreatedAt:a.created_at}),now()));
 ops.push(stmt("UPDATE restore_jobs SET status='complete' WHERE id=? AND status='staging'",j.id));try{await database().batch(ops);}catch{fail(409,'กู้คืนไม่สำเร็จ ไม่มีคะแนนหรือข้อมูลเดิมถูกแก้ไข');}await log(u.id,null,'restore',{jobId:j.id,courses:m.courses.length,files:m.assets.length});return {ok:true,courses:m.courses.length,files:m.assets.length,credentials};
}
