import {all,one,stmt,database,bucket,fail,uid,now,jsonBody,reply,string,log} from './server';
import {ownCourse,teacher,digest,type User} from './auth';
import {validateRestore,commitRestore} from './restore-server';
export function scopeBackup(m:any,id:string){
 m.courses=m.courses.filter((c:any)=>c.id===id);m.subjects=m.subjects.filter((s:any)=>m.courses.some((c:any)=>c.subject_id===s.id));m.periods=m.periods.filter((p:any)=>m.courses.some((c:any)=>c.period_id===p.id));m.assignments=m.assignments.filter((a:any)=>a.course_id===id);m.enrollments=m.enrollments.filter((e:any)=>e.course_id===id);m.submissions=m.submissions.filter((s:any)=>m.assignments.some((a:any)=>a.id===s.assignment_id));m.files=m.files.filter((f:any)=>f.course_id===id);m.students=m.students.filter((u:any)=>m.enrollments.some((e:any)=>e.student_id===u.id));m.extensions=m.extensions.filter((x:any)=>m.assignments.some((a:any)=>a.id===x.assignment_id));m.groups=(m.groups||[]).filter((g:any)=>m.assignments.some((a:any)=>a.id===g.assignment_id));m.groupMembers=(m.groupMembers||[]).filter((x:any)=>m.groups.some((g:any)=>g.id===x.group_id));m.exams=(m.exams||[]).filter((e:any)=>e.course_id===id);m.examAttempts=(m.examAttempts||[]).filter((a:any)=>m.exams.some((e:any)=>e.id===a.exam_id));m.examEvents=(m.examEvents||[]).filter((ev:any)=>m.examAttempts.some((a:any)=>a.id===ev.attempt_id));m.audit=(m.audit||[]).filter((a:any)=>a.course_id===id);m.attendanceSessions=(m.attendanceSessions||[]).filter((s:any)=>s.course_id===id);m.attendanceRecords=(m.attendanceRecords||[]).filter((r:any)=>m.attendanceSessions.some((s:any)=>s.id===r.session_id));m.followupNotes=(m.followupNotes||[]).filter((n:any)=>n.course_id===id);m.profiles=[];delete m.notificationReads;return m;
}
const hashBytes=async(bytes:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');
export async function snapshotCourse(u:User,courseId:string,kind='manual',daily=false){
 teacher(u);await ownCourse(u,courseId,true);const id=uid(),key='snapshots/'+id+'/manifest.json',day=daily?new Date(Date.now()+7*3600000).toISOString().slice(0,10):null;
 if(daily){const prior=await one('SELECT * FROM backup_snapshots WHERE owner_id=? AND course_id=? AND day=?',u.id,courseId,day);if(prior?.status==='complete'||prior?.status==='building'&&Date.now()-new Date(prior.created_at).getTime()<600000)return prior!.id;if(prior)await stmt('UPDATE backup_snapshots SET day=NULL,status=\'failed\',error=\'สร้างชุดสำรองไม่ครบ กรุณาลองใหม่\' WHERE id=?',prior.id).run();}
 try{await stmt('INSERT INTO backup_snapshots(id,owner_id,course_id,kind,status,manifest_key,day,created_at) VALUES(?,?,?,?,?,?,?,?)',id,u.id,courseId,kind,'building',key,day,now()).run();}catch{if(daily)return (await one('SELECT id FROM backup_snapshots WHERE owner_id=? AND course_id=? AND day=?',u.id,courseId,day))?.id;throw Error('สร้างจุดกู้คืนไม่ได้');}
 const copied:string[]=[];try{const {extendedRoute}=await import('./extended-server');const response=await extendedRoute(new Request('https://grade.internal/api/backup'),u,'backup','GET');const m=scopeBackup(await response!.json(),courseId);if(m.files.reduce((n:number,f:any)=>n+f.size,0)>250*1024*1024)fail(413,'ชุดสำรองเกิน 250 MB กรุณาดาวน์โหลดแยกเองก่อนทำรายการ');m.assets=[];let size=0;
  for(const f of m.files){const object=await bucket().get(f.id);if(!object)fail(409,'ไฟล์งานไม่ครบ ไม่สร้างชุดสำรองที่ขาดไฟล์');const bytes=await object.arrayBuffer();if(bytes.byteLength!==f.size)fail(409,'ขนาดไฟล์งานไม่ตรง');const aid=uid(),objectKey='snapshots/'+id+'/'+aid;await bucket().put(objectKey,bytes,{httpMetadata:{contentType:f.mime}});copied.push(objectKey);m.assets.push({id:aid,kind:'file',referenceId:f.id,size:f.size,mime:f.mime,sha256:await hashBytes(bytes)});size+=f.size;}
  validateRestore(m);const current=await one('SELECT revision FROM courses WHERE id=?',courseId);if(current?.revision!==m.courses[0]?.revision)fail(409,'ข้อมูลเปลี่ยนระหว่างสำรอง กรุณาลองใหม่');await bucket().put(key,JSON.stringify(m),{httpMetadata:{contentType:'application/json'}});copied.push(key);await stmt('UPDATE backup_snapshots SET status=\'complete\',size=? WHERE id=?',size,id).run();return id;
 }catch(err){await Promise.all(copied.map(k=>bucket().delete(k)));await stmt('UPDATE backup_snapshots SET status=\'failed\',error=?,day=NULL WHERE id=?',String((err as Error).message).slice(0,300),id).run();throw err;}
}
async function access(u:User,id:string){teacher(u);const s=await one('SELECT * FROM backup_snapshots WHERE id=? AND owner_id=?',id,u.id);if(!s)fail(404,'ไม่พบจุดกู้คืนหรือไม่มีสิทธิ์');await ownCourse(u,s!.course_id);if(s!.status!=='complete')fail(409,'จุดกู้คืนยังไม่พร้อม');return s!;}
export async function snapshotsRoute(r:Request,u:User,path:string,method:string):Promise<Response|null>{
 if(path==='snapshots'&&method==='GET'){teacher(u);const rows=await all('SELECT * FROM backup_snapshots WHERE owner_id=? ORDER BY created_at DESC LIMIT 100',u.id),visible=[];for(const row of rows){try{await ownCourse(u,row.course_id);visible.push(row);}catch{}}return reply({snapshots:visible,automatic:await one('SELECT value FROM settings WHERE key=?','backup-auto:'+u.id)});}
 if(path==='snapshots'&&method==='POST'){const b=await jsonBody(r);return reply({id:await snapshotCourse(u,string(b.courseId,'วิชา'))},201);}
 if(path==='snapshots/automatic'&&method==='POST'){teacher(u);const b=await jsonBody(r);await stmt('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','backup-auto:'+u.id,b.enabled===true?'1':'0').run();return reply({ok:true});}
 if(path==='snapshots/daily'&&method==='POST'){teacher(u);const setting=await one('SELECT value FROM settings WHERE key=?','backup-auto:'+u.id);if(setting?.value==='0')return reply({ids:[]});const {getState}=await import('./state'),state=await getState(u),ids=[];for(const c of state.courses.filter(c=>c.can_edit&&!c.archived))ids.push(await snapshotCourse(u,c.id,'daily',true));return reply({ids});}
 const match=path.match(/^snapshots\/([^/]+)(?:\/(asset|restore))?$/);if(!match)return null;
 if(method==='GET'){const s=await access(u,match[1]);if(match[2]==='asset'){const aid=new URL(r.url).searchParams.get('id');const m=await bucket().get(s.manifest_key);if(!m)fail(404,'ไม่พบชุดสำรอง');const manifest=await m!.json<any>();const a=manifest.assets.find((a:any)=>a.id===aid);if(!a)fail(404,'ไม่พบไฟล์ในชุดสำรอง');const object=await bucket().get('snapshots/'+s.id+'/'+a.id);if(!object)fail(404,'ไฟล์สำรองไม่ครบ');return new Response(object.body,{headers:{'Content-Type':a.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}const object=await bucket().get(s.manifest_key);if(!object)fail(404,'ไม่พบชุดสำรอง');return reply(await object!.json());}
 if(method==='POST'&&match[2]==='restore'){const s=await access(u,match[1]);await ownCourse(u,s.course_id,true);const object=await bucket().get(s.manifest_key);if(!object)fail(404,'ไม่พบชุดสำรอง');const m=validateRestore(await object!.json()),id=uid(),copied:string[]=[];await stmt('INSERT INTO restore_jobs(id,owner_id,manifest,status,created_at) VALUES(?,?,?,?,?)',id,u.id,JSON.stringify(m),'staging',now()).run();try{for(const a of m.assets){const o=await bucket().get('snapshots/'+s.id+'/'+a.id);if(!o)fail(409,'ไฟล์สำรองไม่ครบ');const bytes=await o.arrayBuffer();if(bytes.byteLength!==a.size||await hashBytes(bytes)!==a.sha256)fail(409,'ไฟล์สำรองเสียหาย');const key=uid();await bucket().put(key,bytes,{httpMetadata:{contentType:a.mime}});copied.push(key);await stmt('INSERT INTO restore_assets(id,job_id,asset_id,object_key,sha256,size) VALUES(?,?,?,?,?,?)',uid(),id,a.id,key,a.sha256,a.size).run();}const result=await commitRestore(u,{id,manifest:JSON.stringify(m)});await log(u.id,s.course_id,'snapshot_restore',{snapshotId:s.id});return reply(result,201);}catch(e){await Promise.all(copied.map(k=>bucket().delete(k)));await stmt('UPDATE restore_jobs SET status=\'cancelled\' WHERE id=?',id).run();throw e;}}
 return null;
}
