import {calculateGrade,workBudgets,workPhase,phaseLabel} from './grades';
export const attendanceLabels:Record<string,string>={present:'มา',absent:'ขาด',leave:'ลา',late:'สาย'};
const round=(v:number)=>Math.round(v*100)/100;
export function attendanceSummary(sessions:any[],records:any[],courseId:string,studentId:string){
 const live=sessions.filter(s=>s.course_id===courseId&&!s.deleted),own=records.filter(r=>r.student_id===studentId&&live.some(s=>s.id===r.session_id));
 const scheduled=live.reduce((n,s)=>n+Number(s.hours),0),hours=own.reduce((n,r)=>n+Number(r.hours),0),unmarked=live.filter(s=>!own.some(r=>r.session_id===s.id)).length;
 return {sessions:live.length,scheduled:round(scheduled),hours:round(hours),percent:scheduled?round(hours/scheduled*100):0,unmarked,...Object.fromEntries(Object.keys(attendanceLabels).map(k=>[k,own.filter(r=>r.status===k).length]))};
}
export function scorePlan(course:any,tasks:any[]){const budgets=workBudgets(course);return ['before','after'].map(phase=>{const max=round(tasks.filter(a=>a.course_id===course.id&&workPhase(a)===phase).reduce((n,a)=>n+Number(a.max_score),0));return {phase,label:phaseLabel(phase,course),max,budget:budgets[phase as 'before'|'after'],remaining:round(budgets[phase as 'before'|'after']-max)};});}
export function publicationCheck(state:any,course:any){const enrolls=state.enrollments.filter((e:any)=>e.course_id===course.id&&e.active),plan=scorePlan(course,state.assignments),grades=enrolls.map((e:any)=>({enrollment:e,grade:calculateGrade(course,state.assignments,state.submissions,e)}));return {plan,unallocated:round(plan.reduce((n,p)=>n+Math.max(0,p.remaining),0)),over:plan.filter(p=>p.remaining<0),incomplete:grades.filter((x:any)=>!x.grade.complete),missing:grades.reduce((n:number,x:any)=>n+x.grade.missing,0),pending:grades.reduce((n:number,x:any)=>n+x.grade.pending,0),students:enrolls.length};}
export function parseScorePaste(text:string,roster:any[],course:any){
 const seen=new Set<string>();return text.split(/\r?\n/).filter(l=>l.trim()).map((l,index)=>{const cols=l.includes('\t')?l.split('\t'):l.split(',');const code=cols[0]?.trim()||'',e=roster.find(e=>e.student_code===code),errors:string[]=[];if(!e)errors.push('ไม่พบรหัสในห้องนี้');if(seen.has(code))errors.push('รหัสซ้ำ');seen.add(code);if(cols.length<2||cols.length>3)errors.push('ต้องมีรหัส ตามด้วยกลางภาค และ/หรือปลายภาค');const row:any={code,enrollmentId:e?.id,name:e?.name||'',line:index+1,errors};for(const [i,k] of ['mid','final'].entries()){const v=cols[i+1]?.trim();if(v===undefined||v==='')continue;if(v==='-'){row[k]=null;continue;}const n=Number(v);if(!Number.isFinite(n)||n<0||n>Number(course[k+'_weight']))errors.push(`${k==='mid'?'กลางภาค':'ปลายภาค'}เกินช่วงคะแนน`);else row[k]=n;}if(!('mid' in row)&&!('final' in row))errors.push('ไม่มีคะแนนที่จะบันทึก');return row;});
}
export function historyText(action:string,d:any):string{if(action==='restored_history'){let detail=d.detail;try{if(typeof detail==='string')detail=JSON.parse(detail);}catch{}return 'กู้คืนประวัติ: '+historyText(d.action,detail||{});}if(d.before&&(action==='review'||action==='exam_scores')){const fields=action==='review'?['score']:['mid','final','special'];return fields.filter(k=>k in d).map(k=>`${({score:'คะแนนงาน',mid:'กลางภาค',final:'ปลายภาค',special:'สถานะ'} as any)[k]} ${d.before[k]??'ว่าง'} → ${d[k]??'ว่าง'}`).join(' · ')+(d.feedback?' · '+d.feedback:'');}if(action==='review')return `ให้คะแนน ${d.score??'ส่งคืนแก้ไข'}${d.feedback?' · '+d.feedback:''}`;if(action==='bulk_scores')return `บันทึกคะแนน ${d.count} คน · ${d.reason}`;if(action==='attendance')return `เช็กชื่อ ${d.count} คน · ${d.title}`;if(action==='group_managed')return `ปรับสมาชิก/หัวหน้ากลุ่ม · ${d.reason}`;if(action==='individual_score')return `คะแนนส่วนบุคคล ${d.before??'ว่าง'} → ${d.score} · ${d.reason}`;if(action==='publication')return d.published?'เผยแพร่ผลการเรียน':'ถอนผลการเรียน';if(action==='followup_note')return `บันทึกการติดตาม · ${d.text||d.status||''}`;return Object.entries(d||{}).filter(([k,v])=>!k.toLowerCase().includes('id')&&['string','number','boolean'].includes(typeof v)).map(([k,v])=>`${k}: ${v}`).join(' · ')||'เปิดรายละเอียดเพิ่มเติม';}
export function notifications(state:any,time=Date.now()){
 const student=state.user.role==='student',out:any[]=[],add=(key:string,title:string,text:string,courseId:string,view:string,urgent=false)=>out.push({key,title,text,courseId,view,urgent});
 for(const c of state.courses.filter((c:any)=>!c.archived)){const tasks=state.assignments.filter((a:any)=>a.course_id===c.id);if(student){for(const a of tasks){const s=state.submissions.find((s:any)=>s.assignment_id===a.id&&s.student_id===state.user.id),extension=state.extensions.find((x:any)=>x.assignment_id===a.id&&x.student_id===state.user.id),due=new Date(extension?.due_at||a.due_at).getTime();if(!s){if(time-new Date(a.created_at).getTime()<7*86400000)add('new:'+a.id,'งานใหม่',a.title,c.id,'courses');if(due-time<2*86400000)add('due:'+a.id+':'+due,due<time?'งานเลยกำหนด':'ใกล้กำหนดส่ง',a.title,c.id,'courses',true);}else if(s.status==='returned')add('return:'+s.id+':'+s.reviewed_at,'ครูส่งคืนให้แก้ไข',a.title,c.id,'courses',true);else if(s.status==='graded')add('grade:'+s.id+':'+s.reviewed_at,'ตรวจงานแล้ว',a.title,c.id,'courses');}if(c.published)add('results:'+c.id+':'+c.revision,'เผยแพร่ผลการเรียนแล้ว',c.name,c.id,'results');}
 else {const pending=state.submissions.filter((s:any)=>s.status==='pending'&&tasks.some((a:any)=>a.id===s.assignment_id)),units=new Set(pending.map((s:any)=>s.group_id||s.id));if(units.size)add('review:'+c.id+':'+pending.map((s:any)=>s.id+':'+s.revision).sort().join('|'),'งานรอตรวจ',`${c.name} ${c.classroom} · ${units.size} งาน/กลุ่ม`,c.id,'review',true);const overdue=state.enrollments.filter((e:any)=>e.course_id===c.id&&e.active).reduce((n:number,e:any)=>n+tasks.filter((a:any)=>{const ext=state.extensions.find((x:any)=>x.assignment_id===a.id&&x.student_id===e.student_id);return new Date(ext?.due_at||a.due_at).getTime()<time&&!state.submissions.some((s:any)=>s.assignment_id===a.id&&s.student_id===e.student_id);}).length,0);if(overdue)add('overdue:'+c.id+':'+new Date(time+7*3600000).toISOString().slice(0,10),'งานเลยกำหนดที่ต้องติดตาม',`${c.name} ${c.classroom} · ${overdue} รายการ`,c.id,'followup',true);for(const n of (state.followupNotes||[]).filter((n:any)=>n.course_id===c.id&&!n.deleted&&n.status==='open'&&n.next_date&&n.next_date<=new Date(time+7*3600000).toISOString().slice(0,10)))add('followup:'+n.id+':'+n.revision,'ถึงวันนัดติดตาม',n.text,c.id,'cases',true);}}
 const read=new Set((state.notificationReads||[]).map((x:any)=>x.key));return out.map(x=>({...x,read:read.has(x.key)})).sort((a,b)=>Number(b.urgent)-Number(a.urgent));
}
