import {all,one,stmt,database,fail,uid,now,jsonBody,reply,string,number,integer,requireLive,log} from './server';
import {ownCourse,teacher,type User} from './auth';
import {getState} from './state';
import {publicationCheck,attendanceLabels} from './teacher-logic';
import {snapshotCourse} from './snapshots-server';
import {validateQuestions} from './exam-server';
async function writable(u:User,id:string){teacher(u);const c=await ownCourse(u,string(id,'วิชา'),true);if(c.archived)fail(409,'รายวิชาเก็บเป็นประวัติแล้ว');return c;}
async function enrolled(u:User,c:any,id:string){await requireLive('student',id);const e=await one('SELECT * FROM enrollments WHERE course_id=? AND student_id=? AND active=1 AND deleted=0',c.id,id);if(!e)fail(404,'นักเรียนไม่ได้ลงทะเบียนในห้องนี้');await requireLive('enrollment',e!.id);return e!;}
export async function courseMutation(c:any,build:(guard:string,args:any[])=>D1PreparedStatement[],expected=c.revision,extra='1=1',extraArgs:any[]=[]){const token=uid(),guard='EXISTS(SELECT 1 FROM courses WHERE id=? AND mutation_token=?)',args=[c.id,token];const res=await database().batch([stmt("UPDATE courses SET mutation_token=?,published=0,grading_mode='points',revision=revision+1 WHERE id=? AND revision=? AND archived=0 AND deleted=0 AND "+extra,token,c.id,expected,...extraArgs),...build(guard,args)]);if(!res[0].meta.changes)fail(409,'ข้อมูลเปลี่ยนแล้ว กรุณาโหลดใหม่ก่อนบันทึก');return res;}
const checkedDate=(v:unknown,optional=false)=>{if(optional&&v==='')return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(new Date(v+'T00:00:00Z').getTime())||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)fail(400,'วันที่ไม่ถูกต้อง');return v;};
export async function teacherRoute(r:Request,u:User,path:string,method:string):Promise<Response|null>{
 const manage=path.match(/^manage-groups\/([^/]+)$/);if(manage&&method==='POST'){
  const b=await jsonBody(r);await requireLive('assignment',manage[1]);const a=await one('SELECT * FROM assignments WHERE id=?',manage[1]);if(!a?.is_group)fail(404,'ไม่พบงานกลุ่ม');const c=await writable(u,a.course_id),reason=string(b.reason,'เหตุผลการปรับกลุ่ม',300),old=await all('SELECT * FROM work_groups WHERE assignment_id=?',a.id),members=await all('SELECT * FROM group_members WHERE assignment_id=?',a.id),subs=await all('SELECT * FROM submissions WHERE assignment_id=? AND deleted=0',a.id),seen=new Set<string>(),ids=new Set<string>();
  if(!Array.isArray(b.groups)||b.groups.length>100)fail(400,'รายการกลุ่มไม่ถูกต้อง');const groups:any[]=[];for(const raw of b.groups){const existing=raw.id?old.find(g=>g.id===raw.id):null;if(raw.id&&!existing||existing&&raw.revision!==existing.revision)fail(409,'กลุ่มเปลี่ยนแล้ว กรุณาโหลดใหม่');const id=existing?.id||uid();if(ids.has(id)||!Array.isArray(raw.memberIds)||!raw.memberIds.length||raw.memberIds.length>a.group_max)fail(400,'กลุ่มซ้ำ สมาชิกว่าง หรือเกินขนาด');ids.add(id);for(const student of raw.memberIds){if(seen.has(student))fail(400,'นักเรียนอยู่หลายกลุ่ม');seen.add(student);await enrolled(u,c,student);}if(!raw.memberIds.includes(raw.leaderId))fail(400,'หัวหน้าต้องอยู่ในกลุ่ม');groups.push({id,name:string(raw.name,'ชื่อกลุ่ม',80),leader:raw.leaderId,members:raw.memberIds,old:existing});}
  const target=new Map<string,string>(groups.flatMap(g=>g.members.map((s:string)=>[s,g.id] as [string,string]))),affected=new Set<string>();for(const m of members)if(target.get(m.student_id)!==m.group_id){affected.add(m.group_id);if(target.get(m.student_id))affected.add(target.get(m.student_id)!);}for(const [s,g] of target)if(!members.some(m=>m.student_id===s&&m.group_id===g))affected.add(g);
  const changedSubs=subs.filter(s=>s.group_id&&affected.has(s.group_id)||target.get(s.student_id)!==s.group_id&&target.has(s.student_id));if(changedSubs.length&&!b.resetAffected)fail(409,'มีงานส่งแล้ว ต้องยืนยันส่งคืนงานและล้างคะแนนของกลุ่มที่ได้รับผลกระทบ');if(changedSubs.some(s=>s.deleted)||await one('SELECT id FROM submissions WHERE assignment_id=? AND deleted=1',a.id))fail(409,'มีงานในถังขยะ กรุณากู้คืนก่อนปรับกลุ่ม');
  await snapshotCourse(u,c.id,'before_groups');const stamp=now(),revision=Math.max(0,...subs.map(s=>s.revision))+1,extra='(SELECT COUNT(*) FROM work_groups WHERE assignment_id=?)=?'+old.map(()=> ' AND EXISTS(SELECT 1 FROM work_groups WHERE id=? AND revision=?)').join(''),extraArgs=[a.id,old.length,...old.flatMap(g=>[g.id,g.revision])];
  await courseMutation(c,(guard,args)=>{
   const ops:D1PreparedStatement[]=[];for(const g of groups){ops.push(g.old?stmt(`UPDATE work_groups SET name=?,leader_id=?,member_count=?,revision=revision+1,submission_token=NULL WHERE id=? AND ${guard}`,g.name,g.leader,g.members.length,g.id,...args):stmt(`INSERT INTO work_groups(id,assignment_id,name,leader_id,member_count,created_at) SELECT ?,?,?,?,?,? WHERE ${guard}`,g.id,a.id,g.name,g.leader,g.members.length,stamp,...args));}
   ops.push(stmt(`DELETE FROM group_members WHERE assignment_id=? AND ${guard}`,a.id,...args));for(const g of groups)for(const s of g.members)ops.push(stmt(`INSERT INTO group_members(group_id,assignment_id,student_id) SELECT ?,?,? WHERE ${guard}`,g.id,a.id,s,...args));
   const resetStudents=new Set<string>(changedSubs.map(s=>s.student_id));for(const g of groups)if(affected.has(g.id)&&changedSubs.length)for(const s of g.members)resetStudents.add(s);
   for(const s of resetStudents){const prev=subs.find(x=>x.student_id===s),groupId=target.get(s)||null;ops.push(prev?stmt(`UPDATE submissions SET group_id=?,status='returned',score=NULL,individual_score=NULL,rubric_scores='[]',feedback=?,reviewed_at=?,revision=? WHERE id=? AND ${guard}`,groupId,'ครูปรับกลุ่ม กรุณาส่งงานรอบใหม่: '+reason,stamp,revision,prev.id,...args):stmt(`INSERT INTO submissions(id,assignment_id,student_id,group_id,status,note,submitted_at,revision,feedback) SELECT ?,?,?,?,'returned','',?,?,? WHERE ${guard}`,uid(),a.id,s,groupId,stamp,revision,'ครูปรับกลุ่ม กรุณาส่งงานรอบใหม่: '+reason,...args));}
   for(const g of old.filter(g=>!ids.has(g.id))){ops.push(stmt(`UPDATE submissions SET group_id=NULL WHERE group_id=? AND ${guard}`,g.id,...args),stmt(`DELETE FROM work_groups WHERE id=? AND ${guard}`,g.id,...args));}return ops;
  },integer(b.courseRevision,'รุ่นวิชา',0,1e9),extra,extraArgs);await log(u.id,c.id,'group_managed',{assignmentId:a.id,reason,reset:changedSubs.length>0,before:members,groups});return reply({ok:true});
 }
 if(path==='individual-score'&&method==='POST'){const b=await jsonBody(r),s=await one('SELECT * FROM submissions WHERE id=? AND deleted=0',b.submissionId);if(!s)fail(404,'ไม่พบงานส่ง');await requireLive('submission',s!.id);await requireLive('assignment',s!.assignment_id);const a=(await one('SELECT * FROM assignments WHERE id=?',s!.assignment_id))!,c=await writable(u,a.course_id);if(!a.is_group||!a.individual_weight||s!.status!=='graded')fail(409,'ให้ตรวจคะแนนกลุ่มก่อนคะแนนรายบุคคล');await enrolled(u,c,s!.student_id);const score=number(b.score,'คะแนนส่วนบุคคล',0,a.max_score*a.individual_weight/100),reason=string(b.reason,'เหตุผล',300);if(b.revision!==s!.revision||b.expectedScore!==s!.individual_score)fail(409,'คะแนนเปลี่ยนแล้ว');await snapshotCourse(u,c.id,'before_individual');const extra='EXISTS(SELECT 1 FROM submissions WHERE id=? AND revision=? AND individual_score IS ? AND status=\'graded\')';await courseMutation(c,(guard,args)=>[stmt(`UPDATE submissions SET individual_score=? WHERE id=? AND ${guard}`,score,s!.id,...args)],c.revision,extra,[s!.id,s!.revision,s!.individual_score]);await log(u.id,c.id,'individual_score',{studentId:s!.student_id,assignmentId:a.id,before:s!.individual_score,score,reason});return reply({ok:true});}
 const check=path.match(/^publication-check\/([^/]+)$/);if(check&&method==='GET'){teacher(u);const c=await ownCourse(u,check[1]);return reply(publicationCheck(await getState(u),c));}
 if(path==='bulk-scores'&&method==='POST'){
  const b=await jsonBody(r),c=await writable(u,b.courseId);if(c.course_type==='activity')fail(409,'วิชากิจกรรมไม่มีคะแนนสอบ');if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100)fail(400,'บันทึกครั้งละ 1–100 คน');integer(b.revision,'รุ่นข้อมูล',0,1e9);const reason=string(b.reason,'เหตุผล',300),state=await getState(u),seen=new Set(),changes:any[]=[];
  for(const row of b.rows){const e=state.enrollments.find(e=>e.id===row.enrollmentId&&e.course_id===c.id&&e.active);if(!e||seen.has(e.id))fail(400,'รหัสนักเรียนไม่ตรงห้องหรือซ้ำ');seen.add(e.id);const values:any={};for(const k of ['mid','final'])if(k in row)values[k]=row[k]===null?null:number(row[k],k==='mid'?'กลางภาค':'ปลายภาค',0,c[k+'_weight']);if(!Object.keys(values).length)fail(400,'ไม่มีคะแนนที่จะบันทึก');changes.push({e,values});}
  if(b.revision!==c.revision)fail(409,'คะแนนเปลี่ยนแล้ว กรุณาโหลดใหม่');await snapshotCourse(u,c.id,'before_scores');
  await courseMutation(c,(guard,args)=>changes.map(({e,values})=>stmt(`UPDATE enrollments SET ${Object.keys(values).map(k=>k+'=?').join(',')} WHERE id=? AND ${guard}`,...Object.values(values),e.id,...args)),b.revision);
  await log(u.id,c.id,'bulk_scores',{count:changes.length,reason,changes:changes.map(({e,values})=>({studentId:e.student_id,name:e.name,before:{mid:e.mid,final:e.final},...values}))});return reply({ok:true,count:changes.length});
 }
 if(path==='attendance'&&method==='POST'){const b=await jsonBody(r),c=await writable(u,b.courseId),id=uid(),date=checkedDate(b.date),title=string(b.title,'ชื่อคาบ/กิจกรรม',150),hours=number(b.hours,'ชั่วโมง',.01,24);await courseMutation(c,(guard,args)=>[stmt(`INSERT INTO attendance_sessions(id,course_id,date,title,hours,created_at) SELECT ?,?,?,?,?,? WHERE ${guard}`,id,c.id,date,title,hours,now(),...args)]);return reply({id},201);}
 const at=path.match(/^attendance\/([^/]+)$/);if(at&&method==='PATCH'){
  const b=await jsonBody(r),s=await one('SELECT * FROM attendance_sessions WHERE id=?',at[1]);if(!s)fail(404,'ไม่พบคาบ');const c=await writable(u,s!.course_id);integer(b.revision,'รุ่นคาบ',0,1e9);if(b.revision!==s!.revision)fail(409,'คาบเปลี่ยนแล้ว กรุณาโหลดใหม่');
  if(typeof b.deleted==='boolean'){await snapshotCourse(u,c.id,'before_attendance');await courseMutation(c,(guard,args)=>[stmt(`UPDATE attendance_sessions SET deleted=?,revision=revision+1 WHERE id=? AND revision=? AND ${guard}`,b.deleted?1:0,s!.id,b.revision,...args)]);return reply({ok:true});}
  if(s!.deleted)fail(409,'คาบอยู่ในถังขยะ');
  if(b.rows===undefined){const date=checkedDate(b.date),title=string(b.title,'ชื่อคาบ',150),hours=number(b.hours,'ชั่วโมง',.01,24);if(await one('SELECT id FROM attendance_records WHERE session_id=? AND hours>?',s!.id,hours))fail(409,'ชั่วโมงที่รับรองเดิมเกินจำนวนใหม่ ให้แก้ชั่วโมงนักเรียนก่อนลดชั่วโมงคาบ');await snapshotCourse(u,c.id,'before_attendance');await courseMutation(c,(guard,args)=>[stmt('UPDATE attendance_sessions SET date=?,title=?,hours=?,revision=revision+1 WHERE id=? AND revision=? AND '+guard,date,title,hours,s!.id,b.revision,...args)]);await log(u.id,c.id,'attendance_edited',{sessionId:s!.id,before:{date:s!.date,title:s!.title,hours:s!.hours},date,title,hours});return reply({ok:true});}
  if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100)fail(400,'เช็กชื่อครั้งละ 1–100 คน');const seen=new Set(),rows:any[]=[];for(const x of b.rows){if(seen.has(x.studentId)||!Object.hasOwn(attendanceLabels,x.status))fail(400,'สถานะเช็กชื่อซ้ำหรือไม่ถูกต้อง');seen.add(x.studentId);await enrolled(u,c,x.studentId);const hours=number(x.hours,'ชั่วโมงเข้าร่วม',0,s!.hours);if(['absent','leave'].includes(x.status)&&hours!==0)fail(400,'ขาดหรือลาใช้ชั่วโมง 0');rows.push({...x,hours,note:String(x.note||'').slice(0,1000)});}
  await snapshotCourse(u,c.id,'before_attendance');await courseMutation(c,(guard,args)=>[stmt(`UPDATE attendance_sessions SET revision=revision+1 WHERE id=? AND revision=? AND ${guard}`,s!.id,b.revision,...args),...rows.map(x=>stmt(`INSERT INTO attendance_records(id,session_id,student_id,status,hours,note,updated_at) SELECT ?,?,?,?,?,?,? WHERE ${guard} ON CONFLICT(session_id,student_id) DO UPDATE SET status=excluded.status,hours=excluded.hours,note=excluded.note,updated_at=excluded.updated_at`,uid(),s!.id,x.studentId,x.status,x.hours,x.note,now(),...args))]);await log(u.id,c.id,'attendance',{sessionId:s!.id,title:s!.title,count:rows.length});return reply({ok:true});
 }
 if(path==='activity-policy'&&method==='POST'){const b=await jsonBody(r),c=await writable(u,b.courseId);if(c.course_type!=='activity')fail(409,'ใช้เกณฑ์เข้าร่วมเฉพาะวิชากิจกรรม');const min=number(b.attendanceMin,'ร้อยละเข้าร่วม'),hours=number(b.requiredHours,'ชั่วโมงที่ต้องผ่าน',0,1000);await snapshotCourse(u,c.id,'before_policy');await courseMutation(c,(guard,args)=>[stmt(`UPDATE courses SET attendance_min=?,required_hours=? WHERE id=? AND ${guard}`,min,hours,c.id,...args)]);await log(u.id,c.id,'activity_policy',{attendanceMin:min,requiredHours:hours});return reply({ok:true});}
 if(path==='followup-notes'&&method==='POST'){const b=await jsonBody(r),c=await writable(u,b.courseId);await enrolled(u,c,b.studentId);const text=string(b.text,'บันทึก',3000),date=checkedDate(b.nextDate||'',true),id=uid();await stmt('INSERT INTO followup_notes(id,course_id,student_id,actor_id,text,next_date,created_at) VALUES(?,?,?,?,?,?,?)',id,c.id,b.studentId,u.id,text,date,now()).run();await log(u.id,c.id,'followup_note',{studentId:b.studentId,text});return reply({id},201);}
 const note=path.match(/^followup-notes\/([^/]+)$/);if(note&&method==='PATCH'){const b=await jsonBody(r),n=await one('SELECT * FROM followup_notes WHERE id=?',note[1]);if(!n)fail(404,'ไม่พบบันทึก');const c=await writable(u,n!.course_id);if(!['open','done'].includes(b.status??n!.status))fail(400,'สถานะไม่ถูกต้อง');const res=await stmt('UPDATE followup_notes SET text=?,next_date=?,status=?,deleted=?,revision=revision+1 WHERE id=? AND revision=?',string(b.text??n!.text,'บันทึก',3000),checkedDate(b.nextDate??n!.next_date,true),b.status??n!.status,typeof b.deleted==='boolean'?Number(b.deleted):n!.deleted,n!.id,integer(b.revision,'รุ่นบันทึก',0,1e9)).run();if(!res.meta.changes)fail(409,'บันทึกเปลี่ยนแล้ว กรุณาโหลดใหม่');await log(u.id,c.id,'followup_note',{studentId:n!.student_id,status:b.status,text:b.text});return reply({ok:true});}
 if(path==='notification-read'&&method==='POST'){const b=await jsonBody(r);if(!Array.isArray(b.keys)||b.keys.length>100)fail(400,'แจ้งเตือนไม่ถูกต้อง');if(!b.keys.length)return reply({ok:true});await database().batch(b.keys.map((k:any)=>stmt('INSERT INTO notification_reads(user_id,key,read_at) VALUES(?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET read_at=excluded.read_at',u.id,string(k,'แจ้งเตือน',20000),now())));return reply({ok:true});}
 if(path==='question-banks'&&method==='GET'){teacher(u);return reply({banks:await all('SELECT * FROM question_banks WHERE owner_id=? ORDER BY created_at DESC',u.id)});}
 if(path==='question-banks'&&method==='POST'){teacher(u);const b=await jsonBody(r),max=Array.isArray(b.questions)?b.questions.reduce((n:number,q:any)=>n+Number(q.points),0):0;number(max,'คะแนนรวม',.01,1000);const qs=validateQuestions(b.questions,max),id=uid();await stmt('INSERT INTO question_banks(id,owner_id,name,tags,questions,created_at) VALUES(?,?,?,?,?,?)',id,u.id,string(b.name,'ชื่อคลัง',150),String(b.tags||'').slice(0,300),JSON.stringify(qs),now()).run();return reply({id},201);}
 const bank=path.match(/^question-banks\/([^/]+)$/);if(bank&&method==='PATCH'){teacher(u);const b=await jsonBody(r),old=await one('SELECT * FROM question_banks WHERE id=? AND owner_id=?',bank[1],u.id);if(!old)fail(404,'ไม่พบคลัง');let questions=old!.questions;if(b.questions!==undefined){const max=Array.isArray(b.questions)?b.questions.reduce((n:number,q:any)=>n+Number(q.points),0):0;number(max,'คะแนนรวม',.01,1000);questions=JSON.stringify(validateQuestions(b.questions,max));}const res=await stmt('UPDATE question_banks SET name=?,tags=?,deleted=?,questions=?,revision=revision+1 WHERE id=? AND owner_id=? AND revision=?',string(b.name,'ชื่อคลัง',150),String(b.tags||'').slice(0,300),Number(b.deleted===true),questions,bank[1],u.id,integer(b.revision,'รุ่นคลัง',0,1e9)).run();if(!res.meta.changes)fail(409,'คลังเปลี่ยนแล้วหรือไม่มีสิทธิ์');return reply({ok:true});}
 return null;
}
