import {sql} from 'drizzle-orm';
import { sqliteTable, text, integer, real, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const users = sqliteTable('users', {
 id:text('id').primaryKey(), username:text('username').notNull().unique(), name:text('name').notNull(), role:text('role').notNull(), password:text('password').notNull(), active:integer('active').notNull().default(1), mustChange:integer('must_change').notNull().default(0), createdAt:text('created_at').notNull()
});
export const settings = sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const sessions = sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const loginLimits = sqliteTable('login_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const periods=sqliteTable('periods',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),year:integer('year').notNull(),term:integer('term').notNull()},t=>[uniqueIndex('period_owner_year_term').on(t.ownerId,t.year,t.term).where(sql`${t.deleted}=0`)]);
export const subjects=sqliteTable('subjects',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),periodId:text('period_id').notNull().references(()=>periods.id),ownerId:text('owner_id').notNull().references(()=>users.id),code:text('code').notNull(),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('subject_scope').on(t.ownerId,t.periodId,t.code).where(sql`${t.deleted}=0`)]);
export const courses=sqliteTable('courses',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),subjectId:text('subject_id').references(()=>subjects.id),periodId:text('period_id').notNull().references(()=>periods.id),ownerId:text('owner_id').notNull().references(()=>users.id),code:text('code').notNull(),name:text('name').notNull(),classroom:text('classroom').notNull(),courseType:text('course_type').notNull().default('academic'),passThreshold:real('pass_threshold').notNull().default(50),attendanceMin:real('attendance_min').notNull().default(0),requiredHours:real('required_hours').notNull().default(0),mutationToken:text('mutation_token'),beforeWorkWeight:real('before_work_weight'),gradingMode:text('grading_mode').notNull().default('weighted'),workWeight:real('work_weight').notNull().default(60),midWeight:real('mid_weight').notNull().default(20),finalWeight:real('final_weight').notNull().default(20),published:integer('published').notNull().default(0),archived:integer('archived').notNull().default(0),revision:integer('revision').notNull().default(0)},t=>[uniqueIndex('course_scope').on(t.periodId,t.code,t.classroom).where(sql`${t.deleted}=0`),index('course_owner').on(t.ownerId)]);
export const enrollments=sqliteTable('enrollments',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),studentId:text('student_id').notNull().references(()=>users.id),studentCode:text('student_code').notNull(),name:text('name').notNull(),number:integer('number').notNull(),active:integer('active').notNull().default(1),mid:real('mid'),final:real('final'),special:text('special').notNull().default('')},t=>[uniqueIndex('enrollment_course_student').on(t.courseId,t.studentId).where(sql`${t.deleted}=0`),index('enrollment_student').on(t.studentId)]);
export const assignments=sqliteTable('assignments',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),title:text('title').notNull(),description:text('description').notNull(),maxScore:real('max_score').notNull(),dueAt:text('due_at').notNull(),isGroup:integer('is_group').notNull().default(0),groupMax:integer('group_max').notNull().default(5),individualWeight:real('individual_weight').notNull().default(0),workPhase:text('work_phase').notNull().default('before'),rubric:text('rubric').notNull().default('[]'),createdAt:text('created_at').notNull()},t=>[index('assignment_course').on(t.courseId)]);
export const submissions=sqliteTable('submissions',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id').notNull().references(()=>users.id),note:text('note').notNull().default(''),submittedAt:text('submitted_at').notNull(),score:real('score'),individualScore:real('individual_score'),feedback:text('feedback').notNull().default(''),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),reviewedAt:text('reviewed_at'),rubricScores:text('rubric_scores').notNull().default('[]'),groupId:text('group_id'),source:text('source').notNull().default('upload')},t=>[uniqueIndex('submission_assignment_student').on(t.assignmentId,t.studentId).where(sql`${t.deleted}=0`),index('submission_student').on(t.studentId)]);
export const files=sqliteTable('files',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id'),revision:integer('revision').notNull().default(0),kind:text('kind').notNull().default('work'),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('file_assignment').on(t.assignmentId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actorId:text('actor_id').notNull().references(()=>users.id),courseId:text('course_id'),action:text('action').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_course').on(t.courseId)]);
export const courseStaff=sqliteTable('course_staff',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),userId:text('user_id').notNull().references(()=>users.id),permission:text('permission').notNull()},t=>[uniqueIndex('staff_course_user').on(t.courseId,t.userId)]);
export const extensions=sqliteTable('extensions',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id').notNull().references(()=>users.id),dueAt:text('due_at').notNull(),note:text('note').notNull().default('')},t=>[uniqueIndex('extension_assignment_student').on(t.assignmentId,t.studentId).where(sql`${t.deleted}=0`)]);
export const sgsProfiles=sqliteTable('sgs_profiles',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),name:text('name').notNull(),config:text('config').notNull(),templateKey:text('template_key').notNull(),templateName:text('template_name').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()});
export const restoreJobs=sqliteTable('restore_jobs',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),manifest:text('manifest').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()});
export const restoreAssets=sqliteTable('restore_assets',{id:text('id').primaryKey(),jobId:text('job_id').notNull().references(()=>restoreJobs.id),assetId:text('asset_id').notNull(),objectKey:text('object_key').notNull(),sha256:text('sha256').notNull(),size:integer('size').notNull()},t=>[uniqueIndex('restore_job_asset').on(t.jobId,t.assetId)]);
export const trashJobs=sqliteTable('trash_jobs',{id:text('id').primaryKey(),actorId:text('actor_id').notNull().references(()=>users.id),kind:text('kind').notNull(),targetId:text('target_id').notNull(),title:text('title').notNull(),counts:text('counts').notNull(),createdAt:text('created_at').notNull(),restoredAt:text('restored_at')});
export const trashEntries=sqliteTable('trash_entries',{kind:text('kind').notNull(),recordId:text('record_id').notNull(),jobId:text('job_id').notNull().references(()=>trashJobs.id)},t=>[uniqueIndex('trash_record').on(t.kind,t.recordId),index('trash_job').on(t.jobId)]);
export const exams=sqliteTable('exams',{deleted:integer('deleted').notNull().default(0),id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),title:text('title').notNull(),kind:text('kind').notNull(),instructions:text('instructions').notNull().default(''),duration:integer('duration').notNull(),maxScore:real('max_score').notNull(),questions:text('questions').notNull(),shuffleQuestions:integer('shuffle_questions').notNull().default(0),shuffleOptions:integer('shuffle_options').notNull().default(0),unlockHash:text('unlock_hash').notNull(),status:text('status').notNull().default('draft'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('exam_course_kind').on(t.courseId,t.kind).where(sql`${t.deleted}=0`)]);
export const examAttempts=sqliteTable('exam_attempts',{id:text('id').primaryKey(),examId:text('exam_id').notNull().references(()=>exams.id),enrollmentId:text('enrollment_id').notNull().references(()=>enrollments.id),studentId:text('student_id').notNull().references(()=>users.id),status:text('status').notNull(),answers:text('answers').notNull().default('{}'),questionForm:text('question_form').notNull().default('[]'),startedAt:integer('started_at').notNull(),deadline:integer('deadline').notNull(),heartbeat:integer('heartbeat').notNull(),pageToken:text('page_token').notNull(),generation:integer('generation').notNull().default(0),lockReason:text('lock_reason').notNull().default(''),lockCount:integer('lock_count').notNull().default(0),score:real('score'),submittedAt:text('submitted_at'),synced:integer('synced').notNull().default(0)},t=>[uniqueIndex('exam_student').on(t.examId,t.studentId),index('exam_attempt_exam').on(t.examId)]);
export const examEvents=sqliteTable('exam_events',{id:text('id').primaryKey(),attemptId:text('attempt_id').notNull().references(()=>examAttempts.id),actorId:text('actor_id').notNull().references(()=>users.id),action:text('action').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[index('exam_event_attempt').on(t.attemptId)]);


export const workGroups=sqliteTable('work_groups',{id:text('id').primaryKey(),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),name:text('name').notNull(),leaderId:text('leader_id').notNull().references(()=>users.id),memberCount:integer('member_count').notNull().default(0),sealed:integer('sealed').notNull().default(0),revision:integer('revision').notNull().default(0),submissionToken:text('submission_token'),createdAt:text('created_at').notNull()});
export const groupMembers=sqliteTable('group_members',{groupId:text('group_id').notNull().references(()=>workGroups.id),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id').notNull().references(()=>users.id)},t=>[uniqueIndex('one_group_per_assignment').on(t.assignmentId,t.studentId)]);

export const attendanceSessions=sqliteTable('attendance_sessions',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),date:text('date').notNull(),title:text('title').notNull(),hours:real('hours').notNull(),revision:integer('revision').notNull().default(0),deleted:integer('deleted').notNull().default(0),createdAt:text('created_at').notNull()});
export const attendanceRecords=sqliteTable('attendance_records',{id:text('id').primaryKey(),sessionId:text('session_id').notNull().references(()=>attendanceSessions.id),studentId:text('student_id').notNull().references(()=>users.id),status:text('status').notNull(),hours:real('hours').notNull(),note:text('note').notNull().default(''),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('attendance_session_student').on(t.sessionId,t.studentId)]);
export const followupNotes=sqliteTable('followup_notes',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),studentId:text('student_id').notNull().references(()=>users.id),actorId:text('actor_id').notNull().references(()=>users.id),text:text('text').notNull(),nextDate:text('next_date').notNull().default(''),status:text('status').notNull().default('open'),revision:integer('revision').notNull().default(0),deleted:integer('deleted').notNull().default(0),createdAt:text('created_at').notNull()});
export const notificationReads=sqliteTable('notification_reads',{userId:text('user_id').notNull().references(()=>users.id),key:text('key').notNull(),readAt:text('read_at').notNull()},t=>[uniqueIndex('notification_user_key').on(t.userId,t.key)]);
export const questionBanks=sqliteTable('question_banks',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),name:text('name').notNull(),tags:text('tags').notNull().default(''),questions:text('questions').notNull(),revision:integer('revision').notNull().default(0),deleted:integer('deleted').notNull().default(0),createdAt:text('created_at').notNull()});
export const backupSnapshots=sqliteTable('backup_snapshots',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),courseId:text('course_id').notNull().references(()=>courses.id),kind:text('kind').notNull(),status:text('status').notNull(),manifestKey:text('manifest_key').notNull(),size:integer('size').notNull().default(0),error:text('error').notNull().default(''),day:text('day'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('daily_snapshot').on(t.ownerId,t.courseId,t.day)]);
