import { sqliteTable, text, integer, real, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const users = sqliteTable('users', {
 id:text('id').primaryKey(), username:text('username').notNull().unique(), name:text('name').notNull(), role:text('role').notNull(), password:text('password').notNull(), active:integer('active').notNull().default(1), mustChange:integer('must_change').notNull().default(0), createdAt:text('created_at').notNull()
});
export const settings = sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const sessions = sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const loginLimits = sqliteTable('login_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const periods=sqliteTable('periods',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),year:integer('year').notNull(),term:integer('term').notNull()},t=>[uniqueIndex('period_owner_year_term').on(t.ownerId,t.year,t.term)]);
export const courses=sqliteTable('courses',{id:text('id').primaryKey(),periodId:text('period_id').notNull().references(()=>periods.id),ownerId:text('owner_id').notNull().references(()=>users.id),code:text('code').notNull(),name:text('name').notNull(),classroom:text('classroom').notNull(),workWeight:real('work_weight').notNull().default(60),midWeight:real('mid_weight').notNull().default(20),finalWeight:real('final_weight').notNull().default(20),published:integer('published').notNull().default(0),archived:integer('archived').notNull().default(0),revision:integer('revision').notNull().default(0)},t=>[uniqueIndex('course_scope').on(t.periodId,t.code,t.classroom),index('course_owner').on(t.ownerId)]);
export const enrollments=sqliteTable('enrollments',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),studentId:text('student_id').notNull().references(()=>users.id),studentCode:text('student_code').notNull(),name:text('name').notNull(),number:integer('number').notNull(),active:integer('active').notNull().default(1),mid:real('mid'),final:real('final'),special:text('special').notNull().default('')},t=>[uniqueIndex('enrollment_course_student').on(t.courseId,t.studentId),index('enrollment_student').on(t.studentId)]);
export const assignments=sqliteTable('assignments',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),title:text('title').notNull(),description:text('description').notNull(),maxScore:real('max_score').notNull(),dueAt:text('due_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('assignment_course').on(t.courseId)]);
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id').notNull().references(()=>users.id),note:text('note').notNull().default(''),submittedAt:text('submitted_at').notNull(),score:real('score'),feedback:text('feedback').notNull().default(''),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),reviewedAt:text('reviewed_at')},t=>[uniqueIndex('submission_assignment_student').on(t.assignmentId,t.studentId),index('submission_student').on(t.studentId)]);
export const files=sqliteTable('files',{id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),studentId:text('student_id'),revision:integer('revision').notNull().default(0),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('file_assignment').on(t.assignmentId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actorId:text('actor_id').notNull().references(()=>users.id),courseId:text('course_id'),action:text('action').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_course').on(t.courseId)]);

