'use client';
import {useEffect,useState} from 'react';
import {Trophy,Sparkles,Volume2,VolumeX,CheckCircle2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
let audio:AudioContext|undefined;
export function SoundToggle(){const [on,setOn]=useState(false);useEffect(()=>setOn(localStorage.getItem('grade-celebration-sound')==='on'),[]);return <Button variant="ghost" size="icon" aria-label={on?'ปิดเสียงฉลอง':'เปิดเสียงฉลอง'} title={on?'ปิดเสียงฉลอง':'เปิดเสียงฉลอง'} onClick={()=>{const next=!on;setOn(next);localStorage.setItem('grade-celebration-sound',next?'on':'off');if(next){audio??=new AudioContext();void audio.resume();}}}>{on?<Volume2 size={17}/>:<VolumeX size={17}/>}</Button>;}
export function Celebration({title,done,total,reward,onClose}:{title:string;done:number;total:number;reward?:{xp:number;level:number;leveled:boolean;badges:string[];themes:string[]};onClose:()=>void}){
 const [reduced,setReduced]=useState(true);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);if(localStorage.getItem('grade-celebration-sound')==='on')try{audio??=new AudioContext();void audio.resume().then(()=>{[523.25,659.25,783.99,1046.5].forEach((f,i)=>{const oscillator=audio!.createOscillator(),gain=audio!.createGain(),start=audio!.currentTime+i*.1;oscillator.type='sine';oscillator.frequency.value=f;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.08,start+.02);gain.gain.exponentialRampToValueAtTime(.001,start+.35);oscillator.connect(gain);gain.connect(audio!.destination);oscillator.start(start);oscillator.stop(start+.4);});}).catch(()=>{});}catch{}},[]);
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className={`celebration-dialog ${reduced?'motion-quiet':''}`}><div aria-hidden="true" className="confetti-field">{!reduced&&Array.from({length:56},(_,i)=><i key={i} style={{left:`${i*73%100}%`,background:['#ffd84d','#6ff0da','#ff76b0','#7caaff','#fff'][i%5],animationDelay:`${i%9*.045}s`,transform:`rotate(${i*31}deg)`}}/>)}</div><div className="mission-emblem" aria-hidden="true"><Trophy size={64}/><Sparkles className="mission-sparkles" size={26}/></div><span className="mission-tag"><CheckCircle2 size={16}/> บันทึกงานสำเร็จ</span><DialogTitle>ภารกิจสำเร็จ!</DialogTitle><DialogDescription className="mission-description">{title}<br/>งานถึงมือครูแล้ว เก่งมากที่ทำเสร็จอีกหนึ่งงาน!</DialogDescription>{reward&&<div className="celebration-rewards" role="status"><strong>{reward.xp?`+${reward.xp} XP 🌱`:'งานแก้ไขถึงมือครูแล้ว 🌱'}</strong>{reward.leveled&&<span>เลเวลอัป! ตอนนี้เลเวล {reward.level} ✨</span>}{reward.badges.map(name=><span key={name}>🏅 ได้รับเหรียญ “{name}”</span>)}{reward.themes.map(name=><span key={name}>🎨 ปลดล็อกธีม “{name}” แล้ว</span>)}</div>}<div className="mission-progress"><div><strong>ส่งแล้ว {done} / {total} งาน</strong><span>{done>=total&&total>0?'ครบทุกภารกิจในวิชานี้!':'ค่อย ๆ เก็บให้ครบ ไปต่อได้เลย'}</span></div><div className="mission-meter"><span style={{width:`${total?done/total*100:0}%`}}/></div></div><Button autoFocus onClick={onClose} className="mission-button">ลุยงานต่อ!</Button><p className="mission-footnote">การฉลองไม่มีผลต่อคะแนน ครูจะตรวจงานตามเกณฑ์</p></DialogContent></Dialog>;
}
