'use client';
import {useState} from 'react';
import {Copy,Printer,Download,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,dateThai,timeThai,localDue,dueISO,download,type AppState,type Row} from '@/lib/client';
import {parseRubric} from '@/lib/rubrics';
import {Choice,DataTable,BusyButton,Status,Empty,FileLinks} from './shared';
import type {Edit} from './editor';
export function GradeMatrix({state,course,refresh,edit}:{state:AppState;course:Row;refresh:()=>Promise<any>;edit:(e:Edit)=>void}){const assignments=state.assignments.filter(a=>a.course_id===course.id),students=state.enrollments.filter(e=>e.course_id===course.id&&e.active).sort((a,b)=>a.number-b.number);return <><section className="panel"><h2>ตารางงานทั้งห้อง</h2><p className="muted">เปิดช่องงานเพื่อดูและตรวจ · กรอกคะแนนงานที่ส่งในห้องเรียนได้โดยไม่ต้องแนบรูป</p></section><section className="panel table-panel matrix-panel">{students.length&&assignments.length?<DataTable headers={['นักเรียน',...assignments.map(a=>`${a.title} / ${a.max_score}`)]} rows={students.map(e=>[<div><strong>{e.number}. {e.name}</strong><small>{e.student_code}</small></div>,...assignments.map(a=>{const s=state.submissions.find(s=>s.assignment_id===a.id&&s.student_id===e.student_id);return <MatrixCell key={`${e.id}-${a.id}-${s?.score}-${s?.revision}`} a={a} s={s} student={e} disabled={!course.can_edit||!!course.archived} refresh={refresh} open={()=>edit({kind:s?'review':'paper',item:s||e,assignment:a,course})}/>;})])}/>:<Empty title="เพิ่มนักเรียนและงานก่อนเริ่มใช้ตาราง"/>}</section></>;}
function MatrixCell({a,s,student,disabled,refresh,open}:{a:Row;s?:Row;student:Row;disabled:boolean;refresh:()=>Promise<any>;open:()=>void}){const [score,setScore]=useState(s?.score===null||s?.score===undefined?'':String(s.score)),[busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="matrix-cell"><Button variant="ghost" size="sm" onClick={open} disabled={disabled}><Status status={s?.status||'missing'}/>{s?.source==='paper'&&<small>กระดาษ</small>}</Button>{!disabled&&!parseRubric(a.rubric).length?<div className="row"><Input aria-label={`คะแนน ${student.student_code} ${a.title}`} type="number" min={0} max={a.max_score} step={.01} value={score} onChange={e=>setScore(e.target.value)}/><BusyButton busy={busy} disabled={score===''} size="icon" variant="outline" aria-label={`บันทึกคะแนน ${student.student_code} ${a.title}`} onClick={async()=>{setBusy(true);setError('');try{if(score==='')throw Error('กรอกคะแนน');const value=Number(score);if(!Number.isFinite(value)||value<0||value>a.max_score)throw Error(`คะแนนต้องอยู่ระหว่าง 0–${a.max_score}`);await api(s?`review/${s.id}`:'paper-grade',s?{score:value,revision:s.revision,expectedReviewedAt:s.reviewed_at??null,expectedRubric:a.rubric,feedback:s.feedback}:{assignmentId:a.id,studentId:student.student_id,score:value},s?'PATCH':'POST');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Save size={15}/></BusyButton></div>:<strong>{s?.score??'—'} / {a.max_score}</strong>}{error&&<p className="error">{error}</p>}</div>;}
const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function Followup({state,course,refresh}:{state:AppState;course:Row;refresh:()=>Promise<any>}){
 const [selected,setSelected]=useState('all');const enrolls=state.enrollments.filter(e=>e.course_id===course.id&&e.active).sort((a,b)=>a.number-b.number),tasks=state.assignments.filter(a=>a.course_id===course.id),shown=selected==='all'?enrolls:enrolls.filter(e=>e.id===selected);const pending=(e:Row)=>tasks.filter(a=>{const s=state.submissions.find(s=>s.student_id===e.student_id&&s.assignment_id===a.id);return !s||s.status==='returned';});
 function report(){return `<!doctype html><html lang="th"><meta charset="UTF-8"><title>ใบติดตามงาน ${escape(course.name)}</title><style>body{font:16px Tahoma,sans-serif;color:#172439;margin:24px}section{break-after:page}h1{font-size:24px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccd5e3;padding:12px;text-align:left;vertical-align:top}small{display:block;color:#56647b}a{color:#214ed3;overflow-wrap:anywhere}@media print{body{margin:0}section:last-child{break-after:auto}}</style><body>${shown.map(e=>`<section><h1>ใบติดตามงาน — ${escape(e.name)}</h1><p>เลขที่ ${e.number} · รหัส ${escape(e.student_code)} · ${escape(course.name)} ${escape(course.classroom)}</p><p>พิมพ์ ${escape(dateThai(new Date().toISOString()))} · งานที่ต้องทำ ${pending(e).length} งาน</p><table><tr><th>งาน / สิ่งที่ต้องทำ</th><th>สถานะ</th><th>กำหนดส่ง</th></tr>${pending(e).map(a=>{const s=state.submissions.find(s=>s.assignment_id===a.id&&s.student_id===e.student_id),x=state.extensions.find(x=>x.assignment_id===a.id&&x.student_id===e.student_id);return `<tr><td><strong>${escape(a.title)}</strong><p>${escape(a.description).replace(/\n/g,'<br>')}</p>${s?.feedback?`<p>คำแนะนำ: ${escape(s.feedback)}</p>`:''}${state.files.filter(f=>f.assignment_id===a.id&&!f.student_id).map(f=>`<a href="${escape(location.origin+'/api/file/'+f.id)}">โจทย์/ตัวอย่าง: ${escape(f.name)}</a><br>`).join('')}</td><td>${s?'ต้องแก้ไข':'ยังไม่ส่ง'}</td><td>${escape(timeThai(x?.due_at||a.due_at))}${x?.note?`<small>${escape(x.note)}</small>`:''}</td></tr>`;}).join('')}</table><p>เข้าสู่ระบบส่งงาน: <a href="${escape(location.origin)}">${escape(location.origin)}</a></p><p>ผู้รับทราบ ___________________ วันที่ __________</p></section>`).join('')}</body></html>`;}
 return <><div className="section-toolbar"><h2>ติดตามงานขาดและงานแก้ไข</h2><div className="row"><Choice label="เลือกนักเรียนสำหรับใบติดตาม" value={selected} onChange={setSelected} options={[{value:'all',label:'ทุกคนในห้อง'},...enrolls.map(e=>({value:e.id,label:`${e.number}. ${e.name}`}))]}/><Button variant="outline" onClick={()=>{const w=window.open('','_blank');if(!w)return;w.document.open();w.document.write(report());w.document.close();w.focus();w.print();}}><Printer size={16}/> พิมพ์ / บันทึก PDF</Button><Button variant="outline" onClick={()=>download(report(),`ใบติดตาม-${course.code}.html`,'text/html;charset=utf-8')}><Download size={16}/> ดาวน์โหลดใบติดตาม</Button></div></div>{shown.map(e=><section className="panel followup-student" key={e.id}><div className="panel-head"><h3>{e.number}. {e.name}</h3><span className="badge red">ต้องทำ {pending(e).length} งาน</span></div>{pending(e).length?<div className="followup-list">{pending(e).map(a=>{const s=state.submissions.find(s=>s.assignment_id===a.id&&s.student_id===e.student_id),x=state.extensions.find(x=>x.assignment_id===a.id&&x.student_id===e.student_id);return <div className="followup-task" key={a.id}><div><strong>{a.title}</strong><Status status={s?'returned':'missing'}/><p>{s?.feedback||a.description}</p><FileLinks files={state.files.filter(f=>f.assignment_id===a.id&&!f.student_id)}/><small>กำหนดส่ง {timeThai(x?.due_at||a.due_at)}</small></div>{course.can_edit&&!course.archived&&<ExtensionForm key={x?.due_at||a.due_at} a={a} studentId={e.student_id} extension={x} refresh={refresh}/>}</div>;})}</div>:<p className="success">ไม่มีงานค้างหรือรอแก้ไข</p>}</section>)}</>;
}
function ExtensionForm({a,studentId,extension,refresh}:{a:Row;studentId:string;extension?:Row;refresh:()=>Promise<any>}){const [due,setDue]=useState(localDue(extension?.due_at||a.due_at)),[note,setNote]=useState(extension?.note||''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('extensions',{assignmentId:a.id,studentId,dueAt:dueISO(due),note});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>กำหนดส่งรายคน<Input type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></label><label>บันทึกนัดหมาย<Input value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></label><BusyButton type="submit" busy={busy}>บันทึกวันส่งใหม่</BusyButton>{error&&<p className="error">{error}</p>}</form>;}
export function CopyCourse({state,course,onDone}:{state:AppState;course:Row;onDone:(r:any)=>Promise<void>}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[target,setTarget]=useState(state.periods.find(p=>p.id!==course.period_id)?.id||'new');const p=state.periods.find(p=>p.id===course.period_id)!;return <><Button variant="outline" onClick={()=>setOpen(true)}><Copy size={16}/> คัดลอกไปเทอมใหม่</Button>{open&&<Dialog open onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="editor-dialog"><DialogTitle>คัดลอกแผนรายวิชา</DialogTitle><DialogDescription>นำงาน เกณฑ์คะแนน และไฟล์ตัวอย่างไปใช้ใหม่ คะแนนและงานส่งของเทอมเดิมยังอยู่ที่เดิม</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{let periodId=target;if(target==='new'){const year=Number(form.get('year')),term=Number(form.get('term'));periodId=state.periods.find(p=>p.year===year&&p.term===term)?.id||(await api('periods',{year,term})).id;}const r=await api('copy-course',{courseId:course.id,periodId,code:form.get('code'),name:form.get('name'),classroom:form.get('classroom'),shiftDays:Number(form.get('days')),copyRoster:form.get('roster')==='on'});await onDone({...r,periodId});setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>ภาคเรียนปลายทาง<Choice label="ภาคเรียนปลายทาง" value={target} onChange={setTarget} options={[{value:'new',label:'เพิ่มภาคเรียนใหม่'},...state.periods.map(p=>({value:p.id,label:`${p.year} เทอม ${p.term}`}))]}/></label>{target==='new'&&<div className="form-grid"><label>ปีการศึกษา<Input name="year" type="number" min={2500} max={2700} defaultValue={p.year+(p.term>=2?1:0)} required/></label><label>เทอม<Input name="term" type="number" min={1} max={3} defaultValue={p.term>=2?1:2} required/></label></div>}<label>รหัสวิชา<Input name="code" defaultValue={course.code} maxLength={30} required/></label><label>ชื่อวิชา<Input name="name" defaultValue={course.name} maxLength={100} required/></label><label>ห้อง<Input name="classroom" defaultValue={course.classroom} maxLength={40} required/></label><label>เลื่อนกำหนดส่งทุกงาน (จำนวนวัน)<Input name="days" type="number" min={-3650} max={3650} defaultValue={120} required/></label><label className="check-label"><Checkbox name="roster"/> คัดลอกรายชื่อด้วย (คะแนนเริ่มว่าง)</label>{error&&<p className="error">{error}</p>}<BusyButton type="submit" busy={busy}>คัดลอกแผนรายวิชา</BusyButton></form></DialogContent></Dialog>}</>;}
const labels:Record<string,string>={review:'ตรวจ/แก้คะแนนงาน',paper_grade:'ให้คะแนนงานกระดาษ',exam_scores:'คะแนนสอบ',publication:'เผยแพร่ผล',submission:'ส่งงาน',extension:'ขยายเวลาส่ง',copy_course:'คัดลอกวิชา',course_access:'เปลี่ยนสิทธิ์รายวิชา',import_students:'นำเข้ารายชื่อ',reset_password:'ตั้งรหัสผ่าน',restored_history:'ประวัติจากชุดกู้คืน'};
export function History({state,course}:{state:AppState;course:Row}){return <section className="panel"><h2>ประวัติการเปลี่ยนแปลง</h2><p className="muted">แสดงล่าสุด 500 รายการในวิชาที่คุณมีสิทธิ์</p><DataTable headers={['วันเวลา','ผู้ดำเนินการ','รายการ','รายละเอียด']} rows={state.history.filter(h=>h.course_id===course.id).map(h=>[timeThai(h.created_at),h.actor_name,labels[h.action]||h.action,<details><summary>ดูรายละเอียด</summary><pre className="history-detail">{JSON.stringify(JSON.parse(h.detail),null,2)}</pre></details>])}/></section>;}
