'use client';
import { useState } from 'react';
import { Plus, Pencil, CalendarDays, Upload, KeyRound, Search, BookOpen, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { dateThai,timeThai,type AppState,type Row } from '@/lib/client';
import { calculateGrade } from '@/lib/grades';
import { Empty,DataTable,Status,FileLinks } from './shared';
import {parseRubric} from '@/lib/rubrics';
import {RubricResult} from './rubric';
import type { Edit } from './editor';
import {ScoreSummary} from './score-summary';
export function CourseView({state,course,edit,initialFilter='all'}:{state:AppState;course:Row;edit:(e:Edit)=>void;initialFilter?:string}){
 const [filter,setFilter]=useState(initialFilter);const teacher=state.user.role!=='student';const editable=!!course.can_edit;const allTasks=state.assignments.filter(a=>a.course_id===course.id);const mySub=(a:Row)=>state.submissions.find(s=>s.assignment_id===a.id&&s.student_id===state.user.id);
 const tasks=allTasks.filter(a=>filter==='all'||filter==='missing'&&!mySub(a)||filter==='returned'&&mySub(a)?.status==='returned'||filter==='graded'&&mySub(a)?.status==='graded');
 const ownEnrollment=!teacher?state.enrollments.find(e=>e.course_id===course.id&&e.student_id===state.user.id&&e.active):undefined;
 const count=state.enrollments.filter(e=>e.course_id===course.id&&e.active).length;
 return <><div className="course-banner"><span className="course-symbol"><BookOpen size={27}/></span><div><small>{course.code} · {course.classroom}</small><h2>{course.name}</h2><p>คะแนนเก็บ {course.work_weight} / กลางภาค {course.mid_weight} / ปลายภาค {course.final_weight}</p></div><div className="course-banner-actions"><span>{teacher?`${count} คน · `:''}{allTasks.length} งาน</span>{teacher&&<Button variant="secondary" disabled={!!course.archived||!course.can_edit} onClick={()=>edit({kind:'course',item:course})}><Pencil size={16}/> แก้ไขวิชา</Button>}</div></div>{ownEnrollment&&<ScoreSummary state={state} course={course} enrollment={ownEnrollment}/>}<div className="section-toolbar"><h2>{teacher?'งานที่มอบหมาย':'งานของฉัน'}</h2>{teacher?<Button disabled={!!course.archived||!course.can_edit} onClick={()=>edit({kind:'assignment',course})}><Plus size={17}/> มอบหมายงาน</Button>:<Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="all">ทั้งหมด</TabsTrigger><TabsTrigger value="missing">ยังไม่ส่ง</TabsTrigger><TabsTrigger value="returned">แก้ไข</TabsTrigger><TabsTrigger value="graded">ตรวจแล้ว</TabsTrigger></TabsList></Tabs>}</div>
 {tasks.length?<div className="task-grid">{tasks.map(a=>{const s=mySub(a);const subs=state.submissions.filter(s=>s.assignment_id===a.id&&state.enrollments.some(e=>e.course_id===course.id&&e.active&&e.student_id===s.student_id));const sample=state.files.filter(f=>f.assignment_id===a.id&&!f.student_id);const extension=state.extensions.find(x=>x.assignment_id===a.id&&x.student_id===state.user.id);const due=extension?.due_at||a.due_at;const overdue=Date.now()>new Date(due).getTime();return <article className="panel task-card" key={a.id}><div className="task-top"><span className="task-icon"><FileText size={20}/></span>{!teacher&&<Status status={s?.status||'missing'}/>}<span className="score-label">{a.max_score} คะแนน</span></div><h3>{a.title}</h3><div className={`task-due ${overdue&&!s&&!teacher?'overdue':''}`}><CalendarDays size={14}/> กำหนดส่ง {timeThai(due)}{extension&&' (ขยายเวลารายคน)'}</div><p className="task-description whitespace-pre-wrap">{a.description||'ส่งรูปหรือไฟล์งานตามที่ครูมอบหมาย'}</p>{parseRubric(a.rubric).length>0&&s?.status!=='graded'&&<div className='rubric-result'><strong>เกณฑ์ของงานนี้</strong>{parseRubric(a.rubric).map(r=><div key={r.id}><span>{r.label}</span><strong>{r.max} คะแนน</strong></div>)}</div>}{sample.length>0&&<div className="task-samples"><span>โจทย์ / ตัวอย่างงาน</span><FileLinks files={sample}/></div>}{teacher?<><div className="task-progress"><span>ส่งแล้ว {subs.length} / {count} คน</span><strong>{count?Math.round(subs.length/count*100):0}%</strong></div><Progress value={count?subs.length/count*100:0}/><div className="task-footer"><span className="muted">ตรวจแล้ว {subs.filter(s=>s.status==='graded').length} คน</span><Button variant="ghost" disabled={!!course.archived||!course.can_edit} size="sm" onClick={()=>edit({kind:'assignment',item:a,course})}><Pencil size={14}/> แก้ไขงาน</Button></div></>:<><div className="student-feedback">{s?.status==='graded'&&<div className="earned-score"><strong>{s.score}</strong><span> / {a.max_score} คะแนน</span></div>}{s&&<RubricResult assignment={a} submission={s}/>} {s?.feedback&&<p className="notice whitespace-pre-wrap">ครู: {s.feedback}</p>}{s&&<p className="muted">ส่ง {timeThai(s.submitted_at)} · รอบที่ {s.revision}{new Date(s.submitted_at)>new Date(due)&&' · ส่งหลังกำหนด'}</p>}</div><FileLinks files={state.files.filter(f=>f.assignment_id===a.id&&f.student_id===state.user.id&&f.revision===s?.revision)}/>{(!s||s.status==='returned')&&!course.archived&&!course.published&&<Button className="w-full" onClick={()=>edit({kind:'submit',assignment:a,course})}><Upload size={16}/> {s?'ส่งงานที่แก้ไข':'ส่งงาน'}</Button>}{!s&&(course.archived||course.published)&&<p className="muted">รายวิชานี้ปิดรับงานแล้ว</p>}</>}</article>;})}</div>:<section className="panel"><Empty title={allTasks.length?'ไม่มีงานในสถานะนี้':'ยังไม่มีงานที่มอบหมาย'} description={teacher?'เพิ่มงานพร้อมคะแนนเต็ม กำหนดส่ง และตัวอย่างงาน':'เมื่อครูมอบหมายงาน จะปรากฏที่นี่'}/></section>}</>;
}
export function ReviewView({state,course,edit}:{state:AppState;course:Row;edit:(e:Edit)=>void}){
 const [filter,setFilter]=useState('pending');const tasks=state.assignments.filter(a=>a.course_id===course.id);const subs=state.submissions.filter(s=>tasks.some(a=>a.id===s.assignment_id)&&state.enrollments.some(e=>e.course_id===course.id&&e.student_id===s.student_id&&e.active));const visible=subs.filter(s=>filter==='all'||s.status===filter).sort((a,b)=>a.submitted_at.localeCompare(b.submitted_at));
 return <><div className="section-toolbar"><div><h2>ตรวจงาน {course.name}</h2><p className="muted">เปิดรูปงาน ให้คะแนน หรือส่งคืนเพื่อให้นักเรียนแก้ไข</p></div><Tabs value={filter} onValueChange={setFilter}><TabsList><TabsTrigger value="pending">รอตรวจ ({subs.filter(s=>s.status==='pending').length})</TabsTrigger><TabsTrigger value="graded">ตรวจแล้ว</TabsTrigger><TabsTrigger value="returned">ส่งคืน</TabsTrigger><TabsTrigger value="all">ทั้งหมด</TabsTrigger></TabsList></Tabs></div><section className="panel table-panel">{visible.length?<DataTable headers={['นักเรียน','งาน','วันส่ง','สถานะ','คะแนน','']} rows={visible.map(s=>{const a=tasks.find(a=>a.id===s.assignment_id)!;const e=state.enrollments.find(e=>e.course_id===course.id&&e.student_id===s.student_id)!;return [<div><strong>{e.name}</strong><small className="cell-sub">เลขที่ {e.number} · {e.student_code}</small></div>,a.title,<div>{timeThai(s.submitted_at)}{new Date(s.submitted_at)>new Date(state.extensions.find(x=>x.assignment_id===a.id&&x.student_id===s.student_id)?.due_at||a.due_at)&&<small className="cell-sub overdue">ส่งหลังกำหนด</small>}</div>,<Status status={s.status}/>,s.score===null?'—':`${s.score} / ${a.max_score}`,<Button size="sm" variant={s.status==='pending'?'default':'outline'} disabled={!!course.archived||!course.can_edit} onClick={()=>edit({kind:'review',item:s,assignment:a,course,queue:visible.map(s=>s.id)})}>เปิดตรวจงาน</Button>];})}/>:<Empty title={filter==='pending'?'ตรวจครบแล้วในตอนนี้':'ไม่มีงานในสถานะนี้'} description="งานที่นักเรียนส่งจะปรากฏที่นี่"/>}</section></>;
}
export function StudentsView({state,course,edit,openImport}:{state:AppState;course:Row;edit:(e:Edit)=>void;openImport:()=>void}){
 const [search,setSearch]=useState('');const enrolls=state.enrollments.filter(e=>e.course_id===course.id&&(e.name.includes(search)||e.student_code.includes(search))).sort((a,b)=>a.number-b.number);
 return <><div className="section-toolbar"><div><h2>นักเรียน {course.classroom}</h2><p className="muted">รายชื่อและสถานะการส่งงานของวิชานี้</p></div><div className="row"><Button variant="outline" disabled={!!course.archived||!course.can_edit} onClick={openImport}><Upload size={16}/> นำเข้ารายชื่อ</Button><Button disabled={!!course.archived||!course.can_edit} onClick={()=>edit({kind:'student',course})}><Plus size={16}/> เพิ่มนักเรียน</Button></div></div><div className="search-box"><Search size={18}/><Input aria-label="ค้นหานักเรียน" placeholder="ค้นหาชื่อหรือรหัสนักเรียน" value={search} onChange={e=>setSearch(e.target.value)}/></div><section className="panel table-panel">{enrolls.length?<DataTable headers={['เลขที่','รหัสนักเรียน','ชื่อ–นามสกุล','ส่งแล้ว','ยังไม่ส่ง','สถานะ','']} rows={enrolls.map(e=>{const g=calculateGrade(course,state.assignments,state.submissions,e);return [e.number,<span className="mono">{e.student_code}</span>,<strong>{e.name}</strong>,`${g.submitted} งาน`,<span className="missing-number">{g.missing} งาน</span>,<span className={`badge ${e.active?'green':'gray'}`}>{e.active?'ลงทะเบียนอยู่':'พักการลงทะเบียน'}</span>,<div className="row"><Button variant="ghost" size="icon" aria-label={`แก้ไข ${e.name}`} disabled={!!course.archived||!course.can_edit} onClick={()=>edit({kind:'enrollment',item:e,course})}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label={`คืนรหัสเริ่มต้น ${e.name}`} disabled={!course.can_edit||state.user.role!=='admin'} onClick={()=>edit({kind:'reset',item:e,course})}><KeyRound size={16}/></Button></div>];})}/>:<Empty title={search?'ไม่พบนักเรียน':'ยังไม่มีนักเรียนในรายวิชานี้'} description="เพิ่มรายชื่อทีละคน หรือนำเข้าจาก Excel, Word และ PDF"/>}</section></>;
}
