'use client';
import {createContext,useContext,useState,type ReactNode} from 'react';
import {Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/lib/client';
export const dataLabels:Record<string,string>={exam:'ข้อสอบ',examAttempt:'คำตอบสอบ',period:'ภาคเรียน',subject:'วิชา',course:'ห้องเรียน',assignment:'งานที่มอบหมาย',enrollment:'การลงทะเบียน',submission:'งานส่ง / คะแนนงาน',file:'ไฟล์',student:'บัญชีนักเรียน',extension:'กำหนดส่งรายคน',profile:'แบบส่งออก SGS'};
const RefreshContext=createContext<()=>Promise<any>>(async()=>{});
export function DataActionsProvider({refresh,children}:{refresh:()=>Promise<any>;children:ReactNode}){return <RefreshContext.Provider value={refresh}>{children}</RefreshContext.Provider>;}
export function DeleteButton({kind,id,label='ลบ',disabled=false}:{kind:string;id:string;label?:string;disabled?:boolean}){
 const refresh=useContext(RefreshContext),[open,setOpen]=useState(false),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function begin(){setOpen(true);setPreview(null);setError('');setBusy(true);try{setPreview(await api('trash/preview',{kind,id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Button type='button' size='sm' variant='outline' className='delete-button' disabled={disabled} onClick={begin}><Trash2 size={14}/>{label}</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className='editor-dialog'><DialogHeader><DialogTitle>{kind==='reset'?'ล้างข้อมูลการเรียนทั้งหมด':'ย้ายข้อมูลไปถังขยะ'}</DialogTitle><DialogDescription>ข้อมูลและไฟล์ต้นฉบับเก็บไว้ กู้คืนได้จากเมนู “จัดการข้อมูล / ถังขยะ”</DialogDescription></DialogHeader>{preview&&<><h3>{preview.title}</h3><p>ข้อมูลที่ได้รับผล:</p><ul className='trash-counts'>{Object.entries(preview.counts).map(([k,n])=><li key={k}><span>{dataLabels[k]||k}</span><strong>{String(n)} รายการ</strong></li>)}</ul><p className='notice'>{kind==='enrollment'?'ลบการลงทะเบียน งานส่ง และคะแนนในห้องนี้ บัญชีและประวัติห้องอื่นยังอยู่':kind==='student'?'ลบบัญชีนักเรียนพร้อมงานและคะแนนทุกปี / ทุกเทอม บัญชีนี้จะเข้าสู่ระบบไม่ได้จนกู้คืน':kind==='reset'?'ล้างภาคเรียน วิชา ห้องเรียน งาน คะแนน ไฟล์ และบัญชีนักเรียนทั้งหมด บัญชีครูและผู้ดูแลยังเข้าใช้ระบบได้':'ข้อมูลลูกที่แสดงด้านบนจะย้ายเข้าถังขยะพร้อมกัน'} · ผลการเรียนห้องที่ได้รับผลจะต้องตรวจสอบก่อนเผยแพร่ใหม่</p></>}{error&&<p className='error' role='alert'>{error}</p>}<div className='dialog-actions'><Button variant='outline' disabled={busy} onClick={()=>setOpen(false)}>ยกเลิก</Button><Button variant='destructive' disabled={busy||!preview} onClick={async()=>{setBusy(true);setError('');try{await api('trash',{kind,id,signature:preview.signature});setOpen(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'กำลังตรวจสอบ…':'ย้ายไปถังขยะ'}</Button></div></DialogContent></Dialog></>;
}
