'use client';
import {useEffect,useState} from 'react';
import {Pencil,Undo2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,timeThai,type AppState,type Row} from '@/lib/client';
import {Choice,DataTable,Empty} from './shared';
import {DeleteButton,dataLabels} from './data-actions';
import type {Edit} from './editor';
export function DataManager({state,refresh,edit}:{state:AppState;refresh:()=>Promise<any>;edit:(e:Edit)=>void}){
 const [kind,setKind]=useState('period'),[search,setSearch]=useState(''),[jobs,setJobs]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{setJobs((await api('trash')).jobs);}catch(e){setError((e as Error).message);}};
 useEffect(()=>{void load();},[state]);
 const admin=state.user.role==='admin';const own=(r:Row)=>admin||r.owner_id===state.user.id;const editable=(r:Row)=>!!state.courses.find(c=>c.id===r.course_id)?.can_edit;
 const groups:Record<string,Row[]>={period:state.periods.filter(own),subject:state.subjects.filter(own),course:state.courses.filter(c=>c.can_edit),assignment:state.assignments.filter(editable),enrollment:state.enrollments.filter(editable),submission:state.submissions.filter(s=>editable({id:s.id,course_id:state.assignments.find(a=>a.id===s.assignment_id)?.course_id})),file:state.files.filter(editable),profile:state.profiles,...(admin?{student:state.students}:{} )};
 const title=(r:Row)=>kind==='period'?`ปี ${r.year} เทอม ${r.term}`:kind==='submission'?`${state.enrollments.find(e=>e.student_id===r.student_id&&e.course_id===state.assignments.find(a=>a.id===r.assignment_id)?.course_id)?.name||'นักเรียน'} · ${state.assignments.find(a=>a.id===r.assignment_id)?.title||'งาน'}`:r.title||r.name||r.student_code;
 const context=(r:Row)=>{if(kind==='student')return `ชื่อผู้ใช้ ${r.username} · บัญชีร่วมทุกเทอม`;const c=kind==='course'?r:state.courses.find(c=>c.id===r.course_id||c.id===state.assignments.find(a=>a.id===r.assignment_id)?.course_id);const p=state.periods.find(p=>p.id===(r.period_id||c?.period_id));return [p?`${p.year} เทอม ${p.term}`:'',c?`${c.code} · ${c.classroom}`:'',r.student_code||''].filter(Boolean).join(' · ');};
 const canEdit=!['submission'].includes(kind);const rows=(groups[kind]||[]).filter(r=>`${title(r)} ${context(r)}`.toLowerCase().includes(search.toLowerCase()));
 return <><section className='panel'><h2>จัดการข้อมูล</h2><p className='muted'>เลือกประเภทแล้วแก้ไขหรือลบได้ทุกปี / ทุกเทอม การลบห้องหรือวิชาจะพางานและคะแนนในส่วนนั้นเข้าถังขยะด้วย</p><div className='row management-filter'><Choice fullText label='ประเภทข้อมูล' value={kind} onChange={v=>{setKind(v);setSearch('');}} options={Object.keys(groups).map(k=>({value:k,label:dataLabels[k]}))}/><Input aria-label='ค้นหาข้อมูลที่ต้องการจัดการ' placeholder='ค้นหาชื่อ รหัส หรือห้องเรียน' value={search} onChange={e=>setSearch(e.target.value)}/></div></section><section className='panel table-panel'>{rows.length?<DataTable headers={['ข้อมูล','ปี / เทอม / ห้อง','จัดการ']} rows={rows.map(r=>[<strong>{title(r)}</strong>,context(r),<div className='row'>{canEdit&&<Button size='sm' variant='outline' onClick={()=>edit({kind:(kind==='student'?'studentAccount':kind) as Edit['kind'],item:r,course:kind==='course'?r:state.courses.find(c=>c.id===r.course_id)})}><Pencil size={14}/>แก้ไข</Button>}{kind==='submission'&&<Button size='sm' variant='outline' onClick={()=>{const a=state.assignments.find(a=>a.id===r.assignment_id);edit({kind:'review',item:r,assignment:a,course:state.courses.find(c=>c.id===a?.course_id)});}}><Pencil size={14}/>แก้คะแนน</Button>}<DeleteButton kind={kind} id={r.id} label={kind==='enrollment'?'ลบจากห้องนี้':kind==='student'?'ลบบัญชีทุกเทอม':'ลบ'}/></div>])}/>:<Empty title='ไม่มีข้อมูลในประเภทนี้' description='รายการที่ลบแล้วอยู่ในถังขยะด้านล่าง'/>}</section><section className='panel'><div className='panel-head'><div><h2>ถังขยะ</h2><p className='muted'>กู้คืนข้อมูลพร้อมไฟล์เดิมได้ หากลบภาคเรียนหรือวิชาต้นทางไว้ ต้องกู้คืนต้นทางก่อน</p></div><Button variant='outline' onClick={load}>อัปเดตถังขยะ</Button></div>{error&&<p className='error' role='alert'>{error}</p>}{jobs.length?<DataTable headers={['รายการที่ลบ','วันเวลา','ข้อมูลที่กู้คืน','']} rows={jobs.map(j=>[j.title,timeThai(j.created_at),Object.entries(JSON.parse(j.counts)).map(([k,n])=>`${dataLabels[k]} ${n}`).join(' · '),<Button variant='outline' size='sm' disabled={!!busy} onClick={async()=>{setBusy(j.id);setError('');try{await api('trash/restore',{jobId:j.id});await refresh();await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><Undo2 size={14}/>{busy===j.id?'กำลังกู้คืน…':'กู้คืน'}</Button>])}/>:<Empty title='ถังขยะว่าง'/>}</section>{admin&&<section className='panel reset-panel'><h2>ล้างข้อมูลการเรียนทั้งหมด</h2><p>สำหรับเริ่มระบบใหม่ ย้ายข้อมูลการเรียนทุกปี / ทุกเทอมและบัญชีนักเรียนเข้าถังขยะพร้อมกัน ดูจำนวนข้อมูลก่อนยืนยันและกู้คืนทั้งชุดได้</p><p className='muted'>บัญชีครู ผู้ดูแล แบบส่งออก SGS และประวัติการดำเนินการเก็บไว้</p><DeleteButton kind='reset' id='all' label='ล้างข้อมูลการเรียนทั้งหมด'/></section>}</>;
}
