'use client';
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { api,localDue,dueISO,type AppState,type Row } from '@/lib/client';
import { BusyButton,FileLinks,Images } from './shared';
export type Edit={kind:'period'|'course'|'assignment'|'student'|'enrollment'|'review'|'submit'|'password'|'reset';item?:Row;course?:Row;assignment?:Row};
export function Editor({edit,state,periodId,onClose,onDone}:{edit:Edit;state:AppState|null;periodId:string;onClose:()=>void;onDone:(r:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const {kind,item,course,assignment}=edit;
 const titles={period:'เพิ่มปีการศึกษา / ภาคเรียน',course:item?'แก้ไขรายวิชา':'สร้างรายวิชา',assignment:item?'แก้ไขงาน':'มอบหมายงานใหม่',student:'เพิ่มนักเรียน',enrollment:'แก้ไขข้อมูลในรายวิชานี้',review:'ตรวจงานและให้คะแนน',submit:'ส่งงาน',password:'เปลี่ยนรหัสผ่าน',reset:'ตั้งรหัสผ่านชั่วคราว'};
 const input=(name:string,label:string,options:any={})=><label key={name}>{label}<Input name={name} required={options.required!==false} {...options}/></label>;
 const files=state?.files.filter(f=>f.assignment_id===(assignment?.id||item?.assignment_id)&&(kind==='review'?f.student_id===item?.student_id&&f.revision===item?.revision:f.student_id===null))||[];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const val=(k:string)=>String(form.get(k)||'');const num=(k:string)=>Number(val(k));const nullable=(k:string)=>val(k)===''?null:num(k);try{let r;
  if(kind==='period')r=await api('periods',{year:num('year'),term:num('term')});
  if(kind==='course')r=await api(item?`courses/${item.id}`:'courses',{periodId,code:val('code'),name:val('name'),classroom:val('classroom'),workWeight:num('workWeight'),midWeight:num('midWeight'),finalWeight:num('finalWeight')},item?'PATCH':'POST');
  if(kind==='assignment'){r=await api(item?`assignments/${item.id}`:'assignments',{courseId:course!.id,title:val('title'),description:val('description'),maxScore:num('maxScore'),dueAt:dueISO(val('dueAt'))},item?'PATCH':'POST');if(form.getAll('files').some(f=>f instanceof File&&f.size)){const attachment=new FormData();attachment.set('assignmentId',item?.id||r.id);form.getAll('files').forEach(f=>{if(f instanceof File&&f.size)attachment.append('files',f);});try{await api('samples',attachment);}catch(err){await onDone(r);setError(`บันทึกงานแล้ว แต่แนบไฟล์ไม่สำเร็จ: ${err instanceof Error?err.message:''} ปิดหน้าต่างแล้วเลือกแก้ไขงานเพื่อแนบใหม่`);setBusy(false);return;}}}
  if(kind==='student')r=await api('students',{courseId:course!.id,code:val('code'),name:val('name'),number:num('number'),password:val('password')});
  if(kind==='enrollment')r=await api(`enrollments/${item!.id}`,{name:val('name'),number:num('number'),active:form.get('active')==='on'},'PATCH');
  if(kind==='review')r=await api(`review/${item!.id}`,{score:nullable('score'),feedback:val('feedback'),revision:item!.revision,returned:form.get('returned')==='on'},'PATCH');
  if(kind==='submit'){form.set('assignmentId',assignment!.id);r=await api('submit',form);}
  if(kind==='password'){if(val('password')!==val('confirm'))throw new Error('รหัสผ่านใหม่สองช่องไม่ตรงกัน');r=await api('password',{oldPassword:val('oldPassword'),password:val('password')});}
  if(kind==='reset')r=await api(`enrollments/${item!.id}`,{resetPassword:true,password:val('password')},'PATCH');
  await onDone(r);onClose();
 }catch(err){setError(err instanceof Error?err.message:'ทำรายการไม่สำเร็จ');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{titles[kind]}</DialogTitle><DialogDescription>{kind==='enrollment'?'การแก้ข้อมูลนี้ไม่เปลี่ยนรายชื่อในเทอมเก่า':kind==='review'?`${assignment?.title||''} · งานรอบที่ ${item?.revision}`:kind==='submit'?`${assignment?.title} · คะแนนเต็ม ${assignment?.max_score}`:kind==='period'?'ข้อมูลของแต่ละเทอมจะจัดเก็บแยกกัน':kind==='reset'?'รหัสผ่านนี้ใช้กับนักเรียนคนเดียวกันทุกเทอม และต้องเปลี่ยนเมื่อเข้าสู่ระบบ':'กรอกข้อมูลแล้วบันทึก'}</DialogDescription></DialogHeader><form onSubmit={submit} className="form-stack">
 {kind==='period'&&<div className="form-grid">{input('year','ปีการศึกษา (พ.ศ.)',{type:'number',min:2500,max:2700,defaultValue:new Date().getFullYear()+543})}{input('term','ภาคเรียน',{type:'number',min:1,max:3,defaultValue:1})}</div>}
 {kind==='course'&&<>{input('code','รหัสวิชา',{defaultValue:item?.code,placeholder:'เช่น ว21101',maxLength:30})}{input('name','ชื่อรายวิชา',{defaultValue:item?.name,placeholder:'เช่น วิทยาศาสตร์',maxLength:100})}{input('classroom','ชั้น / ห้อง',{defaultValue:item?.classroom,placeholder:'เช่น ม.1/1',maxLength:40})}<p className="muted">คะแนนทั้งสามส่วนต้องรวมเป็น 100 คะแนน</p><div className="form-grid three">{input('workWeight','คะแนนเก็บ',{type:'number',min:0,max:100,step:.1,defaultValue:item?.work_weight??60})}{input('midWeight','กลางภาค',{type:'number',min:0,max:100,step:.1,defaultValue:item?.mid_weight??20})}{input('finalWeight','ปลายภาค',{type:'number',min:0,max:100,step:.1,defaultValue:item?.final_weight??20})}</div></>}
 {kind==='assignment'&&<>{input('title','ชื่องาน',{defaultValue:item?.title,maxLength:150})}<label>คำชี้แจง / ตัวอย่างงาน<Textarea name="description" rows={4} defaultValue={item?.description} maxLength={10000}/></label><div className="form-grid">{input('maxScore','คะแนนเต็ม',{type:'number',min:.1,max:1000,step:.1,defaultValue:item?.max_score??10})}{input('dueAt','กำหนดส่ง (เวลาไทย)',{type:'datetime-local',defaultValue:item?localDue(item.due_at):new Date(Date.now()+7*3600000+7*86400000).toISOString().slice(0,16)})}</div><label>ไฟล์โจทย์ / ตัวอย่างงาน<Input name="files" type="file" accept="image/jpeg,image/png,image/webp,.pdf,.docx,.xlsx" multiple/></label><p className="muted">ไม่เกิน 5 ไฟล์ ไฟล์ละ 10 MB รวม 25 MB · ไฟล์เดิมยังเก็บอยู่</p>{item&&<FileLinks files={state?.files.filter(f=>f.assignment_id===item.id&&!f.student_id)||[]}/>}</>}
 {kind==='student'&&<>{input('code','รหัสนักเรียน (ชื่อผู้ใช้)',{maxLength:40,placeholder:'เช่น 12345'})}{input('name','ชื่อ–นามสกุล',{maxLength:100})}{input('number','เลขที่',{type:'number',min:1,max:999,defaultValue:(state?.enrollments.filter(e=>e.course_id===course?.id).length||0)+1})}{input('password','รหัสผ่านชั่วคราว (เว้นว่างเพื่อสร้างอัตโนมัติ)',{type:'text',required:false,minLength:10,maxLength:128})}<p className="muted">รหัสนักเรียนที่มีบัญชีอยู่แล้วจะใช้บัญชีเดิม และเพิ่มเฉพาะการลงทะเบียนวิชานี้</p></>}
 {kind==='enrollment'&&<>{input('name','ชื่อ–นามสกุลในเทอมนี้',{defaultValue:item?.name,maxLength:100})}{input('number','เลขที่',{type:'number',min:1,max:999,defaultValue:item?.number})}<label className="check-label"><Checkbox name="active" defaultChecked={!!item?.active}/> ลงทะเบียนอยู่ในรายวิชานี้</label><p className="muted">ยกเลิกเครื่องหมายเพื่อพักการลงทะเบียน ประวัติงานและคะแนนยังเก็บอยู่</p></>}
 {kind==='review'&&<><Images files={files}/><FileLinks files={files}/>{item?.note&&<div className="notice">{item.note}</div>}{input('score',`คะแนน (เต็ม ${assignment?.max_score})`,{type:'number',min:0,max:assignment?.max_score,step:.01,defaultValue:item?.score??'',required:false})}<label>ข้อเสนอแนะ<Textarea name="feedback" rows={4} defaultValue={item?.feedback} maxLength={5000}/></label><label className="check-label"><Checkbox name="returned"/> ส่งคืนให้นักเรียนแก้ไขและส่งใหม่</label><p className="muted">เมื่อส่งคืน คะแนนรอบนี้จะถูกยกเลิกจนกว่าจะตรวจงานที่แก้ไขแล้ว</p>{state?.files.some(f=>f.assignment_id===item?.assignment_id&&f.student_id===item?.student_id&&f.revision!==item?.revision)&&<details><summary>ไฟล์จากรอบก่อนหน้า</summary><FileLinks files={state.files.filter(f=>f.assignment_id===item?.assignment_id&&f.student_id===item?.student_id&&f.revision!==item?.revision)}/></details>}</>}
 {kind==='submit'&&<>{assignment?.description&&<p className="notice whitespace-pre-wrap">{assignment.description}</p>}<FileLinks files={files}/><label>รูปงาน / ไฟล์งาน<Input name="files" type="file" accept="image/jpeg,image/png,image/webp,.pdf,.docx,.xlsx" multiple required/></label><p className="muted">ถ่ายรูปแล้วเลือกไฟล์ได้ · ไม่เกิน 5 ไฟล์ ไฟล์ละ 10 MB รวม 25 MB</p><label>ข้อความถึงครู<Textarea name="note" rows={3} maxLength={3000}/></label></>}
 {kind==='password'&&<>{input('oldPassword','รหัสผ่านเดิม',{type:'password',autoComplete:'current-password'})}{input('password','รหัสผ่านใหม่',{type:'password',minLength:10,maxLength:128,autoComplete:'new-password'})}{input('confirm','ยืนยันรหัสผ่านใหม่',{type:'password',minLength:10,maxLength:128,autoComplete:'new-password'})}</>}
 {kind==='reset'&&<>{input('password','รหัสผ่านชั่วคราว',{type:'text',minLength:10,maxLength:128,defaultValue:`Gr-${crypto.randomUUID().slice(0,12)}`})}</>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" onClick={onClose} disabled={busy}>ยกเลิก</Button><BusyButton type="submit" busy={busy}>{kind==='submit'?'ส่งงาน':kind==='review'?'บันทึกผลตรวจ':'บันทึก'}</BusyButton></div></form></DialogContent></Dialog>;
}

