'use client';
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { api,localDue,dueISO,type AppState,type Row } from '@/lib/client';
import {RubricEditor,RubricScores} from './rubric';
import {ImageReview} from './image-review';
import {parseRubric,rubricScore} from '@/lib/rubrics';
import {workBudgets} from '@/lib/grades';
import { BusyButton,FileLinks,Images } from './shared';
export type Edit={kind:'file'|'profile'|'subject'|'studentAccount'|'period'|'course'|'assignment'|'student'|'enrollment'|'review'|'submit'|'password'|'reset'|'paper';queue?:string[];item?:Row;course?:Row;assignment?:Row};
export function Editor({edit,state,periodId,onClose,onDone}:{edit:Edit;state:AppState|null;periodId:string;onClose:()=>void;onDone:(r:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const {kind,item,course,assignment}=edit;
 const [workWeight,setWorkWeight]=useState(Number(item?.work_weight??60)),[beforeWeight,setBeforeWeight]=useState(workBudgets(item??{work_weight:60}).before);
 const [targetRooms,setTargetRooms]=useState<string[]>(course?[course.id]:[]);
 const siblingRooms=state?.courses.filter(c=>c.subject_id===course?.subject_id&&c.can_edit&&!c.archived)||[];
 const [returned,setReturned]=useState(false);const [rubric,setRubric]=useState(()=>parseRubric(item?.rubric)),[scores,setScores]=useState<number[]>(()=>{try{return JSON.parse(item?.rubric_scores||'[]');}catch{return [];}});const criteria=parseRubric(assignment?.rubric);
 const titles={file:'แก้ไขชื่อไฟล์',profile:'แก้ไขชื่อแบบส่งออก SGS',subject:'แก้ไขชื่อและรหัสวิชา',studentAccount:'แก้ไขชื่อบัญชีนักเรียน',paper:'คะแนนงานที่ส่งในห้องเรียน',period:item?'แก้ไขปีการศึกษา / ภาคเรียน':'เพิ่มปีการศึกษา / ภาคเรียน',course:item?'แก้ไขรายวิชา':'สร้างรายวิชา',assignment:item?'แก้ไขงาน':'มอบหมายงานใหม่',student:'เพิ่มนักเรียน',enrollment:'แก้ไขข้อมูลในรายวิชานี้',review:'ตรวจงานและให้คะแนน',submit:'ส่งงาน',password:'เปลี่ยนรหัสผ่าน',reset:'คืนรหัสผ่านเริ่มต้น'};
 const input=(name:string,label:string,options:any={})=><label key={name}>{label}<Input name={name} required={options.required!==false} {...options}/></label>;
 const reviewStudent=state?.enrollments.find(e=>e.course_id===course?.id&&e.student_id===item?.student_id);
 const files=state?.files.filter(f=>f.assignment_id===(assignment?.id||item?.assignment_id)&&(kind==='review'?f.student_id===item?.student_id&&f.revision===item?.revision:f.student_id===null))||[];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const val=(k:string)=>String(form.get(k)||'');const num=(k:string)=>Number(val(k));const nullable=(k:string)=>val(k)===''?null:num(k);try{let r;
  if(kind==='file')r=await api(`files/${item!.id}`,{name:val('name')},'PATCH');
  if(kind==='profile')r=await api(`sgs-profiles/${item!.id}`,{name:val('name')},'PATCH');
  if(kind==='subject')r=await api(`subjects/${item!.id}`,{code:val('code'),name:val('name')},'PATCH');
  if(kind==='studentAccount')r=await api(`student-accounts/${item!.id}`,{name:val('name')},'PATCH');
  if(kind==='period')r=await api(item?`periods/${item.id}`:'periods',{year:num('year'),term:num('term')},item?'PATCH':'POST');
  if(kind==='course')r=await api(item?`courses/${item.id}`:'courses',{periodId,code:val('code'),name:val('name'),classroom:val('classroom'),classrooms:!item?val('classroom').split(/[,\n]+/).map(s=>s.trim()).filter(Boolean):undefined,workWeight:num('workWeight'),beforeWorkWeight:num('beforeWorkWeight'),midWeight:num('midWeight'),finalWeight:num('finalWeight')},item?'PATCH':'POST');
  if(kind==='assignment'){if(!item&&!targetRooms.length)throw new Error('เลือกห้องเรียนอย่างน้อยหนึ่งห้อง');r=await api(item?`assignments/${item.id}`:'assignments',{courseId:course!.id,courseIds:!item?targetRooms:undefined,title:val('title'),description:val('description'),maxScore:num('maxScore'),workPhase:val('workPhase'),dueAt:dueISO(val('dueAt')),rubric},item?'PATCH':'POST');if(form.getAll('files').some(f=>f instanceof File&&f.size)){const attachment=new FormData();attachment.set('assignmentId',item?.id||r.id);if(!item&&r.assignmentIds)attachment.set('assignmentIds',JSON.stringify(r.assignmentIds));form.getAll('files').forEach(f=>{if(f instanceof File&&f.size)attachment.append('files',f);});try{await api('samples',attachment);}catch(err){await onDone(r);setError(`บันทึกงานแล้ว แต่แนบไฟล์ไม่สำเร็จ: ${err instanceof Error?err.message:''} ปิดหน้าต่างแล้วเลือกแก้ไขงานเพื่อแนบใหม่`);setBusy(false);return;}}}
  if(kind==='student')r=await api('students',{courseId:course!.id,code:val('code'),name:val('name'),number:num('number')});
  if(kind==='enrollment')r=await api(`enrollments/${item!.id}`,{name:val('name'),number:num('number'),active:form.get('active')==='on'},'PATCH');
  if(kind==='review')r=await api(`review/${item!.id}`,{score:form.get('returned')==='on'?null:criteria.length?rubricScore(criteria,scores):nullable('score'),rubricScores:scores,feedback:val('feedback'),revision:item!.revision,expectedReviewedAt:item!.reviewed_at??null,expectedRubric:assignment!.rubric,returned:form.get('returned')==='on'},'PATCH');
  if(kind==='paper')r=await api('paper-grade',{assignmentId:assignment!.id,studentId:item!.student_id,score:criteria.length?rubricScore(criteria,scores):nullable('score'),rubricScores:scores,feedback:val('feedback')});
  if(kind==='submit'){form.set('assignmentId',assignment!.id);r=await api('submit',form);}
  if(kind==='password'){if(val('password')!==val('confirm'))throw new Error('รหัสผ่านใหม่สองช่องไม่ตรงกัน');r=await api('password',{oldPassword:val('oldPassword'),password:val('password')});}
  if(kind==='reset')r=await api(`enrollments/${item!.id}`,{resetPassword:true},'PATCH');
  const next=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('data-next')==='true';await onDone({...r,celebrate:kind==='submit'?{title:assignment!.title,courseId:assignment!.course_id}:undefined,reviewNext:next});if(!next)onClose();
 }catch(err){setError(err instanceof Error?err.message:'ทำรายการไม่สำเร็จ');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{titles[kind]}</DialogTitle><DialogDescription>{kind==='enrollment'?'การแก้ข้อมูลนี้ไม่เปลี่ยนรายชื่อในเทอมเก่า':kind==='review'?`${reviewStudent?.number||''}. ${reviewStudent?.name||''} · ${assignment?.title||''} · งานรอบที่ ${item?.revision}`:kind==='submit'?`${assignment?.title} · คะแนนเต็ม ${assignment?.max_score}`:kind==='period'?'ข้อมูลของแต่ละเทอมจะจัดเก็บแยกกัน':kind==='reset'?'คืนรหัสผ่านเป็นรหัสนักเรียน ใช้บัญชีเดียวกันทุกเทอม นักเรียนเลือกเปลี่ยนภายหลังได้':'กรอกข้อมูลแล้วบันทึก'}</DialogDescription></DialogHeader><form onSubmit={submit} className="form-stack">
 {['file','profile','subject','studentAccount'].includes(kind)&&<>{kind==='subject'&&input('code','รหัสวิชา',{defaultValue:item?.code,maxLength:30})}{input('name',kind==='file'?'ชื่อไฟล์':'ชื่อ',{defaultValue:item?.name,maxLength:kind==='file'?200:100})}{kind==='studentAccount'&&<p className='muted'>ชื่อผู้ใช้ {item?.username} · เปลี่ยนชื่อบัญชีเท่านั้น รายชื่อในแต่ละเทอมแก้จากประเภทการลงทะเบียน</p>}</>}
 {kind==='period'&&<div className="form-grid">{input('year','ปีการศึกษา (พ.ศ.)',{type:'number',min:2500,max:2700,defaultValue:item?.year??new Date().getFullYear()+543})}{input('term','ภาคเรียน',{type:'number',min:1,max:3,defaultValue:item?.term??1})}</div>}
 {kind==='course'&&<>{input('code','รหัสวิชา',{defaultValue:item?.code,readOnly:!!item?.subject_id,placeholder:'เช่น ว21101',maxLength:30})}{input('name','ชื่อรายวิชา',{defaultValue:item?.name,readOnly:!!item?.subject_id,placeholder:'เช่น วิทยาศาสตร์',maxLength:100})}{input('classroom',item?'ชั้น / ห้อง':'ห้องเรียน (เพิ่มได้หลายห้อง คั่นด้วยจุลภาค)',{defaultValue:item?.classroom,placeholder:item?'เช่น ม.1/1':'ม.1/1, ม.1/2, ม.1/3',maxLength:item?40:2000})}<p className="muted">{item?.subject_id?'ชื่อและรหัสใช้ร่วมทุกห้อง แก้ได้จากปุ่ม “แก้ชื่อวิชา” · สัดส่วนด้านล่างใช้สำหรับห้องนี้ และต้องรวมเป็น 100 คะแนน':'คะแนนทั้งสามส่วนต้องรวมเป็น 100 คะแนน ทุกห้องใหม่จะเริ่มด้วยสัดส่วนนี้'}</p><div className="form-grid three">{input('workWeight','คะแนนเก็บ',{type:'number',min:0,max:100,step:.1,value:workWeight,onChange:(e:React.ChangeEvent<HTMLInputElement>)=>{const n=Number(e.target.value);setWorkWeight(n);setBeforeWeight(Math.min(beforeWeight,n));}})}{input('midWeight','กลางภาค',{type:'number',min:0,max:100,step:.1,defaultValue:item?.mid_weight??20})}{input('finalWeight','ปลายภาค',{type:'number',min:0,max:100,step:.1,defaultValue:item?.final_weight??20})}</div></>}
 {kind==='assignment'&&<>{!item&&siblingRooms.length>1&&<fieldset className='room-targets'><legend>มอบหมายให้ห้องเรียน</legend><p className='muted'>เลือกได้หลายห้อง งานและคะแนนของแต่ละห้องแยกกัน</p>{siblingRooms.map(c=><label className='check-label' key={c.id}><Checkbox checked={targetRooms.includes(c.id)} onCheckedChange={v=>setTargetRooms(old=>v===true?[...old,c.id]:old.filter(id=>id!==c.id))}/>{c.classroom}</label>)}</fieldset>}<label>ช่วงงาน<select className='phase-select' name='workPhase' defaultValue={item?.work_phase??'before'}><option value='before'>ก่อนกลางภาค</option><option value='after'>หลังกลางภาค</option></select></label><p className='muted'>คะแนนเก็บก่อนกลางภาค {workBudgets(course).before} · หลังกลางภาค {workBudgets(course).after} คะแนน</p>{input('title','ชื่องาน',{defaultValue:item?.title,maxLength:150})}<label>คำชี้แจง / ตัวอย่างงาน<Textarea name="description" rows={4} defaultValue={item?.description} maxLength={10000}/></label><div className="form-grid">{input('maxScore','คะแนนเต็ม',{type:'number',min:.1,max:1000,step:.1,defaultValue:item?.max_score??10})}{input('dueAt','กำหนดส่ง (เวลาไทย)',{type:'datetime-local',defaultValue:item?localDue(item.due_at):new Date(Date.now()+7*3600000+7*86400000).toISOString().slice(0,16)})}</div><RubricEditor value={rubric} onChange={setRubric}/><label>ไฟล์โจทย์ / ตัวอย่างงาน<Input name="files" type="file" accept="image/jpeg,image/png,image/webp,.pdf,.docx,.xlsx" multiple/></label><p className="muted">ไม่เกิน 5 ไฟล์ ไฟล์ละ 10 MB รวม 25 MB · ไฟล์เดิมยังเก็บอยู่</p>{item&&<FileLinks editable files={state?.files.filter(f=>f.assignment_id===item.id&&!f.student_id)||[]}/>}</>}
 {kind==='student'&&<>{input('code','รหัสนักเรียน (ชื่อผู้ใช้)',{maxLength:40,placeholder:'เช่น 12345'})}{input('name','ชื่อ–นามสกุล',{maxLength:100})}{input('number','เลขที่',{type:'number',min:1,max:999,defaultValue:(state?.enrollments.filter(e=>e.course_id===course?.id).length||0)+1})}<p className="notice">บัญชีใหม่ใช้รหัสนักเรียนเป็นทั้งชื่อผู้ใช้และรหัสผ่านเริ่มต้น นักเรียนเลือกเปลี่ยนรหัสผ่านเองได้</p><p className="muted">รหัสนักเรียนที่มีบัญชีอยู่แล้วจะใช้บัญชีเดิม และเพิ่มเฉพาะการลงทะเบียนวิชานี้</p></>}
 {kind==='enrollment'&&<>{input('name','ชื่อ–นามสกุลในเทอมนี้',{defaultValue:item?.name,maxLength:100})}{input('number','เลขที่',{type:'number',min:1,max:999,defaultValue:item?.number})}<label className="check-label"><Checkbox name="active" defaultChecked={!!item?.active}/> ลงทะเบียนอยู่ในรายวิชานี้</label><p className="muted">ยกเลิกเครื่องหมายเพื่อพักการลงทะเบียน ประวัติงานและคะแนนยังเก็บอยู่</p></>}
 {kind==='review'&&<><ImageReview files={files} submission={item!}/><FileLinks editable files={files}/>{item?.note&&<div className="notice">{item.note}</div>}{criteria.length?<RubricScores rubric={criteria} value={scores} onChange={setScores} required={!returned}/>:input('score',`คะแนน (เต็ม ${assignment?.max_score})`,{type:'number',min:0,max:assignment?.max_score,step:.01,defaultValue:item?.score??'',required:false})}<div className='row'>{['ทำได้ครบถ้วน เก่งมาก','ตรวจคำตอบอีกครั้ง','เพิ่มคำอธิบายขั้นตอน','รูปไม่ชัด กรุณาถ่ายใหม่'].map(text=><Button key={text} type='button' variant='outline' size='sm' onClick={e=>{const area=e.currentTarget.form?.elements.namedItem('feedback') as HTMLTextAreaElement;area.value+=(area.value?'\n':'')+text;}}>{text}</Button>)}</div><label>ข้อเสนอแนะ<Textarea name="feedback" rows={4} defaultValue={item?.feedback} maxLength={5000}/></label><label className="check-label"><Checkbox name="returned" checked={returned} onCheckedChange={v=>setReturned(v===true)}/> ส่งคืนให้นักเรียนแก้ไขและส่งใหม่</label><p className="muted">เมื่อส่งคืน คะแนนรอบนี้จะถูกยกเลิกจนกว่าจะตรวจงานที่แก้ไขแล้ว</p>{state?.files.some(f=>f.assignment_id===item?.assignment_id&&f.student_id===item?.student_id&&f.revision!==item?.revision)&&<details><summary>ไฟล์จากรอบก่อนหน้า</summary><FileLinks files={state.files.filter(f=>f.assignment_id===item?.assignment_id&&f.student_id===item?.student_id&&f.revision!==item?.revision)}/></details>}</>}
 {kind==='paper'&&<><p className='notice'>บันทึกให้นักเรียน {item?.name} · นับเป็นงานส่งในห้องเรียน</p>{criteria.length?<RubricScores rubric={criteria} value={scores} onChange={setScores} required={!returned}/>:input('score',`คะแนน / ${assignment?.max_score}`,{type:'number',min:0,max:assignment?.max_score,step:.01})}<label>ข้อเสนอแนะ<Textarea name='feedback' rows={3}/></label></>}
 {kind==='submit'&&<>{assignment?.description&&<p className="notice whitespace-pre-wrap">{assignment.description}</p>}<FileLinks files={files}/><label>รูปงาน / ไฟล์งาน<Input name="files" type="file" accept="image/jpeg,image/png,image/webp,.pdf,.docx,.xlsx" multiple required/></label><p className="muted">ถ่ายรูปแล้วเลือกไฟล์ได้ · ไม่เกิน 5 ไฟล์ ไฟล์ละ 10 MB รวม 25 MB</p><label>ข้อความถึงครู<Textarea name="note" rows={3} maxLength={3000}/></label></>}
 {kind==='password'&&<>{input('oldPassword','รหัสผ่านเดิม',{type:'password',autoComplete:'current-password'})}{input('password','รหัสผ่านใหม่',{type:'password',minLength:10,maxLength:128,autoComplete:'new-password'})}{input('confirm','ยืนยันรหัสผ่านใหม่',{type:'password',minLength:10,maxLength:128,autoComplete:'new-password'})}</>}
 {kind==='reset'&&<><p className="notice">ชื่อผู้ใช้และรหัสผ่านเริ่มต้น: <strong>{item?.student_code}</strong></p><p className="muted">เมื่อบันทึก ระบบจะออกจากบัญชีนี้บนทุกอุปกรณ์ นักเรียนเข้าสู่ระบบด้วยรหัสนักเรียนและเปลี่ยนรหัสผ่านภายหลังได้</p></>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" onClick={onClose} disabled={busy}>ยกเลิก</Button>{kind==='review'&&edit.queue&&edit.queue.length>1&&<BusyButton type='submit' data-next='true' busy={busy}>บันทึกแล้วตรวจคนถัดไป</BusyButton>}<BusyButton type="submit" busy={busy}>{kind==='submit'?'ส่งงาน':kind==='review'?'บันทึกผลตรวจ':'บันทึก'}</BusyButton></div></form></DialogContent></Dialog>;
}

