'use client';
import {useEffect,useState} from 'react';
import {api,type Row} from '@/lib/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export function GroupPicker({assignment,userId,closed,onChange,readOnly=false}:{assignment:Row;userId:string;closed:boolean;onChange:()=>Promise<any>;readOnly?:boolean}){
 const [groups,setGroups]=useState<Row[]>([]),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>setGroups((await api(`groups/${assignment.id}`)).groups);
 useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>void load().catch(()=>{}),15000);return()=>clearInterval(timer);},[assignment.id]);
 const own=groups.find(g=>g.members.some((m:Row)=>m.student_id===userId));
 const run=async(op:string,body:any={})=>{setBusy(true);setError('');try{await api(`groups/${assignment.id}/${op}`,body);await load();await onChange();setName('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className='group-picker' aria-label={`กลุ่มของงาน ${assignment.title}`}><strong>งานกลุ่ม · ไม่เกิน {assignment.group_max} คน</strong><p className='muted'>{readOnly?'รายชื่อกลุ่มที่นักเรียนจัดเอง · ตรวจหนึ่งครั้งได้คะแนนสมาชิกทุกคน':'เลือกกลุ่มเองได้ คนใดคนหนึ่งส่งงานให้ทุกคน คะแนนและข้อเสนอแนะใช้ร่วมกัน'}</p>{own?<><p><strong>กลุ่มของฉัน: {own.name}</strong> · {own.member_count} คน</p><ul>{own.members.map((m:Row)=><li key={m.student_id}>{m.number}. {m.name}{m.student_id===own.leader_id?' (หัวหน้ากลุ่ม)':''}</li>)}</ul>{own.sealed?<p className='notice'>ส่งงานแล้ว ล็อกรายชื่อสมาชิก · เมื่อครูส่งคืน สมาชิกคนใดก็ส่งงานแก้ไขให้ทั้งกลุ่มได้</p>:!closed&&<><div className='row'>{own.leader_id===userId&&<><Input aria-label='ชื่อกลุ่มใหม่' value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder='ชื่อกลุ่มใหม่'/><Button variant='outline' disabled={busy||!name.trim()} onClick={()=>void run('rename',{name})}>แก้ชื่อกลุ่ม</Button></>}<Button variant='outline' disabled={busy} onClick={()=>void run('leave')}>ออกจากกลุ่ม</Button></div>{own.leader_id===userId&&own.member_count>1&&<p className='muted'>หัวหน้ากลุ่มออกได้เมื่อสมาชิกคนอื่นออกครบแล้ว</p>}</>}</>:<>{!closed&&!readOnly&&<div className='row'><Input aria-label={`ชื่อกลุ่มใหม่ ${assignment.title}`} value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder='ตั้งชื่อกลุ่มของฉัน'/><Button disabled={busy||!name.trim()} onClick={()=>void run('create',{name})}>สร้างกลุ่ม</Button></div>}{!groups.length&&<p className='muted'>ยังไม่มีกลุ่มสำหรับงานนี้</p>}{groups.map(g=><div className='group-option' key={g.id}><div><strong>{g.name}</strong><span className='muted'> {g.member_count} / {assignment.group_max} คน</span><p className='muted'>{g.members.map((m:Row)=>m.name).join(', ')}</p></div>{!readOnly&&<Button size='sm' variant='outline' disabled={busy||closed||!!g.sealed||g.member_count>=assignment.group_max} onClick={()=>void run('join',{groupId:g.id})}>{g.sealed?'ส่งงานแล้ว':g.member_count>=assignment.group_max?'กลุ่มเต็ม':'เข้าร่วม'}</Button>}</div>)}</>}{error&&<p className='error' role='alert'>{error}</p>}</section>;
}
