'use client';
import {useEffect,useRef,useState} from 'react';
import {RotateCw,ZoomIn,ZoomOut,Undo2,Save,PenLine,Type} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,type Row} from '@/lib/client';
import {BusyButton,Choice} from './shared';
export function ImageReview({files,submission}:{files:Row[];submission:Row}){
 const images=files.filter(f=>f.mime.startsWith('image/')&&f.kind!=='feedback');const [selected,setSelected]=useState(images[0]?.id||''),[zoom,setZoom]=useState(1),[color,setColor]=useState('#e33155'),[mode,setMode]=useState('pen'),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ready,setReady]=useState(false);const canvas=useRef<HTMLCanvasElement>(null),image=useRef<HTMLImageElement|null>(null),drawing=useRef(false),last=useRef<[number,number]|null>(null);const file=images.find(f=>f.id===selected);
 function reset(){const c=canvas.current,img=image.current;if(!c||!img)return;const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);setZoom(1);setMessage('');}
 useEffect(()=>{setReady(false);setMessage('');if(!file)return;let active=true;const img=new Image();img.onload=()=>{if(active){image.current=img;reset();setReady(true);}};img.onerror=()=>{if(active)setMessage('โหลดรูปไม่สำเร็จ กรุณาเปิดไฟล์หรือเลือกใหม่');};img.src=`/api/file/${file.id}`;return()=>{active=false;};},[selected]);
 function point(e:React.PointerEvent<HTMLCanvasElement>):[number,number]{const c=canvas.current!,rect=c.getBoundingClientRect();return [(e.clientX-rect.left)*c.width/rect.width,(e.clientY-rect.top)*c.height/rect.height];}
 function start(e:React.PointerEvent<HTMLCanvasElement>){if(!ready||mode==='pan')return;const c=canvas.current!,ctx=c.getContext('2d')!,[x,y]=point(e);c.setPointerCapture(e.pointerId);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=Math.max(3,c.width/300);ctx.lineCap='round';if(mode==='text'){if(text.trim()){ctx.font=`bold ${Math.max(24,c.width/30)}px Tahoma`;ctx.fillText(text,x,y);}return;}drawing.current=true;last.current=[x,y];ctx.beginPath();ctx.arc(x,y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill();}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current||!last.current)return;const ctx=canvas.current!.getContext('2d')!,p=point(e);ctx.beginPath();ctx.moveTo(...last.current);ctx.lineTo(...p);ctx.stroke();last.current=p;}
 function rotate(){const c=canvas.current!;const copy=document.createElement('canvas');copy.width=c.width;copy.height=c.height;copy.getContext('2d')!.drawImage(c,0,0);c.width=copy.height;c.height=copy.width;const ctx=c.getContext('2d')!;ctx.translate(c.width,0);ctx.rotate(Math.PI/2);ctx.drawImage(copy,0,0);ctx.setTransform(1,0,0,1,0,0);}
 async function save(){setBusy(true);setMessage('');try{const blob=await new Promise<Blob>((resolve,reject)=>canvas.current!.toBlob(b=>b?resolve(b):reject(Error('สร้างรูปไม่ได้')),'image/png'));const form=new FormData();form.set('submissionId',submission.id);form.set('revision',String(submission.revision));form.append('file',blob,`รอบ${submission.revision}.png`);await api('feedback-image',form);setMessage('บันทึกรูปคำแนะนำแล้ว นักเรียนเปิดดูได้ในงานนี้');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!images.length)return null;
 return <section className="image-review"><div className="row"><Choice label="รูปที่จะตรวจ" value={selected} onChange={v=>{if(message.includes('บันทึก'))setMessage('');setSelected(v);}} options={images.map(f=>({value:f.id,label:f.name}))}/><Button type="button" size="icon" variant="outline" aria-label="ขยายรูป" onClick={()=>setZoom(z=>Math.min(3,z+.25))}><ZoomIn size={16}/></Button><Button type="button" size="icon" variant="outline" aria-label="ย่อรูป" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><ZoomOut size={16}/></Button><Button type="button" size="icon" variant="outline" aria-label="หมุนรูป" disabled={!ready} onClick={rotate}><RotateCw size={16}/></Button><Button type="button" size="icon" variant="outline" aria-label="ล้างรอยเขียน" disabled={!ready} onClick={reset}><Undo2 size={16}/></Button></div><div className="annotation-tools row"><Button type="button" size="sm" variant={mode==='pen'?'default':'outline'} onClick={()=>setMode('pen')}><PenLine size={15}/> ปากกา</Button><Button type="button" size="sm" variant={mode==='text'?'default':'outline'} onClick={()=>setMode('text')}><Type size={15}/> ข้อความ</Button><Button type='button' size='sm' variant={mode==='pan'?'default':'outline'} onClick={()=>setMode('pan')}>เลื่อนรูป</Button><label>สี<Input type="color" aria-label="สีปากกา" value={color} onChange={e=>setColor(e.target.value)}/></label>{mode==='text'&&<Input aria-label="ข้อความเขียนบนรูป" placeholder="พิมพ์คำแนะนำ แล้วแตะบนรูป" value={text} onChange={e=>setText(e.target.value)} maxLength={100}/>}</div><div className="annotation-viewport"><canvas ref={canvas} aria-label="รูปงานสำหรับเขียนคำแนะนำ" style={{width:`${zoom*100}%`,touchAction:mode==='pan'?'auto':'none'}} onPointerDown={start} onPointerMove={move} onPointerUp={()=>{drawing.current=false;last.current=null;}} onPointerCancel={()=>{drawing.current=false;last.current=null;}}/></div><div className="row"><BusyButton type="button" busy={busy} disabled={!ready} onClick={save}><Save size={16}/> บันทึกรูปคำแนะนำ</BusyButton><span className="muted">เก็บเป็นรูปใหม่ งานต้นฉบับยังอยู่</span></div>{message&&<p role="status" className="notice">{message}</p>}</section>;
}
