'use client';
import {useEffect,useState} from 'react';
import {Sparkles,ArrowRight,Palette,Target} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {AppState,Row} from '@/lib/client';
import {dateThai} from '@/lib/client';
import {studentJourney} from '@/lib/student-journey';
import './student-journey.css';

const themes=[{id:'meadow',name:'สวนยามเช้า',xp:0},{id:'sunset',name:'สวนอาทิตย์ตก',xp:60},{id:'moon',name:'สวนใต้แสงดาว',xp:150}];
export function StudentJourney({state,courses,onTask}:{state:AppState;courses:Row[];onTask:(assignment:Row)=>void}){
 const [time,setTime]=useState(Date.now),[theme,setTheme]=useState('meadow'),[palette,setPalette]=useState(false);
 const scope=courses.map(c=>c.period_id).sort()[0]||'none',key=`grade-garden:${state.user.id}:${scope}`;
 useEffect(()=>{try{setTheme(localStorage.getItem(key)||'meadow');}catch{}},[key]);
 useEffect(()=>{const timer=setInterval(()=>setTime(Date.now()),60000);return ()=>clearInterval(timer);},[]);
 const j=studentJourney(state,courses,time),chosen=themes.find(t=>t.id===theme&&t.xp<=j.xp)||themes[0];
 return <section className={`student-journey garden-${chosen.id}`} aria-label='สวนภารกิจของฉัน'>
  <div className='journey-heading'><div><span className='journey-eyebrow'><Sparkles size={15}/> พื้นที่ความสำเร็จของคุณ</span><h2>อีกหนึ่งงาน อีกหนึ่งก้าว 🌱</h2><p>สะสมความพยายาม แล้วเติมสีให้สวนของคุณ</p></div><Button variant='outline' aria-expanded={palette} onClick={()=>setPalette(!palette)}><Palette size={16}/> แต่งสวน</Button></div>
  <div className='journey-overview'><div className='journey-garden' aria-hidden='true'><svg viewBox='0 0 320 175'><circle cx='263' cy='33' r='19' className='garden-sun'/><path d='M0 138 Q80 94 164 128 Q240 104 320 132 V175 H0Z' fill='#b9e7ba'/><path d='M0 158 Q150 120 320 154 V175 H0Z' fill='#83c7a0'/>{Array.from({length:Math.min(7,1+Math.floor(j.xp/25))},(_,i)=><g key={i} transform={`translate(${33+i*40},${144-i%2*10})`}><path d='M0 0 Q-5 -16 0 -35' fill='none' stroke='#397c57' strokeWidth='3'/><ellipse cx='-6' cy='-15' rx='8' ry='4' fill='#549d62' transform='rotate(30 -6 -15)'/><ellipse cx='7' cy='-22' rx='8' ry='4' fill='#549d62' transform='rotate(-30 7 -22)'/>{j.xp>=25*(i+1)?<><path d='M-10 -35 C-21 -47 -6 -52 0 -43 C4 -56 21 -47 10 -35 C17 -21 0 -20 0 -30 C-6 -20 -21 -26 -10 -35' fill={['#ffbccc','#ffdf91','#c7baff'][i%3]}/><circle cy='-35' r='5' fill='#f9ad44'/></>:<ellipse cy='-35' rx='5' ry='9' fill='#b6d86d'/>}</g>)}</svg><span>{chosen.name} · ของตกแต่งตาม XP</span></div>
   <div className='journey-level'><span className='journey-level-pill'>นักปลูกความฝัน · เลเวล {j.level}</span><strong>{j.xp} <small>XP สะสม</small></strong><div className='journey-meter' role='progressbar' aria-label='XP ไปเลเวลถัดไป' aria-valuenow={j.levelProgress} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${j.levelProgress}%`}}/></div><p>อีก {j.nextLevel} XP ถึงเลเวล {j.level+1}</p><small>ส่งงานใหม่ +20 · ตรงเวลา +5 · ส่งแก้ไขสำเร็จครั้งแรก +10<br/>นับครั้งเดียวต่องาน · XP แยกจากคะแนนวิชา</small></div></div>
  {palette&&<div className='journey-themes' aria-label='เลือกธีมสวน'>{themes.map(t=><button key={t.id} disabled={j.xp<t.xp} aria-pressed={chosen.id===t.id} onClick={()=>{setTheme(t.id);try{localStorage.setItem(key,t.id);}catch{}}}><span>{t.id==='meadow'?'🌤️':t.id==='sunset'?'🌅':'🌙'}</span><strong>{t.name}</strong><small>{j.xp<t.xp?`ปลดล็อกที่ ${t.xp} XP`:chosen.id===t.id?'กำลังใช้':'เลือกธีมนี้'}</small></button>)}</div>}
  <div className='journey-missions'><div className='journey-week'><h3><Target size={17}/> ภารกิจสัปดาห์นี้</h3><p>{dateThai(new Date(j.weekStart).toISOString())} – {dateThai(new Date(j.weekEnd-1).toISOString())}</p>{j.weekGoal>0?<><strong>{Math.min(j.weekly,j.weekGoal)} / {j.weekGoal} งาน</strong><div className='journey-meter' role='progressbar' aria-label='ภารกิจสัปดาห์นี้' aria-valuenow={Math.min(j.weekly,j.weekGoal)} aria-valuemin={0} aria-valuemax={j.weekGoal}><i style={{width:`${Math.min(100,j.weekly/j.weekGoal*100)}%`}}/></div><small>{j.weekly>=j.weekGoal?'ครบเป้าหมายแล้ว! พักและภูมิใจกับตัวเองได้เลย ✨':'ส่งงานต่างกันหรือส่งงานที่แก้ไขกลับให้ครู ทีละงานก็ได้'}</small></>:<p>ยังไม่มีงานให้ส่งในตอนนี้ กลับมาดูเมื่อครูมอบหมายงานนะ</p>}</div>
   <div className='journey-next'><span className='journey-eyebrow'>{j.next?.s?'🦋 โอกาสลองอีกครั้ง':'🌿 ก้าวถัดไปของคุณ'}</span><h3>{j.next?.a.title||(j.sent?'ส่งครบแล้ว เก่งมาก!':'สวนกำลังรอภารกิจแรก')}</h3><p>{j.next?j.next.s?'ครูให้คำแนะนำแล้ว อ่านและค่อย ๆ ปรับงานได้':`เริ่มจากงานนี้ · ${courses.find(c=>c.id===j.next!.a.course_id)?.name} · กำหนด ${Number.isFinite(j.next.due)?dateThai(new Date(j.next.due).toISOString()):'ยังไม่ระบุ'}`:'เมื่อมีงานใหม่ จะแนะนำงานถัดไปให้ที่นี่'}</p>{j.next?.s?.feedback&&<p className='journey-teacher-note'>ครูแนะนำ: {j.next.s.feedback}</p>}{j.next&&<Button onClick={()=>onTask(j.next!.a)}>{j.next.s?'ไปแก้ไขและส่งงาน':'เริ่มภารกิจนี้'}<ArrowRight size={16}/></Button>}</div></div>
  <div className='journey-badge-heading'><h3>สมุดเหรียญความสำเร็จ</h3><span>{j.badges.filter(b=>b.earned).length} / {j.badges.length} เหรียญ</span></div><div className='journey-badges'>{j.badges.map(b=><article key={b.id} className={b.earned?'earned':''}><span aria-hidden='true'>{b.icon}</span><strong>{b.name}</strong><small>{b.text}</small><span className='journey-badge-status'>{b.earned?'ได้รับแล้ว ✓':`${Math.min(b.value,b.goal)} / ${b.goal}`}</span></article>)}</div>
  <p className='journey-note'>รางวัลส่วนตัวแยกตามวิชาและเทอม · ต้นไทร 3D ยังเติบโตตามคะแนนที่ครูตรวจ · ธีมสวนจำไว้ในเบราว์เซอร์นี้</p>
 </section>;
}
