'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,Users,Sparkles,Layers} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,type AppState,type Row} from '@/lib/client';
import {subjectProgress} from '@/lib/subject-progress';
import {BusyButton} from './shared';

export function SubjectWorld({state,courses,activeId,onRoom,onSubject}:{state:AppState;courses:Row[];activeId:string;onRoom:(id:string,view?:string,filter?:string)=>void;onSubject:(id:string)=>void}){
 const subjects=state.subjects.filter(s=>courses.some(c=>c.subject_id===s.id));const signature=subjects.map(s=>s.id).join('|');
 const [position,setPosition]=useState(0),gesture=useRef<{x:number;y:number}|null>(null),swiped=useRef(false);
 useEffect(()=>{const i=subjects.findIndex(s=>s.id===activeId);if(i>=0)setPosition(i);},[activeId,signature]);
 const index=Math.min(position,subjects.length-1),focused=subjects[index];if(!focused)return null;
 const rooms=courses.filter(c=>c.subject_id===focused.id).sort((a,b)=>a.classroom.localeCompare(b.classroom,'th',{numeric:true})),progress=subjectProgress(state,rooms),student=state.user.role==='student';
 function choose(i:number){const next=(i+subjects.length)%subjects.length;setPosition(next);onSubject(subjects[next].id);}
 function open(id:string,view?:string,filter?:string){onRoom(id,view,filter);}
 function tilt(e:React.PointerEvent<HTMLButtonElement>){if(e.pointerType!=='mouse')return;const b=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',`${-(e.clientY-b.top-b.height/2)/b.height*12}deg`);e.currentTarget.style.setProperty('--tilt-y',`${(e.clientX-b.left-b.width/2)/b.width*12}deg`);}
 const firstMissing=rooms.find(c=>subjectProgress(state,[c]).missing)||rooms[0],firstPending=rooms.find(c=>subjectProgress(state,[c]).pending)||rooms[0],firstReturned=rooms.find(c=>subjectProgress(state,[c]).returned)||rooms[0];
 return <section className="subject-world world-explorer" aria-label="สำรวจรายวิชา"><div className="world-heading"><div><span className="world-kicker"><Sparkles size={16}/> พื้นที่เรียนรู้</span><h2>{student?'จักรวาลวิชาของฉัน':'สำรวจรายวิชา'}</h2></div><div className="row"><span>{subjects.length} วิชา · {courses.length} ห้อง</span>{activeId!=='all'&&<Button variant="ghost" size="sm" onClick={()=>onSubject('all')}>ดูทุกวิชา</Button>}</div></div>
 <div className="orb-stage" tabIndex={0} role="group" aria-label="เลือกวิชา ใช้ปุ่มซ้ายหรือขวาเพื่อเลื่อน" onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowRight'){e.preventDefault();choose(index+1);}if(e.key==='ArrowLeft'){e.preventDefault();choose(index-1);}}} onPointerCancel={()=>{gesture.current=null;swiped.current=false;}} onPointerDown={e=>{gesture.current={x:e.clientX,y:e.clientY};swiped.current=false;}} onPointerUp={e=>{const start=gesture.current;gesture.current=null;if(start&&Math.abs(e.clientX-start.x)>60&&Math.abs(e.clientY-start.y)<50){swiped.current=true;choose(index+(e.clientX<start.x?1:-1));}}}>
 <div className="ambient-orbs" aria-hidden="true"><i/><i/><i/><i/><i/></div>
 {subjects.length>1&&[-1,1].map(delta=>{const i=(index+delta+subjects.length)%subjects.length,s=subjects[i];return <button className={`satellite-orb satellite-${delta<0?'left':'right'} planet-${i%4}`} key={delta} onClick={()=>{if(swiped.current){swiped.current=false;return;}choose(i);}} aria-label={`เลือกวิชา ${s.code} ${s.name}`}><BookOpen size={24}/><span>{s.name}</span></button>;})}
 <div className={`focused-subject planet-${index%4}`} key={focused.id}><button className="planet-orb focused-orb" onPointerMove={tilt} onPointerLeave={e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg');}} onClick={()=>{if(swiped.current){swiped.current=false;return;}open(rooms[0].id);}} aria-label={`เปิดรายวิชา ${focused.code} ${focused.name}`}><BookOpen size={48}/><span>{focused.code}</span></button><h3>{focused.name}</h3><div className="planet-meta"><Layers size={15}/>{rooms.length} ห้อง{!student&&<><Users size={15}/>{progress.students} คน</>}</div></div>
 </div><div className="world-pagination"><Button variant="ghost" size="sm" disabled={subjects.length<2} onClick={()=>choose(index-1)}>วิชาก่อนหน้า</Button><span aria-live="polite" aria-atomic="true">{index+1} / {subjects.length} วิชา</span><Button variant="ghost" size="sm" disabled={subjects.length<2} onClick={()=>choose(index+1)}>วิชาถัดไป</Button></div>
 <div className="world-room-row"><span>เลือกห้องเรียน</span><div className="planet-rooms">{rooms.map(c=><button key={c.id} onClick={()=>open(c.id)}>{c.classroom}{!!c.archived&&' · ประวัติ'}</button>)}</div><div className="world-status"><strong>ส่งแล้ว {progress.submitted} / {progress.expected} งาน</strong><span>{progress.percentage}%</span><div className="world-status-meter" role="progressbar" aria-label="ความคืบหน้าการส่งงาน" aria-valuenow={progress.percentage} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${progress.percentage}%`}}/></div></div></div>
 <div className="world-quick-actions">{progress.pending>0&&<Button variant="outline" onClick={()=>open(firstPending.id,student?'courses':firstPending.can_edit?'review':'matrix')}>{student?'งานรอตรวจ':'ตรวจงาน'} {progress.pending} งาน</Button>}{progress.missing>0&&<Button onClick={()=>open(firstMissing.id,student?'courses':'followup',student?'missing':undefined)}>{student?'ไปส่งงาน':'ติดตามงานที่ยังไม่ส่ง'} {progress.missing} งาน</Button>}{progress.returned>0&&<Button variant="outline" onClick={()=>open(firstReturned.id,student?'courses':'followup',student?'returned':undefined)}>งานที่ต้องแก้ {progress.returned} งาน</Button>}{progress.expected>0&&!progress.missing&&!progress.returned&&<span className="world-complete">{student?'ส่งครบแล้ว เก่งมาก!':'รับงานครบแล้วทุกห้อง'}</span>}{progress.expected===0&&<span className="muted">{student?'ครูยังไม่ได้มอบหมายงาน':'เพิ่มรายชื่อและมอบหมายงานเพื่อเริ่มติดตามความก้าวหน้า'}</span>}</div>
 </section>;
}
export function SubjectRooms({state,subject,sections,selectedId,onDone,onSelect}:{state:AppState;subject:Row;sections:Row[];selectedId:string;onDone:(r:any)=>Promise<void>;onSelect:(id:string)=>void}){
 const [mode,setMode]=useState<'rooms'|'name'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const owner=state.user.role==='admin'||subject.owner_id===state.user.id;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{let r;if(mode==='rooms')r=await api('subject-rooms',{subjectId:subject.id,classrooms:String(f.get('classrooms')).split(/[,\n]+/).map(s=>s.trim()).filter(Boolean)});else r=await api(`subjects/${subject.id}`,{name:f.get('name'),code:f.get('code')},'PATCH');await onDone(r);setMode(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="room-rail"><div><strong>{subject.name}</strong><span>{subject.code} · {sections.length} ห้องที่คุณเข้าถึงได้</span></div><div className="room-pills">{sections.map(c=><button key={c.id} aria-pressed={c.id===selectedId} onClick={()=>onSelect(c.id)}>{c.classroom}</button>)}</div>{owner&&<div className="row"><Button variant="outline" size="sm" onClick={()=>{setMode('rooms');setError('');}}><Plus size={15}/> เพิ่มห้องในวิชานี้</Button><Button variant="ghost" size="sm" onClick={()=>{setMode('name');setError('');}}>แก้ชื่อวิชา</Button></div>}</section>{mode&&<Dialog open onOpenChange={v=>{if(!v&&!busy)setMode(null);}}><DialogContent><DialogHeader><DialogTitle>{mode==='rooms'?'เพิ่มห้องเรียนในรายวิชา':'แก้รายละเอียดรายวิชา'}</DialogTitle><DialogDescription>{mode==='rooms'?`${subject.name} · รายชื่อและคะแนนแยกจากห้องอื่น`:'ชื่อและรหัสเปลี่ยนพร้อมกันทุกห้อง คะแนนและงานยังอยู่ครบ'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={save}>{mode==='rooms'?<label>ห้องเรียน (คั่นด้วยจุลภาค)<Input name="classrooms" placeholder="ม.1/2, ม.1/3" required maxLength={2000}/></label>:<><label>รหัสวิชา<Input name="code" defaultValue={subject.code} maxLength={30} required/></label><label>ชื่อรายวิชา<Input name="name" defaultValue={subject.name} maxLength={100} required/></label></>}{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setMode(null)}>ยกเลิก</Button><BusyButton type="submit" busy={busy}>บันทึก</BusyButton></div></form></DialogContent></Dialog>}</>;
}

