'use client';
import {useEffect,useState} from 'react';
import {BookOpen,Plus,Users,Sparkles,Layers,ChevronLeft,ChevronRight,ArrowDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,type AppState,type Row} from '@/lib/client';
import {subjectProgress} from '@/lib/subject-progress';
import {BusyButton} from './shared';
import {IslandScene} from './island-scene';

export function SubjectWorld({state,courses,activeId,onRoom,onSubject}:{state:AppState;courses:Row[];activeId:string;onRoom:(id:string,view?:string,filter?:string)=>void;onSubject:(id:string)=>void}){
 const subjects=state.subjects.filter(s=>courses.some(c=>c.subject_id===s.id));const signature=subjects.map(s=>s.id).join('|');
 const [allOpen,setAllOpen]=useState(false),[roomOpen,setRoomOpen]=useState(false);
 const [position,setPosition]=useState(0);
 useEffect(()=>{const i=subjects.findIndex(s=>s.id===activeId);if(i>=0)setPosition(i);},[activeId,signature]);
 const index=Math.min(position,subjects.length-1),focused=subjects[index];if(!focused)return null;
 const rooms=courses.filter(c=>c.subject_id===focused.id).sort((a,b)=>a.classroom.localeCompare(b.classroom,'th',{numeric:true})),progress=subjectProgress(state,rooms),student=state.user.role==='student';
 function choose(i:number){const next=(i+subjects.length)%subjects.length;setPosition(next);onSubject(subjects[next].id);}
 function open(id:string,view?:string,filter?:string){onRoom(id,view,filter);}
 const firstMissing=rooms.find(c=>subjectProgress(state,[c]).missing)||rooms[0],firstPending=rooms.find(c=>subjectProgress(state,[c]).pending)||rooms[0],firstReturned=rooms.find(c=>subjectProgress(state,[c]).returned)||rooms[0];
 return <section className="subject-world world-explorer immersive-explorer island-explorer" aria-label="สำรวจรายวิชา"><div className="world-heading"><div><span className="world-kicker"><Sparkles size={16}/> พื้นที่เรียนรู้</span><h2>{student?'วิชาของฉัน':'โลกของห้องเรียน'}</h2></div><div className="row"><span>{subjects.length} วิชา · {courses.length} ห้อง</span><Button variant="ghost" size="sm" onClick={()=>setAllOpen(true)}>เลือกวิชา</Button></div></div>
 <IslandScene subjects={subjects.slice(Math.max(0,Math.min(index-3,subjects.length-8)),Math.max(0,Math.min(index-3,subjects.length-8))+8).map(s=>{const ids=courses.filter(c=>c.subject_id===s.id).map(c=>c.id),tasks=state.assignments.filter(a=>ids.includes(a.course_id)),image=state.files.find(f=>f.mime?.startsWith('image/')&&tasks.some(a=>a.id===f.assignment_id));return {...s,roomCount:ids.length,preview:image?`/api/file/${image.id}`:undefined};})} focusedId={focused.id} onPick={id=>{choose(subjects.findIndex(s=>s.id===id));setRoomOpen(true);}}/>
 <div className="island-focused-label"><h3>{focused.name}</h3><span>{focused.code} · {rooms.length} ห้อง{!student&&` · ${progress.students} คน`}</span></div><div className="world-pagination"><Button variant="ghost" size="sm" disabled={subjects.length<2} onClick={()=>choose(index-1)} aria-label="วิชาก่อนหน้า"><ChevronLeft size={23}/></Button><span aria-live="polite" aria-atomic="true">{index+1} / {subjects.length} วิชา</span><Button variant="ghost" size="sm" disabled={subjects.length<2} onClick={()=>choose(index+1)} aria-label="วิชาถัดไป"><ChevronRight size={23}/></Button></div>
 <div className="world-room-row"><span>เลือกห้องเรียน</span><div className="planet-rooms">{rooms.map(c=><button key={c.id} onClick={()=>open(c.id)}>{c.classroom}{!!c.archived&&' · ประวัติ'}</button>)}</div><div className="world-status"><strong>ส่งแล้ว {progress.submitted} / {progress.expected} งาน</strong><span>{progress.percentage}%</span><div className="world-status-meter" role="progressbar" aria-label="ความคืบหน้าการส่งงาน" aria-valuenow={progress.percentage} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${progress.percentage}%`}}/></div></div></div>
 <div className="world-quick-actions">{progress.pending>0&&<Button variant="outline" onClick={()=>open(firstPending.id,student?'courses':firstPending.can_edit?'review':'matrix')}>{student?'งานรอตรวจ':'ตรวจงาน'} {progress.pending} งาน</Button>}{progress.missing>0&&<Button onClick={()=>open(firstMissing.id,student?'courses':'followup',student?'missing':undefined)}>{student?'ไปส่งงาน':'ติดตามงานที่ยังไม่ส่ง'} {progress.missing} งาน</Button>}{progress.returned>0&&<Button variant="outline" onClick={()=>open(firstReturned.id,student?'courses':'followup',student?'returned':undefined)}>งานที่ต้องแก้ {progress.returned} งาน</Button>}{progress.expected>0&&!progress.missing&&!progress.returned&&<span className="world-complete">{student?'ส่งครบแล้ว เก่งมาก!':'รับงานครบแล้วทุกห้อง'}</span>}{progress.expected===0&&<span className="muted">{student?'ครูยังไม่ได้มอบหมายงาน':'เพิ่มรายชื่อและมอบหมายงานเพื่อเริ่มติดตามความก้าวหน้า'}</span>}</div>
 <button className="explore-more" onClick={()=>document.getElementById('world-analytics')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowDown size={18}/> ดูสถิติการส่งงาน</button><Dialog open={roomOpen} onOpenChange={setRoomOpen}><DialogContent className="island-room-dialog"><DialogHeader><DialogTitle>{focused.name}</DialogTitle><DialogDescription>{focused.code} · เลือกห้องเรียนเพื่อดูงานและคะแนน</DialogDescription></DialogHeader><div className="island-room-list">{rooms.map(c=><button key={c.id} onClick={()=>{setRoomOpen(false);open(c.id);}}><Layers size={22}/><span><strong>{c.classroom}</strong><small>{c.archived?'เก็บเป็นประวัติ':'เปิดงานและคะแนน'}</small></span></button>)}</div></DialogContent></Dialog><Dialog open={allOpen} onOpenChange={setAllOpen}><DialogContent className="subject-picker"><DialogHeader><DialogTitle>เลือกรายวิชา</DialogTitle><DialogDescription>{subjects.length} วิชาในภาคเรียนนี้</DialogDescription></DialogHeader><Button variant="outline" onClick={()=>{onSubject('all');setAllOpen(false);}}>แสดงสถิติทุกวิชา</Button><div className="subject-picker-grid">{subjects.map((s,i)=><button key={s.id} onClick={()=>{choose(i);setAllOpen(false);}} aria-pressed={s.id===focused.id}><BookOpen size={22}/><span><small>{s.code}</small><strong>{s.name}</strong></span></button>)}</div></DialogContent></Dialog></section>;
}
export function SubjectRooms({state,subject,sections,selectedId,onDone,onSelect}:{state:AppState;subject:Row;sections:Row[];selectedId:string;onDone:(r:any)=>Promise<void>;onSelect:(id:string)=>void}){
 const [mode,setMode]=useState<'rooms'|'name'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const owner=state.user.role==='admin'||subject.owner_id===state.user.id;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{let r;if(mode==='rooms')r=await api('subject-rooms',{subjectId:subject.id,classrooms:String(f.get('classrooms')).split(/[,\n]+/).map(s=>s.trim()).filter(Boolean)});else r=await api(`subjects/${subject.id}`,{name:f.get('name'),code:f.get('code')},'PATCH');await onDone(r);setMode(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="room-rail"><div><strong>{subject.name}</strong><span>{subject.code} · {sections.length} ห้องที่คุณเข้าถึงได้</span></div><div className="room-pills">{sections.map(c=><button key={c.id} aria-pressed={c.id===selectedId} onClick={()=>onSelect(c.id)}>{c.classroom}</button>)}</div>{owner&&<div className="row"><Button variant="outline" size="sm" onClick={()=>{setMode('rooms');setError('');}}><Plus size={15}/> เพิ่มห้องในวิชานี้</Button><Button variant="ghost" size="sm" onClick={()=>{setMode('name');setError('');}}>แก้ชื่อวิชา</Button></div>}</section>{mode&&<Dialog open onOpenChange={v=>{if(!v&&!busy)setMode(null);}}><DialogContent><DialogHeader><DialogTitle>{mode==='rooms'?'เพิ่มห้องเรียนในรายวิชา':'แก้รายละเอียดรายวิชา'}</DialogTitle><DialogDescription>{mode==='rooms'?`${subject.name} · รายชื่อและคะแนนแยกจากห้องอื่น`:'ชื่อและรหัสเปลี่ยนพร้อมกันทุกห้อง คะแนนและงานยังอยู่ครบ'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={save}>{mode==='rooms'?<label>ห้องเรียน (คั่นด้วยจุลภาค)<Input name="classrooms" placeholder="ม.1/2, ม.1/3" required maxLength={2000}/></label>:<><label>รหัสวิชา<Input name="code" defaultValue={subject.code} maxLength={30} required/></label><label>ชื่อรายวิชา<Input name="name" defaultValue={subject.name} maxLength={100} required/></label></>}{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setMode(null)}>ยกเลิก</Button><BusyButton type="submit" busy={busy}>บันทึก</BusyButton></div></form></DialogContent></Dialog>}</>;
}

