'use client';
import {useState} from 'react';
import {BookOpen,Plus,Users,Sparkles,Layers} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api,type AppState,type Row} from '@/lib/client';
import {BusyButton} from './shared';

export function SubjectWorld({state,courses,onRoom,onSubject}:{state:AppState;courses:Row[];onRoom:(id:string)=>void;onSubject:(id:string)=>void}){
 const subjects=state.subjects.filter(s=>courses.some(c=>c.subject_id===s.id));
 return <section className="subject-world" aria-label="รายวิชาและห้องเรียน"><div className="world-heading"><div><span className="world-kicker"><Sparkles size={16}/> พื้นที่เรียนรู้</span><h2>รายวิชาของ{state.user.role==='student'?'ฉัน':'ภาคเรียนนี้'}</h2></div><span>{subjects.length} วิชา · {courses.length} ห้องเรียน</span></div><div className="subject-planets">{subjects.map((s,i)=>{const rooms=courses.filter(c=>c.subject_id===s.id),students=new Set(state.enrollments.filter(e=>e.active&&rooms.some(c=>c.id===e.course_id)).map(e=>e.student_id));return <article className={`subject-planet planet-${i%4}`} key={s.id}><button className="planet-orb" onClick={()=>onSubject(s.id)} aria-label={`ดูภาพรวม ${s.code} ${s.name} ทุกห้อง`}><BookOpen size={35}/><span>{s.code}</span></button><h3>{s.name}</h3><div className="planet-meta"><Layers size={14}/>{rooms.length} ห้อง{state.user.role!=='student'&&<><Users size={14}/>{students.size} คน</>}</div><div className="planet-rooms">{rooms.map(c=><button key={c.id} onClick={()=>onRoom(c.id)}>{c.classroom}{!!c.archived&&' · ประวัติ'}</button>)}</div></article>;})}</div></section>;
}
export function SubjectRooms({state,subject,sections,selectedId,onDone,onSelect}:{state:AppState;subject:Row;sections:Row[];selectedId:string;onDone:(r:any)=>Promise<void>;onSelect:(id:string)=>void}){
 const [mode,setMode]=useState<'rooms'|'name'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const owner=state.user.role==='admin'||subject.owner_id===state.user.id;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{let r;if(mode==='rooms')r=await api('subject-rooms',{subjectId:subject.id,classrooms:String(f.get('classrooms')).split(/[,\n]+/).map(s=>s.trim()).filter(Boolean)});else r=await api(`subjects/${subject.id}`,{name:f.get('name'),code:f.get('code')},'PATCH');await onDone(r);setMode(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="room-rail"><div><strong>{subject.name}</strong><span>{subject.code} · {sections.length} ห้องที่คุณเข้าถึงได้</span></div><div className="room-pills">{sections.map(c=><button key={c.id} aria-pressed={c.id===selectedId} onClick={()=>onSelect(c.id)}>{c.classroom}</button>)}</div>{owner&&<div className="row"><Button variant="outline" size="sm" onClick={()=>{setMode('rooms');setError('');}}><Plus size={15}/> เพิ่มห้องในวิชานี้</Button><Button variant="ghost" size="sm" onClick={()=>{setMode('name');setError('');}}>แก้ชื่อวิชา</Button></div>}</section>{mode&&<Dialog open onOpenChange={v=>{if(!v&&!busy)setMode(null);}}><DialogContent><DialogHeader><DialogTitle>{mode==='rooms'?'เพิ่มห้องเรียนในรายวิชา':'แก้รายละเอียดรายวิชา'}</DialogTitle><DialogDescription>{mode==='rooms'?`${subject.name} · รายชื่อและคะแนนแยกจากห้องอื่น`:'ชื่อและรหัสเปลี่ยนพร้อมกันทุกห้อง คะแนนและงานยังอยู่ครบ'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={save}>{mode==='rooms'?<label>ห้องเรียน (คั่นด้วยจุลภาค)<Input name="classrooms" placeholder="ม.1/2, ม.1/3" required maxLength={2000}/></label>:<><label>รหัสวิชา<Input name="code" defaultValue={subject.code} maxLength={30} required/></label><label>ชื่อรายวิชา<Input name="name" defaultValue={subject.name} maxLength={100} required/></label></>}{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setMode(null)}>ยกเลิก</Button><BusyButton type="submit" busy={busy}>บันทึก</BusyButton></div></form></DialogContent></Dialog>}</>;
}

